### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by jayvdb** [pymupdf/PyMuPDF#1002]
Currently to test this package, the openSUSE build only does `import fitz`.

It would be nice if there was something a bit more complicated than that to check that it is working correctly.

**Comment by JorjMcKie** [comment]
I actually do not provide any test data at all - nothing for openSUSE, nor any other platform.
That test for a working import only happens on the Travis CI machines and only serves the purpose to do a shakedown test for correct wheel generation on Travis. That's all.
The actual test runs happen on my machine mostly for Windows - on which all the development takes place. With the generated wheels for Linux on Travis, I then do tests on my local Ubuntu.
Among them are some basic function tests, but also tests for memory leaks.
New functions (based on C code only) also get an extra round on Linux, because that platform is a lot pickier as far as segmentation faults are concerned.

So I guess I need your input, which type of tests you would like to see and where they should be located ...

**Comment by jayvdb** [comment]
Default answer: any tests you have, and they should be located under `tests/`.

Perhaps you could email me a zip of the test code that you have, and I could sift through it and be able to reply on which parts are useful and how to structure them so that they are usable by distro testers.

**Comment by JorjMcKie** [comment]
> zip of the test code

good idea, thanks, I will prepare something.

**Comment by JorjMcKie** [comment]
Here is a first cut.
I went through my material and made a ``tests/`` folder. If you invoke `pytest` in that folder, 25 or so tests should run (successfully).
I will certainly extend this over time, but I hope it is a start for you.
If you would like to see anything else in there, please drop me a request.
[tests.zip](https://github.com/pymupdf/PyMuPDF/files/6297352/tests.zip)
