### ISSUE TITLE
[help request] File growth after saving 

### ISSUE THREAD

**Issue by tokland** [pymupdf/PyMuPDF#1003]
## Describe the problem

I have a 16Mb PDF to process. On save, with no modifications yet, it grows up to 27Mb. Not the end of the world, but I am curious if there some way to keep it closer to the original.

## To Reproduce

OS: Arch Linux
Python 3.9.2 [GCC 10.2.0]
PyMuPDF: 1.18.12 (installed with pip)
Input file: https://www.mitma.es/recursos_mfom/paginabasica/recursos/adr_2021.pdf

```
import os.path
import fitz

input_file = "adr_2021.pdf"
output_file = "adr_2021-2.pdf"
doc = fitz.open(input_file)

# garbage=3 is very slow, I have to forcefully kill it 15 minutes in.
doc.save(output_file, garbage=2) 

getsize = os.path.getsize
print("Original: {:,}, Saved: {:,}".format(getsize(input_file), getsize(output_file)))

# Original: 15,814,283, Saved: 26,917,612
```

**Comment by JorjMcKie** [comment]
Hi,
an interesting case! The file is a relatively straightforward text document. It even has no table of contents - unusual for a text file with 1250 pages.
It has an xref count of 146.086 ... **_but_** of those numbers, **_142.770 are free_** - i.e. point to no object in the PDF. The range of unused numbers is in the middle of the xref table.
Therefore, with garbage collection options 2 (compact xref table) a lot of the actually only 3.300 **_existing_** objects (all those after the empty numbers range) get new xref numbers - and hence their object definition must be stored one more time. This explains the file growth.
I am not clear yet, how to explain the long duration of option 3.

But I have a suggestion:
Because of the actual simplicity of the document, copy it to a new one via ìnsert_pdf:
```python
>>> doc=fitz.open("adr_2021.pdf")
>>> doc.xref_length()
146086
>>> new = fitz.open()
>>> new.insert_pdf(doc, show_progress=100)
Inserting 'adr_2021.pdf' at 'memory PDF'
Inserted 100 of 1249 pages.
Inserted 200 of 1249 pages.
Inserted 300 of 1249 pages.
Inserted 400 of 1249 pages.
Inserted 500 of 1249 pages.
Inserted 600 of 1249 pages.
Inserted 700 of 1249 pages.
Inserted 800 of 1249 pages.
Inserted 900 of 1249 pages.
Inserted 1000 of 1249 pages.
Inserted 1100 of 1249 pages.
Inserted 1200 of 1249 pages.
>>> new.save("new.pdf", garbage=3, deflate=True)
>>> new.xref_length()
3275
```
This takes just a few seconds and creates a clean, neatly compressed file of only 10 MB!
We could have copied over the TOC (table of contents) as well (it's empty in this case) by:
```python
new.set_toc(doc.get_toc(simple=False))
# then save the new document
```

**Comment by JorjMcKie** [comment]
I now have a few more insights:
The file has had one incremental save. What happened there was a change from standard xref table format (which is in ASCII text form) to the binary compressed xref table format.
But without removing the old table (b/o **_incremental_** update). So a lot of wasted space and additional complexity for **_any_** optimization.
In this case - because of only 2% of the total xref entries are in use - a lot of complex processing has to occur: garbage collection is an **_in-place_** type of optimization ...

**Comment by tokland** [comment]
It worked, now the output file is just 10.8Mb.

Thanks for your support, and for PyMuPDF, it's a joy to use!

**Comment by JorjMcKie** [comment]
Additional comment:
You may want to re-establish as much of an old file as possible.
Method `insert_pdf()` is a page-controlled process: nothing is copied, that is not referenced by any page. So, links and annotations **_are_** indeed copied by default and therefore no concern.
But in the general case (I covered TOC), a few more things may be of interest, like metadata and embedded files, or even page labels.
These aspects would need extra attention, but they can be copied over as well, before you save the new file.

**Comment by JorjMcKie** [comment]
And an extra big **_THANK YOU_** for your acknowledgement ❤️!!!
Just saw it arriving.
