### ISSUE TITLE
Redacted image still available

### ISSUE THREAD

**Issue by billder677** [pymupdf/PyMuPDF#1027]
I am using the redaction annotation feature to redact parts of an image. I am saving the image's xref to do the redactions one by one via an API I built.

The code I use is this

```
doc = fitz.open(file_path)
rect = fitz.Rect(...)
page = doc.load_page(...)
page.addRedactAnnot(rect, 'redacted')
page.apply_redactions()
doc.saveIncr() # I want to keep filename and some files have some kind of encryption
doc.close()
```

### What happens
- Image in PDF is redacted when viewing it in Firefox
- When loading the image programmatically via `fitz.Pixmap(doc, xref)` I get the original unredacted image out of the pdf file
- I can load the redacted image by it's new xref, so both images are still present in the pdf

### What should happen
- The original's image should be deleted if a new redacted one is created

Why can I still load the old image via it's xref? Is this a real issue or does saveIncr() prevent the correct behaviour?

**Comment by JorjMcKie** [comment]
Everything works as you requested:
* you used `page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_PIXELS)`, because this is the default
* this option does **_not delete_** the image, but empties overlapping pixels, resulting in the original image with a white rectangle

Use a different option if you want other things to happen: you can either remove every image which overlaps any redaction - even if only a bit - or leave every image intact. Same thing if  the complete old image now becomes white ... 😎

If your intention was **_to replace_** some image, you should obviously not allow defaulting the apply_redaction option.

**Comment by JorjMcKie** [comment]
Additional comment:
When you make this type of change, be aware that your file will grow, maybe very significantly, if you use incremental update:
* the old image still is physically present and consumes the same file size portion (even if no longer accessible if you use the correct redaction option)
* the new image is also present - maybe even uncompressed, depending on how sophisticated you inserted it

**Comment by billder677** [comment]
Thanks for your reply. I think I need to rephrase my problem. I want to partly redact images, which works with the redact annotation. For compliance reasons I need the original image to be deleted. So what I am doing is this:

- `page.get_images(full=True)` returns xref 42 for image
- 
- Partly redact image with xref 42 via `page.addRedactAnnot(rect, 'redaced')`
- Apply redactions with `page.apply_redactions()`
- `page.get_images(full=True)` returns xref 424 for image. The old xref 42 is not returned anymore.
- Save that file with `saveIncr()`

When I open the file again:
- PDF viewer shows redacted image
- Loading the old xref 42 via `fitz.Pixmap(doc, xref)` returns the original unredacted image
- Loading xref 424 returns the partly redacted image

Is this the expected behaviour? Reading the docs I understand that applying the redactions also deletes the original image entirely. How can I delete the old image and just keep the redacted one?

**Comment by JorjMcKie** [comment]
Ah, got you now. Thanks for the clarification.
Indeed:
MuPDF's logic here carries some unspoken implications - which I probably also did not mention explicitely enough, or even misleadingly / wrong (I will check):
* When redacting an image on some page, the old image still exists but is (potentially) unreferenced.
* Unreferenced object physical removal will only take place on non-incremental saves.
* Altering PDF by such huge data amounts as images imply, is unexpected and definitely counterproductive for incremental saves.
* The same old image might still be used on other pages - MuPDF does not assume it should be shown redacted everywhere. A sound position in my mind.

If you are sure that the old image is used nowhere else, you can delete it via low-level code, simply by `doc.delete_object(xref)`.

**Comment by billder677** [comment]
Thanks for the explanation. I can get this to work from here on.

**Comment by suparnaj3** [comment]
@JorjMcKie, apply_redactions will not redact the overlapping drawings, am I correct?

Is there a way to redact drawings?

**Comment by JorjMcKie** [comment]
No, there is not. Only text, images and links are affected.

**Comment by suparnaj3** [comment]
Ok, thanks. It would be nice to add that too as a feature.

**Comment by JorjMcKie** [comment]
>  It would be nice to add that too as a feature.

This is up to MuPDF - not PyMuPDF. There are no plans known for doing this ever.

**Comment by JorjMcKie** [comment]
Just consider what that would mean to see that it is **_even impossible_** to achieve:

If there is a line crossing your redact rectangle with both of its points outside that rectangle: how on earth (1) can you even find out, and (2) respond to this situation? It would **_not even_** make sense defining 2 line pieces ending at and beginning at the rectangle border, because the original line may be part of a complex drawing, which may react different as a whole in response to this.
All you can do is overlaying the redact rect with e.g. white to make stuff underneath invisible.

**Comment by suparnaj3** [comment]
Yeah, it makes sense.

Thank you.
