### ISSUE TITLE
Change delete_pages() API

### ISSUE THREAD

**Issue by fgallaire** [pymupdf/PyMuPDF#1042]
_delete_pages()_ API looks weird to me.

Have to loop manualy on _delete_page()_ to delete multiple non-successive pages.
_delete_pages()_ should have only one argument, a list of int of page and do this job.

_from_page, to_page_ arguments easily replaced by _range()_

**Comment by JorjMcKie** [comment]
The performance difference of multiple `doc.delete_page()` executions and one excution of `doc.delete_pages()` for successive pages is **_very_** significant! It is a costly method, because links pointing to any deleted page must be removed from **_all the remaining pages_**.
That's why I have two methods at all. Internally, `delete_page()` is just a wrapper for `delete_pages()` with identical arguments.
Yes: I **_could_** accept a range or slice parameter for `delete_pages()`, but only one that has step=1. Because you would use 2 arguments for range, there would be no advantage.

**Comment by fgallaire** [comment]
I have to delete multiple non-successive pages, it's a common usecase, I want a method to do so, in a simple/correct world it should be `delete_pages()` with a list as argument.
Accepting range to have a clean API, very efficient if it's a range, and just ok for a list of non-successive pages.

**Comment by JorjMcKie** [comment]
I am very busy at the moment, so this will have to wait a while.
On the other hand, the code doing the actual work is all there. Your request amounts to technically just re-arranging and shuffling around existing material.
So if you would submit a PR things could be faster.

**Comment by JorjMcKie** [comment]
Ignore my previous post. I a found a simple way to implement this:
In adition to the old argument spec with keywords, now also a list, tuple or range object can be specified.
Best of all: these sequences need not contain consecutive page numbers - gaps are ok **_without_** performance penalties.

Will publish this with the coming version 1.18.13.

**Comment by JorjMcKie** [comment]
Fixed in v1.18.13, which was just published.
