### ISSUE TITLE
Make getPageXXXList() functions support both index and Page object

### ISSUE THREAD

**Issue by Vbbab** [pymupdf/PyMuPDF#1063]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Potentially add an issue reference.

This is not really a problem, but a mild annoyance and inconsistency. Functions of `doc.getPage[XXX]List()` (e.g. `getPageImageList()`) currently only take in a page *index*, traversed by loops like `for i in range(len(doc))`.

**Describe the solution you'd like**

It would also be more convenient if one could simply traverse the pages themselves (`for page in doc`), and use the `fitz.fitz.Page` object as a parameter to `doc.getPage[XXX]List()`. The functions could then check the type, only accepting either `int` or `fitz.fitz.Page`. If there is some internal acquiring of the `Page` object via the given index, this step could be skipped for a `Page` object parameter.

**Describe alternatives you've considered**
Are there several options for how your request could be met?

As mentioned above, if there is some internal acquiring of the `Page` object that is operated on, this step could be skipped when giving a direct `Page` object. Although if there are some links between the `Page` and the `Document` that might require additional code to check...

**Additional context**
![image](https://user-images.githubusercontent.com/44555590/119759179-a6d24980-be5c-11eb-8d0b-beb7a7805e54.png)

**Comment by JorjMcKie** [comment]
This is the situation:
1. The new method names are `doc.get_page_images(pno)` instead of `doc.getPageImageList(pno)`, etc.
2. The methods **_do not need a page to be loaded_** to do their job! Neither do they internally load the page. They only operate on the page's object definition source.
3. These `Document` methods have mirroring `Page` methods: `page.get_images()`, `page.get_fonts()`, `page.get_xobjects()`. Conveniently to be used when you have loaded the page anyway. They internally execute their `Document`counterparts, e.g. `page.parent.get_page_images(page.number)` - which does not incur any overhead. They can obviously be used in loops `for page in doc: ...` as you suggest.

It would of course be no big deal to do an object type check in `doc.get_page_images(page)` and use `page.number` when it finds the argument not to be an integer.

**Comment by JorjMcKie** [comment]
Update:
``doc.get_page_xxx()`` methods will accept a page number (as before), or a page object as first positional argument in the next version.
Pertains to ``"xxx"`` = ``images``, ``fonts`` and ``xobjects``.
