### ISSUE TITLE
"Invisible" text contained within drawing or "Figure" cannot be filtered out

### ISSUE THREAD

**Issue by inf3rnus** [pymupdf/PyMuPDF#1091]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)

Issue occurs with the pdf for this research paper: https://arxiv.org/pdf/1706.03762

Text that is part of a drawing has a bbox outside of the drawing, and while not rendered when the actual pdf is viewed through a reader, when using PyMuPdf it is extracted as text from the document, with a hex color of #020202.

This occurs on page 15 of the document (last page), as well as pages 14 and 13. Look at page 15 though for a clear example. The text that is showing up in the results is "Input-Input Layer5"

The text is not removed via scrub, and cannot be removed via a redaction annotation when passing the rects from drawings to the applyRedactions method.

Pdfminer.six shows these text blocks as being nested inside of "figures" which I'm assuming to be drawings, if they're not drawings, then PyMuPdf is failing to extract the images for the page. See the screenshot I've included :)

## To Reproduce (mandatory)
1. DL the file above and execute the following:
```
doc = fitz.open(pdf_path)
doc.scrub()

def get_image_list(doc):
  # for i in range(len(doc)):
  imglist = doc.getPageImageList(14)
  print(imglist)

# no images listed for the page
get_image_list(doc)

def extract_content(doc):
  for page_number, page in enumerate(doc, 1):
    if page_number == 15:

    # try this to see how one of the instances of  "Input-Input Layer5" persists
    # drawings = page.get_drawings()

    # for drawing in drawings:
    #   # try:
    #     page.add_redact_annot(drawing['rect'])
    #   # except:
    #   #   print('woops')

    # page.apply_redactions()
      blocks = page.getText('dict')['blocks']
      print(blocks)
# might be wise to save the results as JSON for investigation, but you will see  "Input-Input Layer5" popping up in the results
extract_content(doc)
```
## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

Either there are images that are not being extracted, that would allow us to remove this text by bbox, or we do not have a way of filtering out text contained within drawings where the text has a bbox outside of the drawing.

## Screenshots (optional)
Here's some output from pdfminer.six for page 15

![image](https://user-images.githubusercontent.com/5959983/122084662-41201000-cdbf-11eb-93bd-2151233b7fb9.png)

Take a look at the pdf rendered with pdf.js as well, you will see this invisible text is selectable:

![image](https://user-images.githubusercontent.com/5959983/122084795-60b73880-cdbf-11eb-8c2c-b1aef0361bd9.png)

## Your configuration (mandatory)
 - Operating system Ubuntu 18.04 LTS
 - Python version, 3.7
 - PyMuPDF  PyMuPDF==1.18.13, Conda

**Comment by JorjMcKie** [comment]
If I read your issue carefully, I see no PyMuPDF behaviour that does not comply with the stated features.
So what is the bug?
It seems you are just missing something and should instead have requested an enhancement or asked a question.

If you read the documentation, you will find, that the list `page.get_images()`, resp. `doc.get_page_images()` may be incomplete under certain conditions.
You will also find, that in contrast to this, the list `page.get_image_info()` will always be complete, as it includes also images not reachable via the page's `/Resources`.
In your case, page 15 has zero images: `page.get_image_info() = []`.
But it does have drawings: `len(page.get_drawings()) = 434`. Each member of this list of dictionaries has a key "rect" which is the area that this (sub-) drawing covers.
So you could check if text is intersecting some of the drawing rectangles and remove it via redaction annotations.
Redactions do not / cannot remove drawings.
But there is no way (currently) to determine if text is hidden by something and thus invisible because of this type of situation.
So this idea may (nd probably will) lead to undesired text removals.

**Comment by JorjMcKie** [comment]
Actual invisibility is quite difficult to determine - even if you are able to detect that text occurs inside a clip or "under" some other object, because you also have to inspect the covering object: it may be partially transparent, or may itself become invisible if other conditions are met (e.g. optional contents conditions are met or not - which always is a temporary condition that may change programmatically or interactively).
The effort to implement this detection is far beyond any effort I am willing to invest inside PyMuPDF. Things may change of course should the base library MuPDF decide to offer something here. And you are of course free to request this feature there, https://bugs.ghostscript.com/enter_bug.cgi

So I am going to close this issue.
