### ISSUE TITLE
Multiple button widgets with the same name but different co-ordinates. Does PyMuPDF widget contain properties of each widget to differentiate each box?

### ISSUE THREAD

**Issue by AIMLAPP** [pymupdf/PyMuPDF#1092]
Hi,

I have been using PyMuPDF to extract field names and co-ordinates of widgets in a PDF form.

I have 5 fields, all of them have the same field name but different co-ordinates. I believe this happened because they are radio fields.

I understand that PyMuPDF doesn't currently support interconnected buttons. But is there a way to use PyMuPDF to identify which widget is which?

For instance, the widgets (tick boxes): [Mr, Mrs, Miss, Ms, Dr] all have the same field_name "Title", but with different co-ordinates. 

E.g.
Title:
100, 50, 115, 55

Title:
120, 125, 50, 55

Is PyMuPDF able to identify which tickbox and co-ordinate belongs to Mr, Mrs, Ms, Dr etc? Perhaps PyMuPDF widgets contains properties of the field that could indicate this?
For example, for title, pdftk is able to show the stateoptions of the field "Title" as Mr, Mrs, Ms, Miss and Dr.
I decided to use PyMuPDF instead of pdftk because pdftk did not extract co-ordinates.

The PDF document I used can be found here on page 2:
https://drive.google.com/file/d/1ZsEvbgGrcGhL_9xbXyIsEBQdyEFXzFpT/view?usp=sharing

**Comment by JorjMcKie** [comment]
Hm, not easy right now. The problem is, that those titles are not part of the widget definition in any way, but separate, simple text of the page.
Just as an aside comment: the fields in your PDF are not radio buttons, but interconnected check boxes.
Anyway, check boxes have two different states which each are implemented by different PDF objects (i.e. xrefs). To distinguish them, the so-called appearance object (a PDF dictionary which all annotations have, inclusing widgets) has two subdictionaries. In PDF definition syntax this looks like so for a check box in your PDF:
```postscript
>>> print(doc.xref_object(160))  # first checkbox ("Mr")
<<
  /AP <<  % appearance dictionary
    /D <<  % "down" appearance
      /Mr 84 0 R
      /Off 83 0 R
    >>
    /N <<  % normal appearance
      /Mr 86 0 R
      /Off 85 0 R
    >>
  >>
  /AS /Off  % current state
  /F 4
  /MK <<
    /BC [ 1 1 1 ]
    /BG [ 1 ]
  >>
  /P 1 0 R
  /Parent 168 0 R
  /Rect [ 144.841 750.095 159.706 764.96 ]
  /Subtype /Widget
  /Type /Annot
>>
```
As you can see, you may be as lucky as you are here: the "selected" state (i.e. the field is checked) has been named like the page text to its left side.
If "Mr" is selected, then the value of aside of `/AS` is set to `/AS /Mr`.

As unfortunate as all this may be, you could go hunting down the names of the "normal" `/AP` states and the value of `/AS`like this:
```python
>>> # 160 = xref of first checkbox
>>> doc.xref_get_key(160, "AP/N")
('dict', '<</Mr 86 0 R/Off 85 0 R>>')
>>> doc.xref_get_key(160, "AS")
('name', '/Off')
>>> 
```
It shouldn't be difficult to turn this into a proper widget attribute like `widget.state_names` and return a dictionary like
```python
>>> widget.state_names
{"normal": "Mr", "down": "Mr"}
>>> # which would be None in non-button cases
```
But right now ... sorry, only the low-level code approach is available.

**Comment by JorjMcKie** [comment]
If one of the titles is selected, the corresponding field value will be set to "Mr" etc., **_not_** to `True`.
Interestingly, because those boxes are interconnected, MuPDF will set the field value of **_all_** check boxes in that group to "Mr".
Wasn't aware of this myself ...

**Comment by JorjMcKie** [comment]
Here is a little script, that should work in many / most cases:
[btn-states.zip](https://github.com/pymupdf/PyMuPDF/files/6662107/btn-states.zip)
For page 2 of the test PDF, it does this:
```bash
python btn-states.py
('Title', {'down': ['Mr', 'Off'], 'normal': ['Mr', 'Off']})
('Title', {'down': ['Mrs', 'Off'], 'normal': ['Mrs', 'Off']})
('Title', {'down': ['Miss', 'Off'], 'normal': ['Miss', 'Off']})
('Title', {'down': ['Ms', 'Off'], 'normal': ['Ms', 'Off']})
('Title', {'down': ['Dr', 'Off'], 'normal': ['Dr', 'Off']})
('Gender', {'down': ['Female', 'Off'], 'normal': ['Female', 'Off']})
('Gender', {'down': ['Male', 'Off'], 'normal': ['Male', 'Off']})
('Title second person', {'down': ['Mr', 'Off'], 'normal': ['Mr', 'Off']})
('Title second person', {'down': ['Mrs', 'Off'], 'normal': ['Mrs', 'Off']})
('Title second person', {'down': ['Miss', 'Off'], 'normal': ['Miss', 'Off']})
('Title second person', {'down': ['Ms', 'Off'], 'normal': ['Ms', 'Off']})
('Title second person', {'down': ['Dr', 'Off'], 'normal': ['Dr', 'Off']})
('Gender Second person',
 {'down': ['Female', 'Off'], 'normal': ['Female', 'Off']})
('Gender Second person', {'down': ['Male', 'Off'], 'normal': ['Male', 'Off']})
```

**Comment by JorjMcKie** [comment]
Just to let you know: I will include this method in the next version.
