### ISSUE TITLE
PDF > HTML: Font is too big (therefore text divs are overlapping)

### ISSUE THREAD

**Issue by gustavklopp** [pymupdf/PyMuPDF#1108]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When converting a PDF to a HTML file, the result has font which are bigger than the original (taking the size of images in the page for example) resulting in overlapping of text section.

## To Reproduce (mandatory)
Opening a PDF file which contains several text section:

```
                doc = fitz.open(uploadedfile_path)
                content = ''
                for i, page in enumerate(doc):
                    text = page.getText("html")
                    content += text
                with open('result.html', 'w') as result:
                    result.write(content)
                doc.close()
```

## Expected behavior (optional)
Font of the same (relative) size than the original.

## Screenshots (optional)
original PDF:
![Zaslonska slika 2021-06-25 17-54-38](https://user-images.githubusercontent.com/6438275/123452173-735f1800-d5de-11eb-8af1-9dc9a8c0e6fc.png)

result HTML:
![Zaslonska slika 2021-06-25 17-53-20](https://user-images.githubusercontent.com/6438275/123451980-44e13d00-d5de-11eb-9d2f-01afa2642fad.png)

## Your configuration (mandatory)
 - Arch Linux
 - Python 3.8.10
 - PyMuPDF==1.18.14

**EDIT** 
The bug disappears for Google Chrome! What makes the HTML produced wrong on other browser?

**Comment by JorjMcKie** [comment]
1. As explained in the documentation, the conversion to HTML is not perfect. There even is an explanation / guide on how to remedy some of these problems.
2. Because PyMuPDF directly invokes MuPDF base functions for the outputs as (X)HTML and XML, it has no handle to influence the results.
2. Please crosscheck with the original CLI tool of MuPDF: `mutool convert -o out.html file.pdf page#` to confirm that the issue is in MuPDF itself - not in PyMuPDF.
3. Please submit an issue to MuPDF's bug tracker https://bugs.ghostscript.com/enter_bug.cgi accompanied by a sample PDF.

> The bug disappears for Google Chrome! What makes the HTML produced wrong on other browser?

HTML  - as opposed to PDF - does not embed fonts - it just names them. It is up to the respective browser to choose a font based on that name in the HTML file. This choice (and the respective reservoir for fonts incorporated in the browser) will therefore be different for each browser, and also per platform where the browser is invoked on.

**Comment by gustavklopp** [comment]
Ok, I will more study how Firefox handles this since the problem seems to come from here. Thanks!
