### ISSUE TITLE
Pixmap `samples` seems to not point to a valid address unless `len` is called on it

### ISSUE THREAD

**Issue by PowerSnail** [pymupdf/PyMuPDF#1210]
## Describe the bug

To be honest, I'm not exactly sure if this is a `PyMuPDF` bug, but here it goes:

If I get a pixmap from a PDF page, and another library (PyQt, for example) tries to use `pixmap.samples` as if it is a raw buffer, it triggers an Address boundary error. However, if I call `len(pixmap.samples)` first, this doesn't happen. The code snippet below explains it better than words.

The Qt documentation says that the `QImage` will treat the first argument as a raw pointer to a byte array. So, my guess would be that some part of `samples` isn't actually allocated until I access it in Python. If a native library tries to dereference the raw pointer directly, it triggers SIGSEGV.

## To Reproduce (mandatory)

```
from PyQt6 import QtGui
import fitz

doc = fitz.Document()
page = doc.new_page()
pixmap = page.get_pixmap()

# len(pixmap.samples)  # uncomment this line to eliminate the error

image = QtGui.QImage(pixmap.samples, pixmap.width, pixmap.height, QtGui.QImage.Format.Format_RGB888)
print("image[0, 0]: {}".format(str(image.pixelColor(0, 0).name())))
```

## Your configuration (mandatory)
 - OpenSUSE
 - Python 3.9.6
 - PyMuPDF 1.18.16

**Comment by JorjMcKie** [comment]
First time I am hearing of this 😯! It must have worked all the time before ... up to PyQt5. Is this happening since Qt version 6?
What happens if you use `bytearray(pixmap.samples)` instead?
`pixmap.samples` is **_not_** a raw pointer, but a `bytes` object created when (each time!) accessing the property - something defined like
```python
    @property
    def samples(self) -> AnyType:
        """The area of all pixels."""

        return _fitz.Pixmap_samples(self)
```
I never liked that design actually: within MuPDF, there exists a binary memory area obviously, which could be nicely addressed directly by something that knows how to do that. Instead, the property makes a `bytes` of that large beast - each time.
I **_could_** make a real raw pointer in Python using C function `PyObject* PyLong_FromVoidPtr(void *p)` (where `p` is the memory address of the samples area) and store it in an attribute like `samples_ptr` of the `Pixmap` object - a long int. Hopefully, Qt can then be made to use `void* PyLong_AsVoidPtr(PyObject *pylong)` to access it!
**_If_** this would work: great! Would be very much faster.

**Comment by JorjMcKie** [comment]
Or is Qt seriously requiring a `bytearray` and not `bytes`?

**Comment by JorjMcKie** [comment]
Just confirmed (again), that PIL `Image` creation works fine using `Image.frombytes(mode, (pixmap.width, pixmap.height), pixmap.samples)`.

**Comment by JorjMcKie** [comment]
How about creating a new property, `pix.samples_mv` which would return a `memoryview` of `pm->samples`.
This would avoid making a copy. Its `len()` function returns the same value as `pix.samples`. Content can be accessed via bytes(mv[n:m]), etc.
In Qt, you could then use `bytearray(pix.samples_mv)` instead of `pix.samples`.

**Comment by JorjMcKie** [comment]
Here are screen print from the different PyQt versions.
PyQt5:
![pyqt5](https://user-images.githubusercontent.com/8290722/129717300-51819cd6-9c86-4fc5-ad34-26371ea8c4f6.jpg)
PyQt6:
![pyqt6](https://user-images.githubusercontent.com/8290722/129717335-296c5a61-c29a-44e6-b61d-afa8fe50ce7a.jpg)
So, both versions explicitely allow `bytes` objects as parameter 1.
Irritating is that PyQt6 no longer seems to support a voidptr, or at least does no longer announce it.

Thinking about your error, to me it seems to point to a complaint about a wrong memory **_alignment_** - as opposed to not being completely loaded stuff. Like as if Qt expects those bytes to start at an address which is a multiple of 2 (or 4, 8, ...), which it doesn't.
That may well be and would be specific to your OS, OpenSuse. Supporting this is the fact, that I am **_unable to reproduce the error on Windows._**

**Comment by JorjMcKie** [comment]
I thought I had written this already.
I experimented with `pixmap.samples_ptr`, which provides a Python void pointer to the pixels area, instead of copying it:
It works for PyQt5 and PyQt6 and may be 800 to 1000 times or so faster than using `pixmap.samples`:
```python
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.26.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import fitz
In [2]: from PyQt5 import QtGui
In [3]: pix = fitz.Pixmap("Fuerteventura-2007 139.jpg") # a 2 MB image
In [4]: %timeit img=QtGui.QImage(pix.samples_ptr, pix.width, pix.height, QtGui.QImage.Format_RGB888)
3.45 µs ± 17.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [5]: %timeit img=QtGui.QImage(pix.samples, pix.width, pix.height, QtGui.QImage.Format_RGB888)
3.57 ms ± 38.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

```python
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from PyQt6 import QtGui
In [2]: import fitz
In [3]: pix = fitz.Pixmap("Fuerteventura-2007 139.jpg") # a 2 MB image
In [6]: %timeit img=QtGui.QImage(pix.samples_ptr, pix.width, pix.height, QtGui.QImage.Format.Format_BGR888)
5.33 µs ± 33.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [7]: %timeit img=QtGui.QImage(pix.samples, pix.width, pix.height, QtGui.QImage.Format.Format_BGR888)
4.08 ms ± 76.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by PowerSnail** [comment]
That's very thorough investigation!

> Is this happening since Qt version 6?

Yes, it started when I migrated to Qt6. Sorry for forgetting to mention that.

> What happens if you use bytearray(pixmap.samples) instead?

Both `bytes` and `bytearray` works if used as a construtor here.

```python
from PyQt6 import QtGui
import fitz

doc = fitz.Document()
page = doc.new_page()
pixmap = page.get_pixmap()

samples = bytearray(pixmap.samples)  # works
# samples = bytes(pixmap.samples)  # This also works

image = QtGui.QImage(samples, pixmap.width, pixmap.height, QtGui.QImage.Format.Format_RGB888)
print("image[0, 0]: {}".format(str(image.pixelColor(0, 0).name())))
```

In fact, as I experiment more, simply assign `pixmap.samples` to a variable seems to work around this thing.

```python
from PyQt6 import QtGui
import fitz

doc = fitz.Document()
page = doc.new_page()
pixmap = page.get_pixmap()

samples = pixmap.samples

image = QtGui.QImage(samples, pixmap.width, pixmap.height, QtGui.QImage.Format.Format_RGB888)
print("image[0, 0]: {}".format(str(image.pixelColor(0, 0).name())))
```

> Supporting this is the fact, that I am unable to reproduce the error on Windows.

Hmm, actually I am able to reproduce this on Windows (use `pixmap.samples` directly in `QImage(...)`; don't assign it to a variable). I notice that on Windows I don't see an error message. But the crash must have happened as nothing is printed in the console despite the `print` statement.

And the above workaround works on Windows, too. Just assign it to a variable is enough. 

My Windows environment:

- OS: 10.0.19043
- Python: 3.9.6
- PyMuPDF: 1.18.16
- PyQt Version (for both win and linux): 6.1.1

> I experimented with pixmap.samples_ptr, which provides a Python void pointer to the pixels area, instead of copying it:
It works for PyQt5 and PyQt6 and may be 800 to 1000 times or so faster than using pixmap.samples:

That sounds *really* neat.

**Comment by JorjMcKie** [comment]
> "... assign pixmap.samples to a variable seems to work around this thing"

A key observation! This means, that Python keeps this bytes object alive - as long as that variable lives. When using the property directly in QImage: there, these bytes are garbage collected some time soon after they have been accessed. And this may mean: even while QImage function still is underway doing stuff.
Obviously QImage makes no copy of this area for its own purpose, but relies on its continued existence. **_That_** has probably changed for PyQt6. And because of that, the Qt-internal pointer to those bytes soon enough point to Nirwana ... causing that error.

I might of course increase the C reference count of the `pixmap.samples` bytes object - so freeing wouldn't happen like that. But that will have collateral effects like increased memory consumption for all other users.
I therefore suggest to accept your "circumvention" as the state-of-the-art solution for the PyQt6 case.
An official recommendation like: "Either do this or use the (future) `pixmap.samples_ptr` instead."

**Comment by PowerSnail** [comment]
> these bytes are garbage collected some time soon after they have been accessed

I would've thought that being a field of an object is enough to keep it not GCed. Is it because `pixmap.samples` is not actually a member variable, but a property?

> I therefore suggest to accept your "circumvention" as the state-of-the-art solution for the PyQt6 case.

Yeah, I'll use the workaround for now (luckily it's a simple workaround). And totally looking forward to the release of `samples_ptr`!

Thanks!

**Comment by JorjMcKie** [comment]
> is not actually a member variable, but a property?

Exactly, it is up to be garbage collected as soon as the reference count reaches zero. A **_member_** variable would live as long as the object itself - but in our case that would also increase its size dramatically.
Would be especially unfortunate when considering that that same area actually also exists in C memory inside MuPDF ...
Good to see, that PyQt can use that Python pointer feature. So the QImage will be in no danger as long as the pixmap object lives.

**Comment by PowerSnail** [comment]
That answers everything. Thanks!
