### ISSUE TITLE
fitz - converting to image produces blank or incomplete output

### ISSUE THREAD

**Issue by Raxidi** [pymupdf/PyMuPDF#1317]
I am trying to save each page of the pdf file as an individual image. Attached file produces almost blank output.

## To Reproduce (mandatory)
dpi_matrix = fitz.Matrix(200 / 72, 200 / 72)
file_path='.\test.pdf'
with fitz.open(file_path) as pdf_file:
            for i in range(len(pdf_file)):
                page = pdf_file.loadPage(i)
                page_pixel = page.getPixmap(matrix = dpi_matrix, annots=False)
                page_pixel.save(f'{i}.jpg')

## Expected behavior (optional)
Image created should have been replica of what is looks in any pdf viewer.

## Screenshots (optional)
Please refer attached files for input and generated output.

## Your configuration (mandatory)
 - Windows 10 64 bit
 - Python 3.8.6 64 bit
 - PyMuPDF version 1.18.19 installed using pip 

output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)`
PyMuPDF 1.18.19: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-09-16 16:45:29.
Built for Python 3.8 on win32 (64-bit).

[test.pdf](https://github.com/pymupdf/PyMuPDF/files/7321778/test.pdf)
![1](https://user-images.githubusercontent.com/42836800/136777743-cc563073-4314-4771-835e-6527c19195c4.jpg)

@JorjMcKie Firstly, thank you for this awesome tool. I appreciate your great effort in creating this.
Please help me if my requirement is achievable or is there any other way I can create images without this issue. I think this issue might be due to type3 fonts in the file(I am not the creator of this PDF).
Thanks!

**Comment by JorjMcKie** [comment]
Thank you for your compliments ... and for submitting this issue.
This indeed is a new (upstream) issue, which - fortunately - is being fixed in MuPDF in the coming v1.19.0: the following script does the expected. Please note: output format **_JPEG is not supported for output_** by MuPDF, use PNG:
```python
import fitz

dpi = 200
dpi_matrix = fitz.Matrix(dpi / 72, dpi / 72)
file_path = "test.pdf"
with fitz.open(file_path) as pdf_file:
    for page in pdf_file:
        page_pixel = page.get_pixmap(matrix=dpi_matrix, annots=False)
        page_pixel.set_dpi(dpi, dpi)
        page_pixel.save(f"{page.number}.png")
```
You have the following options:
* I send you a preliminary 1.19.0 wheel
* you download MuPDF from [here](https://mupdf.com/downloads/), either `mupdf-1.19.0-windows.zip` or `mupdf-1.19.0-windows-tesseract.zip`, and then execute the following equivalent batch command: `mutool draw -r 200 -o %d.png test.pdf`. This will produce a 200 dpi page images named 1.png, 2.png, ...
