### ISSUE TITLE
How to extract JavaScript code from PDF file?

### ISSUE THREAD

**Issue by qqizai** [pymupdf/PyMuPDF#1745]
**Describe the solution you'd like**
Excuse me, I looked through the source code and saw that addjs function, but I haven't found how to extract JavaScript code from PDF yet. Does the current library support extracting JavaScript code? If yes, how to use it? Looking forward to your reply, thank you.

**Comment by JorjMcKie** [comment]
What type of JS do you refer to? There are several places where a PDF might have them.
For form fields, there is extensive support to add or etract JavaScript - see there.
Otherwise, for general JavaScript actions you can use PyMuPDF's low-level interface and iterate through the PDF's objects:
```python
for xref in range(1, doc.xref_length):
    js = doc.xref_get_key(xref, "JS")  # either a JS action or null
    if js != ("null", "null"):  # not the null object
        # js[0] is the object type. If
        # js[0] == "string", then js[1] is the JavaScript source and you are done
        # js[0] == "xref", then js[1] looks like "nnn 0 R" with another xref that you must read
```
JavaScripts may be specified as a string or a stream (both in PDF terminology). If you are being given an xref above, you must therefore check whether it is a stream: `doc.xref_is_stream(js_xref)`, and if so, your JS code can be extracted via `doc.xref_stream(js_xref)`. Otherwise the source code can be extracted via `doc.xref_object(js_xref)`.

**Comment by JorjMcKie** [comment]
Any comments on this?
Please consider closing the issue.
