### ISSUE TITLE
page.get_drawings(): closePath is always False

### ISSUE THREAD

**Issue by Luux** [pymupdf/PyMuPDF#1751]
When analyzing the drawings using `page.get_drawings()`, the `closePath` attribute is always set to False in the dict. Also, there is no additional line introduced from the last point to the first, so this information is just missing.

Here are two simple shapes, one with closePath set to True and one without:

![output](https://user-images.githubusercontent.com/15156652/173379745-2a39f199-9aff-458e-a7a1-2e2e5cd915bd.png)
![output2](https://user-images.githubusercontent.com/15156652/173379749-7d6f919f-d23d-4e0c-afc1-907451c4de52.png)

Both dicts returned by `page.get_drawings` are identical:

```
[{'items': [('l', Point(10.0, 10.0), Point(10.0, 50.0)),
   ('l', Point(10.0, 50.0), Point(100.0, 100.0))],
  'type': 's',
  'stroke_opacity': 1.0,
  'color': (0.0, 0.0, 0.0),
  'width': 5.0,
  'lineCap': (0, 0, 0),
  'lineJoin': 0.0,
  'closePath': False,
  'dashes': '[] 0',
  'rect': Rect(10.0, 10.0, 100.0, 100.0),
  'seqno': 0,
  'fill': None,
  'fill_opacity': 1,
  'even_odd': True}]
```
```
[{'items': [('l', Point(10.0, 10.0), Point(10.0, 50.0)),
   ('l', Point(10.0, 50.0), Point(100.0, 100.0))],
  'closePath': False,
  'type': 's',
  'stroke_opacity': 1.0,
  'color': (0.0, 0.0, 0.0),
  'width': 5.0,
  'lineCap': (0, 0, 0),
  'lineJoin': 0.0,
  'dashes': '[] 0',
  'rect': Rect(10.0, 10.0, 100.0, 100.0),
  'seqno': 0,
  'fill': None,
  'fill_opacity': 1,
  'even_odd': True}]
```

## To Reproduce (mandatory)
```
import fitz

doc = fitz.open()
page = doc.new_page()
shape = page.new_shape()

shape.draw_line((10, 10), (10, 50))
shape.draw_line((10, 50), (100, 100))
shape.finish(closePath=False, color=(0,0,0), width=5)
shape.commit()
drawings = list(page.get_drawings())

page2 = doc.new_page()
shape2 = page2.new_shape()

shape2.draw_line((10, 10), (10, 50))
shape2.draw_line((10, 50), (100, 100))
shape2.finish(closePath=True, color=(0,0,0), width=5)
shape2.commit()
drawings2 = list(page2.get_drawings())

# BUG:
assert drawings == drawings2

```

## Expected behavior (optional)
`closePath` should return the correct value.

## Your configuration (mandatory)
 - (K)Ubuntu 20.04.4 LTS
 - Python: 3.9
 - PyMuPDF version: 1.19.6

**Comment by Luux** [comment]
Note that the same behaviour occurs when using `get_cdrawings()`

**Comment by julian-smith-artifex-com** [comment]
@JorjMcKie would you be able to take a look at this commit, which attempts to address this bug?

https://github.com/pymupdf/PyMuPDF/commit/beb5993cbaa46c10

It seems to work ok - all tests pass, except for `PyMuPDF/tests/test_drawings.py:test_drawings1()`, because we are now setting `closePath` to `True` where we didn't previously.

If the fix is correct, we'd need to update `PyMuPDF/tests/resources/symbols.txt` with the new output.

**Comment by JorjMcKie** [comment]
@julian-smith-artifex-com I have reviewed the code and tested several examples.
I think we are good.

**Comment by JorjMcKie** [comment]
Ok – I will and provide feedback.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Julian ***@***.***>
Gesendet: Donnerstag, 23. Juni 2022 14:25
An: ***@***.***>
Cc: Jorj X. ***@***.***>; ***@***.***>
Betreff: Re: [pymupdf/PyMuPDF] page.get_drawings(): closePath is always False (Issue #1751)


@JorjMcKie<https://github.com/JorjMcKie> would you be able to take a look at this commit, which attempts to address this bug?

beb5993cbaa46c10<https://github.com/pymupdf/PyMuPDF/commit/beb5993cbaa46c10>

It seems to work ok - all tests pass, except for PyMuPDF/tests/test_drawings.py:test_drawings1(), because we are now setting closePath to True where we didn't previously.

If the fix is correct, we'd need to update PyMuPDF/tests/resources/symbols.txt with the new output.
