### ISSUE TITLE
Provide slim source distribution on PyPI

### ISSUE THREAD

**Issue by stefan6419846** [pymupdf/PyMuPDF#1790]
**Is your feature request related to a problem? Please describe.**

With the latest changes, PyPI ships a source distribution which is 90.4 MB in size as it includes the whole MuPDF source. If building the package against the system-wide MuPDF installation (or some custom one), this introduces some unnecessary overhead.

**Describe the solution you'd like**

Besides the current *sdist* file including the whole MuPDF source as well, an additional slim source distribution without the MuPDF source code is shipped without the MuPDF source being included (the source distribution of version 1.19.6 had 2.3 MB only).

**Describe alternatives you've considered**

Use the source distributions automatically generated by GitHub for each release/tag.

**Comment by julian-smith-artifex-com** [comment]
Making a separate sdist without mupdf on pypi.org, would complicate the release process, require additional documentation, and would probably cause confusion.

I think the suggestion to use github's source releases is a better approach:

* These are generated automatically already so no work is required.

* For the 1.20.1 release at https://github.com/pymupdf/PyMuPDF/releases/tag/1.20.1, the `.zip` file is 7.7MB. That's rather more than 2.3MB because it includes the documentation and some other files, but significantly less than 90MB and easily downloadable these days.

So i think this is the solution we should use.

**Comment by julian-smith-artifex-com** [comment]
Good idea about documenting this.

In my tree i've added some information to the installation page about building with github's source releases.
