### ISSUE TITLE
No Python 3.11 wheels + built error

### ISSUE THREAD

**Issue by yan-hic** [pymupdf/PyMuPDF#1993]
Cannot be installed on Python 3.11 Windows or Ubuntu through `PyPI`.

Wheels are not available and building fails for both Win64 and Linux.

```
x86_64-linux-gnu-gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imupdf-1.20.3-source
/include -Imupdf-1.20.3-source/include/mupdf -Imupdf-1.20.3-source/thirdparty/freetype/include -I/usr/include/python3.11 -I/usr/local/include/python3.11 -c fitz/fitz_wrap.c -o build/temp.linux-x86_64-3.11/fitz/fitz_wrap.o
      fitz/fitz_wrap.c:154:11: fatal error: Python.h: No such file or directory
        154 | # include <Python.h>
            |           ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

**Comment by julian-smith-artifex-com** [comment]
The next release, 1.21.0, may have wheels for python-3.11, assuming Github Action's cibuildwheel infrastructure supports it. But we have not yet tested this.

The build error you're seeing is because the python-3.11 development libraries are not installed.

You could try installing these development libraries (For example on Debian something like `apt install python3-dev`, assuming default python is 3.11). You will also need SWIG (see https://pymupdf.readthedocs.io/en/latest/installation.html for details).

Please report back on how you get on.

**Comment by svladimirs** [comment]
pip install PyMuPDF
Collecting PyMuPDF
  Using cached PyMuPDF-1.20.2.tar.gz (90.4 MB)
  Preparing metadata (setup.py) ... done
Installing collected packages: PyMuPDF
  DEPRECATION: PyMuPDF is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for PyMuPDF ... error
  error: subprocess-exited-with-error

  × Running setup.py install for PyMuPDF did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
etc.

pip install PyMuPDF --use-pep517
Collecting PyMuPDF
  Using cached PyMuPDF-1.20.2.tar.gz (90.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: PyMuPDF
  Building wheel for PyMuPDF (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for PyMuPDF (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [78 lines of output]
etc.

What about "development libraries" for win64? swigwin-4.1.0 already unzip and set in the path.

**Comment by Aaryashree03** [comment]
Collecting webrtcvad
  Using cached webrtcvad-2.0.10.tar.gz (66 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: webrtcvad
  Building wheel for webrtcvad (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      copying webrtcvad.py -> build\lib.win-amd64-cpython-39
      running build_ext
      building '_webrtcvad' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for webrtcvad
  Running setup.py clean for webrtcvad
Failed to build webrtcvad
Installing collected packages: webrtcvad
  Running setup.py install for webrtcvad ... error
  error: subprocess-exited-with-error

  × Running setup.py install for webrtcvad did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running install
      C:\Users\DELL\Documents\deepspeech\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      copying webrtcvad.py -> build\lib.win-amd64-cpython-39
      running build_ext
      building '_webrtcvad' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> webrtcvad

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

How to solve these.

**Comment by sworasky** [comment]
Collecting webrtcvad
  Using cached webrtcvad-2.0.10.tar.gz (66 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: webrtcvad
  Building wheel for webrtcvad (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      copying webrtcvad.py -> build\lib.win-amd64-cpython-39
      running build_ext
      building '_webrtcvad' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for webrtcvad
  Running setup.py clean for webrtcvad
Failed to build webrtcvad
Installing collected packages: webrtcvad
  Running setup.py install for webrtcvad ... error
  error: subprocess-exited-with-error

  × Running setup.py install for webrtcvad did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running install
      C:\Users\DELL\Documents\deepspeech\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      copying webrtcvad.py -> build\lib.win-amd64-cpython-39
      running build_ext
      building '_webrtcvad' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> webrtcvad

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure. 
Help me solving these. have been tying all day long

**Comment by julian-smith-artifex-com** [comment]
Thanks for trying.

Please give the complete output from `pip install PyMuPDF` - we need to see what the actual error is, in order to make progress here.

**Comment by svladimirs** [comment]
I updated the post above. I think the problem is that in 3.11 there were changes related to the TOML library.
PEP 680 -- tomllib: Support for Parsing TOML in the Standard Library
bpo-40059: PEP 680, the tomllib module. Adds support for parsing TOML.

**Comment by julian-smith-artifex-com** [comment]
Thanks for the update.

I don't think it's a TOML issue.

`setup.py` is trying to build PyMuPDF, but it cannot find Visual Studio's `devenv.com` command. It defaults to looking for a match in `C:/Program Files (x86)/Microsoft Visual Studio/2019/*/Common7/IDE/devenv.com`.

If you already have Microsoft Visual Studio installed, you'll need to set environmental variable `PYMUPDF_SETUP_DEVENV` to the actual location of `devenv.com`.

Otherwise, you'll need to install Microsoft Visual Studio.

[Incidentally your webrtcvad build failure looks to be the same problem.]

**Comment by yan-hic** [comment]
Thanks @julian-smith-artifex-com I have reverted back to 3.10 and will wait patiently for the wheels.

**Comment by julian-smith-artifex-com** [comment]
BTW i tried a github/cibuildwheel Linux build with python-3.11 earlier and it worked fine, so it's very likely that the next release will come with wheels for python-3.11.

**Comment by leiserfg** [comment]
Any idea of when is the release coming? Or a any chance of getting the wheel for py3.11 for the current one  if the release will take long?
