### ISSUE TITLE
Mismatch between extractions by words and block or dict

### ISSUE THREAD

**Issue by blenzi** [pymupdf/PyMuPDF#2098]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
The extraction by words does not give the same block number as the extractions by block or dict

## To Reproduce (mandatory)

Download the pdf:

```shell
wget -O test.pdf https://osmose.numerique.gouv.fr/front/publicLink/publicDownload.jsp?id=6c1e3441-f0ad-45f2-a17e-37431f4df8e71c3f79fe-9f65-4d44-95a7-d49a3bd832f8
```

Run the extraction
```python
>>> import fitz
>>> doc = fitz.open("test.pdf")
>>> page = doc.load_page(31)
>>> max(page.get_text("words"), key=lambda x: x[-3:])  # maximum block is 14
(395.0631408691406, 330.32489013671875, 431.13079833984375, 345.05224609375, 'aérosols', 14, 0, 2)
>>> max(page.get_text("blocks"), key=lambda x: x[-2])  # maximum block is 15
(346.7300109863281, 330.32489013671875, 433.8500061035156, 345.05224609375, 'liquides et aérosols \n', 15, 0)
>>> max(page.get_text("dict")["blocks"], key=lambda x: x["number"])  # maximum block is 15
{'number': 15, 'type': 0, 'bbox': (346.7300109863281, 330.32489013671875, 433.8500061035156, 345.05224609375), 'lines': [{'spans': [{'size': 11.039999961853027, 'flags': 4, 'font': 'TimesNewRomanPSMT', 'color': 0, 'ascender': 1.0529999732971191, 'descender': -0.2809999883174896, 'text': 'liquides et aérosols ', 'origin': (346.7300109863281, 341.95001220703125), 'bbox': (346.7300109863281, 330.32489013671875, 433.8500061035156, 345.05224609375)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (346.7300109863281, 330.32489013671875, 433.8500061035156, 345.05224609375)}]}
```

I bumped into this issue because the dict extraction does not provide the words with their bounding boxes, while the extraction by words does not give information about the characters (font, size, color, ...). 

In general, having a the information about the characters in the extraction by word would be nice. And maybe have a level `word` between `span` and `character` in the dict.  To avoid breaking the structure, it could be another item in `span`, with the bbox at least (the other info can be recovered from the span in case).

## Your configuration (mandatory)
 - Operating system, potentially version and bitness: MacOsX 
 - Python version, bitness: 3.11.0
 - PyMuPDF version, installation method (**wheel** or **generated** from source): 1.21.0

**Comment by JorjMcKie** [comment]
Thanks for submitting this. I understand your confusion, but it is no bug:
If you let default the flags parameter in `page.get_text("blocks")` it will also extract image blocks.
Whereas `page.get_text("words")` will always only look at text blocks, and thus ignore image blocks: they will not be included in the underlying `TextPage` (you will remember: an object of this class will always be created for text extractions and searches).

On the quoted page there is an image, therefore "blocks" extraction has a block count 1 larger than than "words" extraction.

Please also remember that both extraction methods, "words" and "blocks", have once been developed for best speed, based on request of an early user. Therefore they sacrifice some comfort for this purpose (e.g. tuples instead of dictionaries). The rewarding result of this approach text extraction options "text, "blocks", "words" have the same performance in all common sense situations.

The list `page.get_text("blocks", flags=fitz.TEXTFLAGS_TEXT)` has the same block count as you see with using the "words" extraction.

As per your other idea ("words" with font details):
Also once though about it ... and soon dropped it again. The gag of "words" is feeding back strings containing no spaces. So it will return **_one_** word for <code>one<i><b>word</b></i></code> ... which is not achievable in circumstances reporting font properties: "dict"/"rawdict" will separate this in two spans of course.
