### ISSUE TITLE
Reading page.get_images() returns all images in a document

### ISSUE THREAD

**Issue by saruvora** [pymupdf/PyMuPDF#2142]
## Describe the bug (mandatory)
I am trying to read a two page pdf with 2 images on each page. Then I tried reading images on each page but I get all the images in the document instead of each page

## To Reproduce (mandatory)
```
import fitz

def main():
    doc = fitz.Document("./google.pdf")
    print("Number of pages: ", len(doc))

    for page in doc.pages(0, len(doc), 1):
        images = page.get_images()
        print("Number of images: ", len(images))

if __name__ == "__main__":
    main()
```

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/20369021/208671010-44158cbd-f093-43c6-bd94-1db27f8b0c06.png)

## Your configuration (mandatory)
 -Ubuntu 22.04
 - 3.10
 - pip install pymupdf

**Comment by JorjMcKie** [comment]
This is no bug, but goes back to a decision of the PDF creator:
Instead of specifying a separate `/Resources` object (where fonts and images must be referenced) for each page, one can can define a central one in the PDF, which then contains all those references for all pages in one place.
Saves coding effort and some space in the PDF.

If you need a list of stuff specific for each page, execute `page.clean_contents()` before looking for images / fonts / ... of the page.

This methods walks through the appearance source of the page and synchronizes its findings with the page object definition.
As part of that process, also a lot of other things are cleaned up - among them renumbering the document's XREFs and the referencenames for images and fonts.

**Comment by saruvora** [comment]
Ah great this works like a charm thank you
