### ISSUE TITLE
RTL (Arabic) ligatures problem when extracting text from PDF

### ISSUE THREAD

**Issue by naourass** [pymupdf/PyMuPDF#2199]
When you extract Arabic text, the words are returned in backward order which is a normal behavior for RTL languages, and you need use bidi algorithm to be able to display it correctly across UI/GUIs.

The problem is when you have ligatures chars that are composed of two chars, these ligatures chars are not reversed which makes the extracted text inaccurate (whether you set TEXT_PRESERVE_LIGATURES flag to on or off) .

_**Here's an example :**_

Let's say we have a font with a ligature glyph "لا" that maps to "uni0644 uni0627". The pdf is rendered like this:

![image](https://user-images.githubusercontent.com/4897498/215363967-63216b61-25c4-426d-a601-fda872f51d9f.png)

When you extract the pdf text using `Document[1].get_text()` you get this:
كارتــــــشلاا

Notice how all chars are reversed except "لا".

And here's the final result after applying bidi algorithm:
االشــــــتراك

Is this a bug, a missing feature or an intended behavior? Is there any workaround to fix it?

**_Sample PDF:_**
https://drive.google.com/file/d/1M4159cnhdb2vgtAyPh6mE__m-WlIDMyv

**Comment by JorjMcKie** [comment]
Please let me have an example PDF for reproducing the issue, thanks.

**Comment by JorjMcKie** [comment]
Sorry for the tardy reaction! After a while simply escaped my attention.
The SO answer goes in the right direction. While PyMuPDF is capable of decomposing the standard ligatures `fi` etc. in the Latin alphabet by setting an appropriate text extraction flag, this is not supported for other, arbitrary alphabets.

So I am sorry to say, that there is no support for this.

**Comment by JorjMcKie** [comment]
You could certainly try this - there is no risk associated with modifying your local `table.py`.

But as I wrote earlier: this of course leaves other script systems out of regard. Among them are even more complex ones like Devanagari.
To properly support all of them, we would actually need to call a text shaping component like HarfBuzz when it comes to properly reconstructing cell content from single unicodes.

**Comment by khaled-hammoud** [comment]
Just for giving you an idea or for those who can not read Arabic in order to understand what I mean.
Assume that English is written from right to left like Arabic or Hebrew, then an english sentence like `"Hello World"` would be extracted with fitz as` "dlroW olleH"`, until now no Problem.
so I can reverse it like this to be in right order:
```
extracted_from_fitz = "dlroW olleH"
#after correction
extracted_from_fitz_rev = extracted_from_fitz[::-1] #Output: Hello World
```

The problem come when ligatures come into play, there is a famous ligature combined of `"f"` + `"i"` as `"ﬁ"`.
Take same assuming above (English as rtl) but now the string to be extracted is `"Hello World ﬁ"`, here `"ﬁ"` is a ligature, so no two successive letters f and i, it should be extracted with fitz as `"ﬁ dlroW olleH"`.
here if I reverse the string to correct it then I become `"Hello World if"` but that is not right, it should be `"Hello World fi"`.

That is my case and explaining for extracted text in Arabic language.
Ok, I edited the file `tables.py` on my pc in order to add more ligatures to yours, following your logic:

```
LIGATURES = {
    "ﬀ": "ff",
    "ﬃ": "ffi",
    "ﬄ": "ffl",
    "ﬁ": "fi",
    "ﬂ": "fl",
    "ﬆ": "st",
    "ﬅ": "st",
    
    
    #ADDED BY ME:
	#Most common ligatures in Arabic (rtl language)
    #ligature: its decomposition
	
    "﷼": "ريال", #ر (U+0631) + ی (U+06CC) + ا (U+0627) + ل (U+0644)
    "ﷲ": "الله", #ا (U+0627) + ل (U+0644) + ل (U+0644) + ه (U+0647)
    "ﻻ": "لا", #ل (U+0644) + ا (U+0627)
    "ﻹ": "لإ", #ل (U+0644) + ا (U+0627) + ◌ٕ (U+0655)
    "ﻷ": "لأ", #ل (U+0644) + ا (U+0627) + ◌ٔ (U+0654)
    "ﻵ": "لآ", #ل (U+0644) + ا (U+0627) + ◌ٓ (U+0653)
}
```

Following documentation:

> TEXT_PRESERVE_LIGATURES
> 1 – If set, ligatures are passed through to the application in their original form. Otherwise ligatures are expanded into their constituent parts, e.g. the ligature “ffi” is expanded into three **eparate** characters f, f and i. Default is “on” in PyMuPDF. MuPDF supports the following 7 ligatures: “ff”, “fi”, “fl”, “ffi”, “ffl”, , “ft”, “st”.


Do you have some ideas or suggestions to get rid of that problem?
Extracted words where Arabic ligatures are involved are not decomposed even after editing and adding them to LIGATURES in `table.py `

My Code:

```
import fitz

with fitz.open("C:\\Users\\admin\\Desktop\\Antoine Gabrial.pdf") as doc:
    for page in doc:
        for text_block in page.get_text_blocks():
            text = text_block[4]
            print(text) #Output: ينايرس ريالبك ناوطنا
            corrected_txt = text[::-1]
            print(corrected_txt) #Output: انطوان كبلاير سرياني


```

The word standing in pdf is right displayed, it is "Antoine Gab**rial** Siriani", fitz extracts it as "inairiS **rial**baG eniotnA" like outputing the variable `print(text)` so if I correct it with  `text[::-1]` it becomes `"Antoine Gab**lair** Siriani"` so wrong, it should be corrected as "Antoine Gab**rial** Siriani", the problem here is the existance of a ligature called "`rial"` (U+FDFC) composed of four letters like this:
Decomposition:  ر (U+0631) - ی (U+06CC) - ا (U+0627) - ل (U+0644) , see : https://www.compart.com/en/unicode/U+FDFC

It is not decomposed in fitz, and of course "Gabrial" has with "rial (Saudi Currency)" nothing to do.

My english is not so perfect but I hope you understand my problem (I assume that you speak no Arabic), therefore a long explaining.

Thanks for you.

**Comment by JorjMcKie** [comment]
@khaled-hammoud - I do understand your problem. But as I wrote in some earlier post (somewhere), there is no way we can extend ligature support beyond the Latin Unicode range in the foreseeable future.

**Comment by khaled-hammoud** [comment]
I am glad that you are understanding me but I added that comment because I thought, modiying table.py by adding some additional ligarures would resolve the problem.
My approach was to understand your logic of your default ligatures therefore I tried it.
Anyway, thank you so much and my regards from Germany.
