### ISSUE TITLE
clean raises RuntimeError: BI operator can only show ImageMask, Gray, RGB, or CMYK images

### ISSUE THREAD

**Issue by TheCapybaraClub** [pymupdf/PyMuPDF#2252]
## Describe the bug (mandatory)
When using doc.tobytes with option clean=True runtime error is raised: 
`RuntimeError: BI operator can only show ImageMask, Gray, RGB, or CMYK images`

Trace:
```---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [9], line 5
      2 tmpDoc = fitz.open()
      4 tmpDoc.insert_pdf(doc, from_page=pn, to_page=pn, links=False, annots=False)
----> 5 tmpDoc_bytes = tmpDoc.tobytes(garbage=4, clean=True, deflate=True, deflate_images=True, deflate_fonts=True)
      7 with open(f'./page_{pn}.pdf', 'wb') as fh:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\fitz\fitz.py:4557, in Document.write(self, garbage, clean, deflate, deflate_images, deflate_fonts, incremental, ascii, expand, linear, no_new_id, appearance, pretty, encryption, permissions, owner_pw, user_pw)
   4555 from io import BytesIO
   4556 bio = BytesIO()
-> 4557 self.save(bio, garbage=garbage, clean=clean,
   4558 no_new_id=no_new_id, appearance=appearance,
   4559 deflate=deflate, deflate_images=deflate_images, deflate_fonts=deflate_fonts,
   4560 incremental=incremental, ascii=ascii, expand=expand, linear=linear,
   4561 pretty=pretty, encryption=encryption, permissions=permissions,
   4562 owner_pw=owner_pw, user_pw=user_pw)
   4563 return bio.getvalue()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\fitz\fitz.py:4547, in Document.save(self, filename, garbage, clean, deflate, deflate_images, deflate_fonts, incremental, ascii, expand, linear, no_new_id, appearance, pretty, encryption, permissions, owner_pw, user_pw)
   4543     if self.name != filename or self.stream:
   4544         raise ValueError("incremental needs original file")
-> 4547 return _fitz.Document_save(self, filename, garbage, clean, deflate, deflate_images, deflate_fonts, incremental, ascii, expand, linear, no_new_id, appearance, pretty, encryption, permissions, owner_pw, user_pw)

RuntimeError: BI operator can only show ImageMask, Gray, RGB, or CMYK images
```

## To Reproduce (mandatory)
I'm sorry but I unable to share the PDF. I think this might be helpful for the issue though:
```# https://pymupdf.readthedocs.io/en/latest/document.html#Document.get_page_images
# (xref, smask, width, height, bpc, colorspace, alt. colorspace, name, filter, referencer)
for pn, page in enumerate(doc):
    print(f"Page: {pn+1}")
    for img in page.get_images():
        print(img)
```

```
Page: 1
(23, 0, 73, 130, 8, 'Indexed', '', 'Im1', 'FlateDecode')
(24, 0, 68, 68, 8, 'Indexed', '', 'Im2', 'FlateDecode')
(25, 0, 32, 116, 8, 'Indexed', '', 'Im3', 'FlateDecode')
(26, 0, 19, 39, 8, 'Indexed', '', 'Im4', 'FlateDecode')
(27, 0, 27, 53, 8, 'DeviceRGB', '', 'Im5', 'FlateDecode')
Page: 2
(23, 0, 73, 130, 8, 'Indexed', '', 'Im1', 'FlateDecode')
(24, 0, 68, 68, 8, 'Indexed', '', 'Im2', 'FlateDecode')
(25, 0, 32, 116, 8, 'Indexed', '', 'Im3', 'FlateDecode')
(26, 0, 19, 39, 8, 'Indexed', '', 'Im4', 'FlateDecode')
(27, 0, 27, 53, 8, 'DeviceRGB', '', 'Im5', 'FlateDecode')
(3, 0, 19, 38, 8, 'Indexed', '', 'Im6', 'FlateDecode')
Page: 3
(23, 0, 73, 130, 8, 'Indexed', '', 'Im1', 'FlateDecode')
(24, 0, 68, 68, 8, 'Indexed', '', 'Im2', 'FlateDecode')
(25, 0, 32, 116, 8, 'Indexed', '', 'Im3', 'FlateDecode')
(26, 0, 19, 39, 8, 'Indexed', '', 'Im4', 'FlateDecode')
(27, 0, 27, 53, 8, 'DeviceRGB', '', 'Im5', 'FlateDecode')
(3, 0, 19, 38, 8, 'Indexed', '', 'Im6', 'FlateDecode')
(7, 0, 24, 87, 8, 'Indexed', '', 'Im7', 'FlateDecode')
Page: 4
(23, 0, 73, 130, 8, 'Indexed', '', 'Im1', 'FlateDecode')
(24, 0, 68, 68, 8, 'Indexed', '', 'Im2', 'FlateDecode')
(25, 0, 32, 116, 8, 'Indexed', '', 'Im3', 'FlateDecode')
(26, 0, 19, 39, 8, 'Indexed', '', 'Im4', 'FlateDecode')
(27, 0, 27, 53, 8, 'DeviceRGB', '', 'Im5', 'FlateDecode')
(3, 0, 19, 38, 8, 'Indexed', '', 'Im6', 'FlateDecode')
(7, 0, 24, 87, 8, 'Indexed', '', 'Im7', 'FlateDecode')
Page: 5
(23, 0, 73, 130, 8, 'Indexed', '', 'Im1', 'FlateDecode')
(24, 0, 68, 68, 8, 'Indexed', '', 'Im2', 'FlateDecode')
(25, 0, 32, 116, 8, 'Indexed', '', 'Im3', 'FlateDecode')
(26, 0, 19, 39, 8, 'Indexed', '', 'Im4', 'FlateDecode')
(27, 0, 27, 53, 8, 'DeviceRGB', '', 'Im5', 'FlateDecode')
(3, 0, 19, 38, 8, 'Indexed', '', 'Im6', 'FlateDecode')
(7, 0, 24, 87, 8, 'Indexed', '', 'Im7', 'FlateDecode')
```

## Expected behavior (optional)
- No runtime error
- Enhanced information in docs about the cleaning operation
- If a stream cannot be sanitized, warn, but not error out

## Your configuration (mandatory)
`! python -V`
Python 3.10.8

`!jupyter --version`
Selected Jupyter core packages...
IPython          : 8.5.0
ipykernel        : 6.16.0
ipywidgets       : 8.0.2
jupyter_client   : 7.4.2
jupyter_core     : 4.11.1
jupyter_server   : 1.21.0
jupyterlab       : not installed
nbclient         : 0.7.0
nbconvert        : 7.2.1
nbformat         : 5.7.0
notebook         : 6.5.1
qtconsole        : 5.3.2
traitlets        : 5.4.0

`print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)`
3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] 
 win32 
 
PyMuPDF 1.21.0: Python bindings for the MuPDF 1.21.0 library.
Version date: 2022-11-08 00:00:01.
Built for Python 3.10 on win32 (64-bit).

## Additional context (optional)
Might be related, but I was unable to find this specific error referenced
[685](https://github.com/pymupdf/PyMuPDF/issues/685)

**Comment by JorjMcKie** [comment]
Your PDF contains illegal specifications inside one of the pages' appearance sources (i.e. `/Contents` objects): `BI` refers to "begin image".
Images embedded like this ("inline images") are only known to the respective page, and not all image types are allowed - this is a PDF restriction, not MuPDF's.
If a page clean is requested, MuPDF runs through all the `/Contents` sources of every page, cleans the sysntax, combines multiple such objects into one, synchronizes references to PDF resources with the commands actually present, etc, etc.
So if unrecoverable errors are found in any `/Contents` object, there is no way but raising an exception, is there.
An obvious immediate way to circumvent this issue is **_not_** specifying "clean". Then MuPDF will not look at any mess that may exist in contents objects.

Another question is whether MuPDF might be instructed to be more generous and skip cleaning for problem pages.
However, as long as you do not provide a reproducer file, we cannot deal with this aspect.
So for the time being, your only option is to clean every page seperately via `page.clean_contents()` (wrapped in a try-except clause) and **_do not specify clean_** in your `save`/`tobytes` method.

```python
for page in doc:
    try:
        page.clean_contents()
    except RuntimeError:
        print(f"Cleaning failed for page {page.number}")
doc.tobytes(clean=False,...)
```
Please consider making a sub-PDF with the problem page only (i.e. delete all other pages), save with garbage option 3. Maybe you are lucky and this page happens to contains only data that can be shared.

Going to close this now. Please reopen if you are able to provide an example PDF with this problem.
