### ISSUE TITLE
Some rectangles rectangles no longer detected

### ISSUE THREAD

**Issue by indrebo** [pymupdf/PyMuPDF#2258]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I have a script that needs to detect rectangles in a pdf and color the found rectangle.
In some cases the rectangles consist of 4 individual lines, so I have made a seperate section for that,
in other cases the rectangle is a seperate element, so I have another section for that.

The code works fine when I run version 1.20.0, but if I run 1.21.1 it does not work as intended
When running with version 1.21.1 it does not color the rectangles that are elements (found with the code: "path['items'][0][0] == 're'").
The code: "page.draw_rect" does not work for these rectangles. 
But rectangles I made out of 4 seperate lines still works

In version 1.20.0 everything works fine.

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

paths_elements = page.get_cdrawings()

for path in paths:
    if path['rect'][0] == path['rect'][2] and path['rect'][1] != path['rect'][3]: 
        vertical_lines.append(path['rect'][0:4])
    if path['rect'][1] == path['rect'][3] and path['rect'][0] != path['rect'][2]:
        horizontal_lines.append(path['rect'][0:4])
    if path['items'][0][0] == 're':
        rectangles.append(path)

_### Code to make rectangles of vertical and horizontal lines_
# this section works fine for both 1.20.0 and 1.21.1
for vertical_line in vertical_lines:
    for horizontal_line in horizontal_lines:
        if match_of_lines:
            page.draw_rect(area, color=(1,0,0), fill=(1,0,0))

# this section only works for 1.20.0 but not for version 1.21.1
for rectangle in rectangles:
    page.draw_rect(area, color=(1,0,0), fill=(1,0,0))

For problems when building or installing PyMuPDF, give the full output of the build/install command so that, for example, all pip/compiler/linker errors/warnings can be seen.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).
My code works fine for version 1.20.0 but not for version 1.21.1 
I expected it to work for 1.21.1 as well
There are no errors when using version 1.21.1, but the issue is that it does not color the rectangles while it does do it when using version 1.20.0

## Your configuration (mandatory)
PyMuPDF 1.20.0: Python bindings for the MuPDF 1.20.0 library.
Version date: 2022-05-16 00:00:01.
Built for Python 3.10 on darwin (64-bit).

 - PyMuPDF version 1.20.0 and 1.21.1,  installation method: pip install pymupdf

**Comment by JorjMcKie** [comment]
There indeed have been changes in this area.
Please be aware that line art extraction (and also text extraction) are MuPDF features that work for all document types - i.e. XPS, EPUB, MOBI, SVG, ... not only for PDF.
Each document type has its own details of encoding these vector graphics. MuPDF only returns lines and curves - no higher level shapes like rectangles, quadrilaterals, circles ...

Therefore, rectangle identification (and als quads to some extent) was built into ***Py***MuPDF **_only_**. In earlier versions, this recognition was too "optimistic" in that rectangles were identified where there were no rectangles in the original document page, IAW "false positives". In addition, we needed to also detect the ***orientation*** of a rectangle: is it drawn clockwise or anti-clockwise.
In an effort to only return rectangles, when there was a rectangle ***according to PDF specifications***, we now use the following, stricter rules:
* three consecutive, connected lines, followed by a "close path" command
* line 1 and 3 must be horizontal, line 2 must be vertical
* if line 1 is above line 3, orientation is clockwise, else anti-clockwise
* start and end points of line 1 and 3 have the same x-value

If any of the above criteria is not met, single line items are returned - no rectangle.
For example, 4 lines that **_geometrically_** do form a rectangle are **_not / no longer_** reported as one, because they **_cannot_** have been part of some original PDF instruction `"x y width height re"`.

Please provide a (small) example that demonstrates that the above rules are met, but no rectangle is returned.

**Comment by JorjMcKie** [comment]
Going to close this for now.
Please feel free to (re-) open if a said example is encountered.
