### ISSUE TITLE
test_color_count fails

### ISSUE THREAD

**Issue by mjg** [pymupdf/PyMuPDF#2347]
## Describe the bug (mandatory)
`test_color_count` fails with:
```
    def test_color_count():
        pm = fitz.Pixmap(imgfile)
>       assert pm.color_count() == 40624
E       assert 39912 == 40624
E        +  where 39912 = <bound method Pixmap.color_count of Pixmap(DeviceRGB, IRect(0, 0, 439, 501), 0)>()
E        +    where <bound method Pixmap.color_count of Pixmap(DeviceRGB, IRect(0, 0, 439, 501), 0)> = Pixmap(DeviceRGB, IRect(0, 0, 439, 501), 0).color_count
```

## To Reproduce (mandatory)
Run test suite

## Expected behavior (optional)
Test succeeds

## Your configuration (mandatory)
Test locally on Fedora 38 x86_64 and in Fedora's COPR for Fedora 36, 37, 38 rawhide various archs
Python versions 3.20 and 3.11
PyMuPDF 1.22.0
mupdf 1.21.1 (locally) and mupdf 1.22.0

## Additional context (optional)
Both Fitz (run locally, directly) and PIL agree that the color count is 39912. The test suite expects 40624, and thus the assert fails. Gimp counts 39935 colours. Does this depend on colour profile treatment on image load?

**Comment by julian-smith-artifex-com** [comment]
Are you building PyMuPDF yourself or installing directly from a wheel? If the former, could you give the exact command that you are using to build it?

The reason i ask is that when PyMuPDF's `setup.py` builds MuPDF, it overwrites MuPDF's `include/mupdf/fitz/config.h` with a PyMuPDF's `fitz/_config.h`. But if MuPDF is built with its own default `config.h`, behaviour will be subtly changed, which can cause PyMuPDF test failures.

**Comment by mjg** [comment]
I package mupdf for Fedora and help packaging PyMuPDF there, in particular to coordinate system mupdf updates with PyMuPDF rebuilds (using the system mupdf, more specifically the static lib in mupdf-devel).

But as far as `test_colour_count` is concerned: If I let PIL count the colours in the test image, or if I let PyMuPDF load the image and let python count the unique 3-tuples I always get 39912. So why would the test suite expect a different count?  Neither PIL nor the the actual number can depend on specifics of the PyMuPDF build.

So, first I'm wondering where the "expected" number in the test comes from. Second, why it differs from counting by non-PyMuPDF means. Incidentally, "my" PyMuPDF counts 39912, too. Does yours count 40624? Could this depend on jpeg library versions?

BTW: We currently "disable" tests on Fedora since someone pushing an updated noticed problems on a specific architecture and simply quelled the tests. That is we still run the tests during regular builds and I look at the results but we do not block on them any more.

**Comment by julian-smith-artifex-com** [comment]
The "expected" number just comes from what PyMuPDF calculates - the test is a regression test, not a check for a match to a separately-calculated number.

I've just checked and it looks like PyMuPDF's overwrite of MuPDF's `config.h` does _not_ effect `test_color_count()`. And i think that you're right that PyMuPDF code and MuPDF code should not effect what `fitz.Pixmap.color_count()` returns.

So, as you say, the only thing remaining seems to be the JPEG library. Presumably Fedora's MuPDF is built to use Fedora's system JPEG library/libraries instead of MuPDF's built-in JPEG libraries in `mupdf/thirdparty/`.

[Normal builds of PyMuPDF (i.e. without setting PYMUPDF_SETUP_MUPDF_BUILD="") will do an internal build of MuPDF which will include JPEG code in MuPDF's `thirdparty/`. With these builds this test passes reliably (i.e. `pm.color_count()` returns 40624) on multiple systems in Github Actions running Windows, Linux (Ubuntu) and MacOS. And also on my own OpenBSD and Linux (Devuan) systems.]

Interestingly gimp-2.10.32p1 on OpenBSD-7.2 reports 39935 colours, same as your reported gimp value.

If Fedora's JPEG/color_count behaviour is thought to be correct even though different than when using normal PyMuPDF/MuPDF builds, we could change the test to use a non-lossy input file format.

A couple of ideas:

* Could you add `pm.save(f'{scriptdir}/test_color_count.png')` to `PyMuPDF/tests/test_pixmap.py:test_color_count()` just before the failing `assert()`, run tests, and post the resulting file `PyMuPDF/tests/test_color_count.png` here? This may clarify whether Fedora's JPEG library is giving different results from other systems.

* Could you try testing an official build of PyMuPDF (on pypi.org) using a venv? For example, in the parent directory of your PyMuPDF checkout, do:
  ```
  python3 -m venv pylocal
  ./pylocal/bin/python -m pip install pymupdf fonttools pytest
  ./pylocal/bin/python -m pytest PyMuPDF
  ```

**Comment by mjg** [comment]
So, sorry it took so long. I saved the jpg as png from the test suite (`pm_save()` as you suggested) in two settings:

1. pip_wheel: PyMuPDF 1.21.1 wheel from pip (including mupdf built against libjpeg I assume) on Fedora 38
2. f39_turbo: PyMuPDF 1.21.1 package built for Fedora 39 against system libs, in particular mupdf against libjpeg-turbo

Opening the pngs in GIMP on F38, I get 40624 colours for the first one and 39912 for the second one - exactly (and unsurprisingly) the numbers which the test suite (i.e. fitz) reports in those cases, and which differ from the number my GIMP reports for the jpeg. I have not checked which jpeg decoder GIMP uses.

The png diff (layers difference) looks interesting - the patterns seem to indicate artifacts of at least one decoding algorithm.
![test_color_count_pip_wheel](https://user-images.githubusercontent.com/233215/234556791-c5bd2653-4776-4d67-98cb-30338dc780ca.png)
![test_color_count_f39_turbo](https://user-images.githubusercontent.com/233215/234556798-cbdfe224-e092-4738-bea5-1313af390544.png)
