### ISSUE TITLE
support webp format

### ISSUE THREAD

**Issue by cole-dda** [pymupdf/PyMuPDF#2417]
https://pymupdf.readthedocs.io/en/latest/pixmap.html#supported-input-image-formats

also support input webp format?

**Comment by JorjMcKie** [comment]
Thanks for your post.
Forwarded your request to MuPDF maintainers, because this support has to be implemented in the base library.

**Comment by JorjMcKie** [comment]
Talked to our experts. They habe been considering this since a while, too. For the time being however, there are **no plans to support WebP** for the following reasons:
* This support would apply to WebP input only, WebP for "output" (i.e. stored in a PDF) is not possible, because the PDF spec does not support it.
* Otherwise, JPEG is superior anyway by far in all cases - except for lossless compression. MuPDF can store JPEG images in PDF.
* Support would require including another thirdparty library, which would bloat the size of our binary.

So I recommend using a package like Pillow for handling WebP input, then convert it to JPEG.
