### ISSUE TITLE
PyMuPDF 1.20.3 whl for python3.11 on win64

### ISSUE THREAD

**Issue by FlyinTeller** [pymupdf/PyMuPDF#2442]
**Is your feature request related to a problem? Please describe.**
Some packages like `paddleocr` have a requirement on `PyMuPDF<1.21`. For python 3.11, this results in a built from source, which can be tricky to get to work, see e.g. https://stackoverflow.com/questions/76379293/how-can-i-fix-the-error-in-pymupdf-when-installing-paddleocr-with-pip

**Describe the solution you'd like**
I have built the win64 whl file for cp311. Can you add it to PyPi? https://drive.google.com/drive/folders/1PESjDkovpvnrWFTKji4-qgT3rcVz-o-F?usp=sharing

**Comment by JorjMcKie** [comment]
I understand your request and I am aware of the StackOverflow post.
We also very much appreciate your far-reaching interest in PyMuPDF.

So we do hope you will understand our position and policies on this:

* We are fixing issues for future versions **only** - never for a backlevel version.
* We only publish versions (wheels) that have been created and tested diligently by us. So we reasonably can take over responsibility for the wheels associated with a respective version.
* When previous PyMuPDF versions have not been made available for some platform or some Python version, then this has happened for good reasons that existed at the time of publishing the version.
    - Although some of those reasons may have become obsolete over time, we will not be making retrograde changes and start filling earlier platform of Python version "gaps".

So we are sorry to have to turn down your request.
Personally, I also think the real problem is that package you mention. Its maintainers are the ones you should direct your enhacement request to.

**Comment by FlyinTeller** [comment]
thank you for the swift reply. I completely understand your reasoning and will close this request. Have a good day!

**Comment by JorjMcKie** [comment]
Thanks a lot for understanding!
