### ISSUE TITLE
Page.annots: docstring should include ValueErrors that can be thrown

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#2480]
docstring of `<page>.annots()` looks like this:
```
Generator over the annotations of a page.

Args:
    types: (list) annotation types to subselect from. If none,
           all annotations are returned. E.g. types=[PDF_ANNOT_LINE]
           will only yield line annotations.
```

I'd like it to look like this:
```
Generator over the annotations of a page.

Args:
    types: (list) annotation types to subselect from. If none,
           all annotations are returned. E.g. types=[PDF_ANNOT_LINE]
           will only yield line annotations.

Raises:
    ValueError: invalid annotations such as when an orphaned object
        as a None parent.
    <others?>
```
See #2479 where I cannot tell if the behaviour is correct or not

**Comment by cbm755** [comment]
Its possible that we've also seen `RuntimeError` from this function, although I'm not sure that was on the most recent release of PyMuPDF.

**Comment by JorjMcKie** [comment]
As discussion #2484 shows, this enhancement request is unfounded, because the generator-iterator `Page.annots()` will not raise this exception. Only illegally using it will.

What we can do, is repeating a warning that is already contained in the documentation: There exist hierarchic structures like `Document -> Page`, `Page -> Annot` for instance. The child items in these structures cannot be allowed to stay usable once their parent is gone.
So constructs of the lazy programmer like `doc[0].first_annot` will create an annotation that is "born as an orphan", because it creates a page, then creates an annot, then deletes the page ... leaving behind an annotation without parent page.
We may add a comment like `doc[0].annots()` will yield unusable (orphaned) annotation items ...

As far as other possibly raised exceptions go, like `RuntimeError`, we could add that to practically everything, because all MuPDF exceptions are mapped to this Python exception class - without us, on the Python level, ever being able to tell what actually has gone wrong. So the question is what we gain if we add `:raises RuntimeError: look at the "mupdf: ..." message`.
This doesn't preclude, as a backburner, that we might add this information in cases where we do know better ...
