### ISSUE TITLE
mac m1 pip install pymupdf 1.20.0  error

### ISSUE THREAD

**Issue by kuba001** [pymupdf/PyMuPDF#2497]
_**Please provide all mandatory information!**_

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

For problems when building or installing PyMuPDF, give the full output of the build/install command so that, for example, all pip/compiler/linker errors/warnings can be seen.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).
mac m1 pip install pymupdf 1.20  error
 ERROR: Failed building wheel for PyMuPDF
ERROR: Could not build wheels for PyMuPDF, which is required to install pyproject.toml-based projects
## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by julian-smith-artifex-com** [comment]
PyMuPDF 1.20 is quite old and i think it predates our support for MacOS/ARM.

The current release 1.22.5 has pre-built wheels for MacOS/ARM so might work better for you.

Otherwise, more information is required here:

* The exact install command that you are using to install PyMuPDF.
* The complete output from this install command.
* Full details about your operating system.
* Your python version.

**Comment by julian-smith-artifex-com** [comment]
I'll close this now; please reopen if you have new information.
