### ISSUE TITLE
how to remove highlight in pdf?

### ISSUE THREAD

**Issue by HazyGuo** [pymupdf/PyMuPDF#263]
Can PyMuPDF remove the highlights in pdf, not the annotations?

**Comment by JorjMcKie** [comment]
What are highlights if they are not annotations?

**Comment by HazyGuo** [comment]
The attachment is my test file, you can use it to test it.
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/2950326/test.pdf)

**Comment by JorjMcKie** [comment]
I see.
I assume you mean the yellow rectangles. They indeed are no annotations, Whoever created the PDF, has decided to **draw** those rectangles permanently - very much as you would when using `Page.drawRect` in PyMuPDF.
What happens, can be seen when you decompress a page's `/Contents` object (either via PyMuPDF or via the MuPDF command line tool: `mutool clean -d test.pdf test-expand.pdf`). You will then see this in object with `xref = 5`:

![grafik](https://user-images.githubusercontent.com/8290722/54095622-9f5b1e80-437e-11e9-8d6d-6bd8b12323bb.png)

The `re` commands in lines 129 & 131 draw rectangles, lines 130 & 132, fill them, line 128 defines color yellow,  etc.
In order to remove such things you would have write a script that analyzes the contents source, locates those commands and removes them. In this example, removing lines 129 through 132 would remove 2 yellow rectangles. Obviously, you must know what to look for (rectangles can also be drawn by drawing single lines - a different command), commands like `re` can be surrounded by any number of spaces or line breaks ... and more difficulties. But look here:

```python
>>> cont = doc._getXrefStream(5).split() # read contents page 0 and make a list of the tokens
>>> cont.index(b"rg") # look for RGB color command
163
>>> cont[160:170] # show some tokens around this place
[b'1', b'1', b'0', b'rg', b'1583', b'4949.67', b'184', b'184', b're', b'f']
>>> # deleting list entries 164 through 169 would remove 1 rectangle
....
>>> # make a bytes object again:
>>> c = b" ".join(cont)
>>> doc._updateStream(5, c) # rewrite the contents object
```
We changed this:
![grafik](https://user-images.githubusercontent.com/8290722/54096809-c9fba600-4383-11e9-8152-d8c35dd62e73.png)
to this: 
![grafik](https://user-images.githubusercontent.com/8290722/54096833-e4358400-4383-11e9-9d07-f2618ccc45ca.png)

**Comment by HazyGuo** [comment]
Thanks for your response, it is very useful to me, I will try it.

**Comment by HazyGuo** [comment]
Hello JorjMcKie, it seems that I can only get part of xref stream, not all of the pages.

**Comment by JorjMcKie** [comment]
Every page has its own `/Contents` objects of course!
A list of a page's xref numbers of such objects is this: `Page._getContents`. You have to go through al of them ...

**Comment by HazyGuo** [comment]
Thanks, it resolves my issue.
