### ISSUE TITLE
Segfault when using BytesIO as a stream for insertImage

### ISSUE THREAD

**Issue by killthekitten** [pymupdf/PyMuPDF#274]
Before I start to complain: thanks for an awesome tool! 😅 

So, I tried to insert an image into a PDF and... bad things happened. Turns out passing `BytesIO` as a stream for `insertImage` results in a segfault. It was hard to debug in a real setup, but it boils down to this code:
https://gist.github.com/killthekitten/2f5acc5799c8166902ce95d43feeb9c2

From @JorjMcKie's [earlier comments](https://github.com/pymupdf/PyMuPDF/issues/72#issuecomment-251904584) it's clear that I shouldn't have used `BytesIO` in the first place but nothing stopped me – which is actually my only issue here. There is even a note in the docs, but I somehow ignored it.

Should we introduce a type check similar to what is done in [`Document`'s constructor](https://github.com/pymupdf/PyMuPDF/blob/master/fitz/fitz.py#L1800) to make it simpler to debug?

**Comment by JorjMcKie** [comment]
I must say you have a very polite way of complaining ... :-))
But you are right: it shouldn't happen.
Let me take it on my list for the next version, ok?
April is the usual month of base library MuPDF's next version (semi-annual release schedule), so I would prefer to not squeez in another version of PyMuPDF before that.

**Comment by killthekitten** [comment]
Sure! I could draft a PR if you don't mind. It'd be great to unify all the methods accepting `stream` arg to use the same check, and also add notes on Readme/docs why exactly does it have to be a bytes object.

**Comment by JorjMcKie** [comment]
Of course it doesn't **have** to be bytes, it could well alternatively be `io.BytesIO` and a ``bytesarray``, too. Would be rather trivial within a future type check to also test for an attribute ``getvalue`` in case of a negtive response.

For an overall unified behaviour in that respect, there exist some complications (could be overcome, too, for sure): (1) interfacing with MuPDF via SWIG has its restrictions, when it comes to function overloading (thinking of the different options to create a pixmap), (2) need to support (including test!) Py2.7 and all Py3.4+ with exactly the same interface (whereever possible). From the top of my head:

* Binary **input**:
   - `insertImage`, as discussed (Python wrapper)
   - `embeddedFile`, `FileAttachment` annots: bytes or bytesarray, directly C, Python wrapping would have to be created to allow for BytesIO. I have been too lazy to allow for filenames, too.
   - pixmaps from str doesn't work because of str = bytes in Py2. This too is direct C with function overloading via SWIG. So image **streams** have to be an object type which is different from str in all Python versions

* Binary **output**:
   - pixmap `getImageData`, document `extractImage`,  `embeddedFileGet`, annotation `fileGet`: bytes in Py2 (i.e. str) and Py3
   - page getText("dict") is a dictionary, also containing anyimages as base64 encoded strings in Py2 and bytes in Py3

**Comment by JorjMcKie** [comment]
forgot the ``Document`` class, which also supports stream input

**Comment by killthekitten** [comment]
@JorjMcKie thanks for the detailed writeup! I'll look into it over the weekend.

**Comment by JorjMcKie** [comment]
You are welcome.
BTW I have found an easy way to add BytesIO support, and I am testing already.
Bottom line will be, that everywhere where binary input is possible today, a BytesIO object is allowed, too. When this happens, I am just using the ``getvalue()`` method of this class. Fortunately, this is equally supported in Py2.
Because I didn't want to introduce Python wrappers all over the place, the remaining issue was how to determine this argument type in C. Certainly possible, but requires the full C source of Python if you want to do it in the cleanest possible way - a prohibitive condition, which I cannot impose on the installing user. So what I am doing now is first check for bytes and bytearray, and if these fail, check whether the argument has an attribute ``getvalue``. If yes, I just assume all is good.

**Comment by JorjMcKie** [comment]
If you are interested in future contribution to PyMuPDF and if you are proficient in C you want to take a look at those changes - just give me an indication and I'll send you a ZIP of the changed source ...

**Comment by killthekitten** [comment]
Not proficient, but I could try. Could you send the changes to a temporary branch?

**Comment by JorjMcKie** [comment]
Just uploaded v1.14.13, which should fix the issue. Sorry, your issue disturbed my peace of mind so much, that I couldn't resist to do it myself.

You can create a diff to see the changes compared to 1.14.12.

If you seriously want to contribute to PyMuPDF in a broad way in future, you must be acquainted with C, SWIG, and also the MuPDF C source - apart from Python, of course.

This is a lot.

Maybe an easier way to get involved is the topic **test**. I am only using dozens of single test scripts and no unified formal approach I must confess.
If you want to could start here and make a major difference to the whole repo!

**Comment by JorjMcKie** [comment]
Oh, by the way:
Because of SWIG, changes to ``fitz.py`` and ``fitz_wrap.c`` make no sense at all - they both are generated by SWIG based on files having a ``.i`` extension.

**Comment by killthekitten** [comment]
You're amazing! I'll switch to the new version and report back later today or tomorrow. 

We're on `black` since January as well, I love that it just works 👍 Regarding SWIG: it was stupid from my side to assume I can change the python code directly, since I read the actual `.i` files :) thanks for the note

**Comment by JorjMcKie** [comment]
Very flattering, thanks! In German: "danke für die Blumen!"
Have fun with PyMuPDF!
