### ISSUE TITLE
Support for OpenType features such as proportional figures (pnum), lining figures (lnum) and tabular figures (tnum)

### ISSUE THREAD

**Issue by joachim-broser** [pymupdf/PyMuPDF#2801]
_Jorj et al., 
Thank you for your great work!_

Are you planning to provide support for **OpenType features** in the future? 

Especially for 
- Lining figures (`lnum`) [https://helpx.adobe.com/fonts/using/open-type-syntax.html#lnum](https://helpx.adobe.com/fonts/using/open-type-syntax.html#lnum)
- Proportional figures (`pnum`) [https://helpx.adobe.com/fonts/using/open-type-syntax.html#pnum](https://helpx.adobe.com/fonts/using/open-type-syntax.html#pnum)
- Tabular figures (`tnum`) [https://helpx.adobe.com/fonts/using/open-type-syntax.html#tnum](https://helpx.adobe.com/fonts/using/open-type-syntax.html#tnum)

**Comment by JorjMcKie** [comment]
Thank you very much for your nice feedback!
Please direct this suggestion to MuPDF, because it is the base library that has to make such decisions. I recommend entering the public MuPDF [Discord](https://discord.gg/KPX8ZYDr) channel where these things are discussed.
PyMuPDF itself cannot do anything about this - so I am taking the liberty to mark your post as "won't fix" in this repo.
