### ISSUE TITLE
Memory Leak with getText(“rawDICT”)

### ISSUE THREAD

**Issue by zufj** [pymupdf/PyMuPDF#290]
We think there might be a memory leak within the getText(“rawDICT”) method. We tried several sister methods like getText() in our investigations.

You’ll see below a couple of charts tracking memory usage over a hundred iterations.

### 1. Memory usage of getText() - Flat

![memusage_gettext](https://user-images.githubusercontent.com/10831452/56753630-46f3ab00-678b-11e9-9b46-dd809f36be8c.png)

### 2. Memory usage of getText(“rawDICT”) - Increasing (despite clean-up attempts)

![memusage_gettextrawDICT](https://user-images.githubusercontent.com/10831452/56753610-3d6a4300-678b-11e9-832c-46ac3bb32e15.png)

It seems the getTextWords() is also affected by the leak similarly (though to a lesser extent as it generates less data than rawdict). 

## Script used
```
import fitz
import os
import psutil
import gc

# Loop
niter = 100

memory_usage_start = [0]*niter
memory_usage_before_gc = [0]*niter
memory_usage_stop = [0]*niter

for i in range(niter):
    
    # Record initial memory usage
    process = psutil.Process(os.getpid())
    memory_usage_start[i] = process.memory_info().rss/2**20
    
    # Load file
    doc = fitz.open(pdf_file_path)
    page_count = doc.pageCount
    page = 0
    text = ''
    
    # Extract text
    while (page < page_count):
        p = doc.loadPage(page)
        page += 1
        #words = p.getTextWords()
        rawdict = p.getText("rawDICT")
        # text += p.getText()
    
    # Record memory usage before cleanup
    memory_usage_before_gc[i] = process.memory_info().rss/2**20
    
    # Cleanup attempt
    #del text
    doc.close()
    gc.collect()
    
    # Record mem final usage
    memory_usage_stop[i] = process.memory_info().rss/2**20
    

# Viz mem usage VS iterations
from pylab import *

iteration = list(range(0,niter))

plot(iteration[20:], memory_usage_start[20:])
plot(iteration[20:], memory_usage_before_gc[20:], 'r+')
plot(iteration[20:], memory_usage_stop[20:], 'g')

xlabel('iteration')
ylabel('memory usage (Mb)')
title('Memory usage over getText("rawDICT")')
grid(True)

```

## Environnement
* Debian Stretch and Ubuntu based docker for Jupyter repro)
* Python 3.6.7
* PyMuPDF             1.14.13 

We’re available to provide further information (or to receive usage suggestions). Thanks for looking into it!

**Comment by JorjMcKie** [comment]
Wow that's a true issue!
Probably goes back to a flaw in the design of the method ("dict" and "rawdict" use the same C-level functions):
What I am doing there, is creating a nested Python dictionary structure. The problem you uncovered seems to be, that sub-dictionaries are counted as being "in use", so ``gc`` refuses to garbage collect them ... until the very end of the program.

Please give me some time to further investigate. Are there any limitations / restrictions on your side?

I would hate to go back to JSON text output and create the dictionary from there ...

**Comment by JorjMcKie** [comment]
A fix has been found and implemented.
WIll be published with the next version.

**Comment by zufj** [comment]
Thank you so much!

Let me know if we can be of help in testing it - we'd be happy to contribute to the effort.

Thanks again for the work spent on this great module.

**Comment by JorjMcKie** [comment]
You are welcome. I am about compiling the wheels and will let you know from where to download the right one.
You are on Linux I presume? Or Mac?
If on Windows, I would send you one via mail, because I generate those wheels locally.

Some remarks on what I did:
As mentioned, the memory growth came from the large and highly nested dictionary structure, which I created completely in C. This was very fast, but Python's gc has no way of knowing where all the memory pieces of the lower level components in that dictionary are and consequently cannot free them.

I must say, I was surprised to learn about that - thanks again for bringing up this issue!

If you know a bit about the Python-C interface:
There is a function ``Py_BuildValue()`` which returns Python objects based on a character string code. E.g. ``Py_BuildValue("iiii", ...)`` will return a tuple of 4 integers. In that case, everything is well-behaving: If you then no longer use this tuple back on the Python language level, gc will collect it.
If you code ``Py_BuildValue("(ii)(ii)", ...)`` it will return a tuple of 2 tuples of 2 integers each - if you see the principle.
**_But_:** in the latter case gc will never free the memory of the 2 sub-tuples!

So what I am doing now is strictly handing back flat (shallow) lists or tuples - no more nesting. This implies building the ``rawdict`` dictionary in Python code, which makes it known to gc and eligible for freeing.
This, however, comes with a performance penalty. But the function is still faster than the ``xml`` variant ...

**Comment by JorjMcKie** [comment]
You can download Linux wheels from [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux) now.
Another branch called ``osx`` will have the Mac wheels in a few minutes.

**Comment by zufj** [comment]
Thanks for the quick turnaround. I was about to test it but encountered an issue while installing the wheel:

``
  File "/opt/conda/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
``

Here's how I tried to install it (also tried directly from the file):

``
pip install --no-cache-dir https://github.com/pymupdf/PyMuPDF-wheels/blob/linux/PyMuPDF-1.14.15-cp36-cp36m-manylinux1_x86_64.whl -vvvv
``

**Comment by JorjMcKie** [comment]
worked fine in my environment:

1. downloaded directly from github using this menu
![grafik](https://user-images.githubusercontent.com/8290722/56909631-96c9bf00-6a76-11e9-9888-70ac288b8bf5.png)

2. then did ``sudo -H python3 -m pip install -U PyMuPDF...whl``

**Comment by zufj** [comment]
Apologies: apparently something is wrong in my docker environment. It worked fine on my Ubuntu machine. I will report back when I found what caused this. Thanks again
