### ISSUE TITLE
PyMuPDF can't show the first page of some epub files while SumatraPDf can show it.

### ISSUE THREAD

**Issue by yinkaisheng** [pymupdf/PyMuPDF#291]
PyMuPDF can't show the first page(cover page) of some epub files.
doc returns a completely transparent image when I call doc.loadPage(0).getPixmap().writePNG('page0.png')

"Python Web Scraping(2nd).epub" is one of the epub files.

[Python Web Scraping(2nd).zip](https://github.com/pymupdf/PyMuPDF/files/3123618/Python.Web.Scraping.2nd.zip)

![image](https://user-images.githubusercontent.com/5846696/56846340-c060da00-6900-11e9-8a04-2111b725e381.png)

**Comment by JorjMcKie** [comment]
Yes, confirmed.
This is the same with MuPDF's own viewer - which is why I cannot do anything about it in PyMuPDF.
As mentioned in #292, SumatraPDF uses an old version of MuPDF (1.6). Why this version delivers **better** results in this case ... I don't know.
Maybe you should submit a bug report to Artifex with this example attached - but **do shorten it** - they have a MB limit for attached files.
The header page itself is just a JPEG, which can be confirmed by looking into the file (EPUB is a ZIP-based format). So I don't see a reason there ...

**Comment by JorjMcKie** [comment]
Update:
While testing the newest release 1.16.0 I found this bug fixed upstream by MuPDF.
So once the corresponding PyMuPDF version is published (takes a few more days), you can expect this issue solved.

**Comment by yinkaisheng** [comment]
OK. Thanks.
