### ISSUE TITLE
Sizing of text in a redaction tends to run very small at times.

### ISSUE THREAD

**Issue by mrw-dev** [pymupdf/PyMuPDF#2933]
### Description of the bug

Using the add_anot_redact method, I am passing in some simple text to and setting the fontsize to 20 and the font of 'tiro'.  The text is very often very small in the redaction box and very often not vertically centered (at least not very well).

The redaction rectangle is working very well as expected and exactly covers the text that I want to redact.  Howeve, the drawing of the text is very somewhat different.  Here are some screenshots of a few redactions so you can see more explicitly what I am talking about (these are completely public documents).

This first example actually is pretty good:

![image](https://github.com/pymupdf/PyMuPDF/assets/144351514/616f1b51-8868-4955-a175-e97e6d09b9a9)

The second example shows a string of capitalized letters "AAAA" and they are fairly small versus the size of the redaction rectangle.  The underlying code iterates to find the proper code size and it seems to go too small.

![image](https://github.com/pymupdf/PyMuPDF/assets/144351514/1c931c59-8bc4-44c5-9853-fab764ba2e3a)

The third example, the string "BC03" is written (no extra characters before or after). and it is extremely small and the vertical centering is way off.  It was able to fit the BC03 on one line but it made room to add another lline that was not needed.  I expect that the code is checking the width and if it is within a certain percentage it keeps dropping the font size (just my guess).

![image](https://github.com/pymupdf/PyMuPDF/assets/144351514/edcbed41-8275-4809-b73f-362823b32182)

I tried to write my own text over the redacted area using insert_textbox().  I iterated the fontsize by checking the width & hieight and I ended up also still seeing the same kind of layout issues.  The insert_textbox is obviously checking to see if it fits based upon its own calculation and doesn't draw other wise.  

I would really like to fill the HEIGHT of the rectangle more fully.  I could of course increase the size of the output rectangle and just draw it myself but the vertical centering as well as when the width is small would still cause issues.   Am I missing something or is this just the way it works.

### How to reproduce the bug

                    highlight = page.add_redact_annot(quad=quad_coords,
                                                      text= redaction_text,
                                                      text_color=getTupleColor(font_color),
                                                      fontname='tiro',
                                                      fontsize=20,
                                                      align=TEXT_ALIGN_CENTER,
                                                      fill=getTupleColor(bkgd_color),
                                                      cross_out=False)
                   apply_redactions(page)

### PyMuPDF version

1.23.8

### Operating system

Linux

### Python version

3.11

**Comment by JorjMcKie** [comment]
The insertion of replacing text has its limits. It internally uses `page.insert_textbox()` and checks for the return code. If there is a non-fit, the font size is reduced down to some lower limit.

I don't want to invest too much effort in this - just to achieve some limited improvements. If the new text is longer than the original, there simply is no hope to ever produce good results.

In addition, original text may have been written with too narrow inter-line distances. A correct removal would then require to reduce the redaction rectangle height in order to not mutilate lines above / below. In that case: how on earth would you ever create an automatic text replacement

I would change the approach to put in replacement text:
1. remove the original text via redaction as before, but without replacement text. Instead extract the original text span covering the place and store relevant info for later, like font size, insertion point ("origin"), potentially even font or text color.
2. After `page.apply_redactions()`, insert the replacement text using all desired properties: specifically insertion point, but maybe also the font, font size, text color etc. One can even apply "morphing" to shrink only the width of the new text and not the height, and more like that.

**Comment by mrw-dev** [comment]
Thanks for your prompt feedback.  I agree it's a tough nut to crack.
