### ISSUE TITLE
Will pymupdf support `PAX` attribution?

### ISSUE THREAD

**Issue by xsank** [pymupdf/PyMuPDF#2940]
Some paper use PAX as `cite`
eg:
```shell
α∗
th
{'kind': 4, 'xref': 314, 'from': Rect(144.49099731445312, 105.655029296875, 148.4770050048828, 123.5889892578125), 'nameddest': 'PAX%40.%2Fpapers%2F224_Paper.pax%401', 'id': ''}
e1
{'kind': 4, 'xref': 316, 'from': Rect(249.94500732421875, 505.87701416015625, 257.9150085449219, 520.0850219726562), 'nameddest': 'PAX%40.%2Fpapers%2F224_Paper.pax%402', 'id': ''}
(Head
r sum-
{'kind': 4, 'xref': 317, 'from': Rect(264.44500732421875, 623.175048828125, 291.1260070800781, 636.9190063476562), 'nameddest': 'PAX%40.%2Fpapers%2F224_Paper.pax%403', 'id': ''}
```

Pymupdf could find the `from` rect, but missing the `to` point

I could not find any related docs in the website：https://pymupdf.readthedocs.io/en/latest/search.html?q=PAX&check_keywords=yes&area=default

will pymupdf support this feature? thanks

**Comment by JorjMcKie** [comment]
This is already supported!
You are showing so-called "named" destination links. They do not have a "to" attribute because the symbolic name given under "nameddest" has all that information.
Please use a variant of the import statement `import fitz_new as fitz` to activate full named destination support.
This "rebased" implementation will replace the current, "classic" implementation during the first half of January.

**Comment by xsank** [comment]
nameddest only contains the information of `PAX@./papers/224_Paper.pax@5`

**Comment by xsank** [comment]
In fact, `cite` have the `to` attribution,

**Comment by JorjMcKie** [comment]
> In fact, `cite` have the `to` attribution,

What is cite?

**Comment by JorjMcKie** [comment]
I am going to move this to the "Discussions" tab. This is no issue.
