### ISSUE TITLE
insert_textbox parameter for adjustment in y

### ISSUE THREAD

**Issue by Andreasox** [pymupdf/PyMuPDF#2967]
In addition to the support for text adjustment in x (TEXT_ALIGN_*),
adjustment in y should be helpful to e.g. position text in road shields exactly in the center.
To my understanding, this can only currently be achieved by hardcoding the y position.
Proposed values:
0 lower (default, as now ) 
1 center  text positioned in the middle of the textbox
2 upper text positioned at the upper position of the textbox

<img width="67" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/6737097/fcebcefe-029d-4a3c-8e56-562ad415da84">

**Comment by JorjMcKie** [comment]
I am afraid we will not be able to implement this anytime soon. A solution is way more complex as it may seem at first sight.

However, I think I have an even better and more elegant solution for you: Use `page.insert_htmlbox()` instead of the other two. Documented [here](https://pymupdf.readthedocs.io/en/latest/page.html#Page.insert_htmlbox), simple examples [here](https://pymupdf.readthedocs.io/en/latest/recipes-text.html#how-to-fill-a-box-with-html-text).

In essence, you can enrich your text with HTML and CSS styling information to achieve whatever you can think of. Here is an example that does what I can read from your post:
```python
import fitz

doc = fitz.open()
page = doc.new_page()
r = fitz.Rect(100, 100, 200, 200)
text = "111"
fontsize = 20
free = r.height - fontsize  # overall height not occupied by text
top = free / 2  # free space above text
btm = free / 2  # free space below text
css = "* {text-align:center;margin-top:%gpx;margin-bottom:%gpx;font-size:%gpx;}" % (
    top,
    btm,
    fontsize,
)
page.insert_htmlbox(r, text, css=css)
# make background
page.draw_rect(r, color=(1, 0, 0), fill=fitz.pdfcolor["gold"], overlay=False)
doc.ez_save(__file__.replace(".py", ".pdf"))
```
Looks like this:
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/77920939-b4b5-496c-aed6-27d293462864)

**Comment by Andreasox** [comment]
Thanks, I understand the complexity of an implementation. htmlbox will be sufficient for our needs.

**Comment by JorjMcKie** [comment]
Thank you for consent.
