### ISSUE TITLE
Story does not honor CSS-defined fonts

### ISSUE THREAD

**Issue by Andreasox** [pymupdf/PyMuPDF#3083]
### Description of the bug

Regardless of CSS-defined font, the text content of a story in the created PDF uses CharisSIL (for serif fonts) or NimbusSans (for serif fonts). Tested with a host of fonts like Arial, Verdana, helv, Verdana etc.
[4558_sans-serif.pdf](https://github.com/pymupdf/PyMuPDF/files/14024779/4558_sans-serif.pdf)
[4558_serif.pdf](https://github.com/pymupdf/PyMuPDF/files/14024780/4558_serif.pdf)

### How to reproduce the bug

PDF creates using the multi-page table story example with the following HTML/CSS:
HTML = """
    <body>
    <table>
    <tr id="row">
        <td id="hrs"></td>
        <td id="min_week"></td>
        <td id="min_sat"></td>
        <td id="min_sun"></td>
    </tr>
    </table>
    </body>
"""

CSS = """
body {
    color: device-cmyk(0, 0, 0, 1);
    table-layout: fixed;
    white-space: pre;
    font-family: "Arial";
    font-size: 9px;
}
td[id="hrs"] {
    font-weight: bold;
    text-align: center;
    padding-left: 5px;
}
td[id="min_week"] {
    text-align: left;
    padding-left: 5px;
}
td[id="min_sat"] {
    text-align: left;
    padding-left: 5px;
}
td[id="min_sun"] {
    text-align: left;
    padding-left: 5px;
}"""

and with position/draw commands:
    story.element_positions(recorder, {"page": page, "filled": where.y1})
    story.draw(dev)  # write timetable content to page

### PyMuPDF version

1.23.17

### Operating system

MacOS

### Python version

3.9

**Comment by JorjMcKie** [comment]
Try `sans-serif` instead of Arial. This will lead to using Helvetica (very similar to arial). Arial is not a generic font-family name.
And MuPDF **_does not access_** a platform's installed files to find such matches.

To force using a specific arial font file family, define them via  @font-face rules.

**Comment by Andreasox** [comment]
Thanks, we have managed to use font-face to use the required font (Gotham). 
For us it is weird that you must use font-face with a src and that this does not work:
body {
    color: device-cmyk(0, 0, 0, 1);
    table-layout: fixed;
    white-space: pre;
    font-family: "Gotham";
    src: url("/xxxx/GothamNarrow-Medium.otf");
    font-size: 9px;
}

**Comment by JorjMcKie** [comment]
This is how I make the MS Comic Sans font being used:
```python
css = """
@font-face {font-family: comic; src: url(comic.ttf);}
@font-face {font-family: comic; src: url(comicbd.ttf);font-weight: bold;}
@font-face {font-family: comic; src: url(comicz.ttf);font-weight: bold;font-style: italic;}
@font-face {font-family: comic; src: url(comici.ttf);font-style: italic;}
* {font-family: comic;}
"""
arch = fitz.Archive("C:/Windows/Fonts")  # where those files live
```
Then story must also have argument `archive=arch`.

> Is this behaviour documented?

Yes, somewhere. Definitely in the MuPDF doc. Would need to dig if you don't believe me.

**Comment by Andreasox** [comment]
I was maybe unclear in my description. pyMuPDF story creates PDF with the NimbusSans font when defining any sans serif font in the CSS (Arial, Helvetica, sans-serif etc.) and CharisSIL for any serif fonts (Times etc.).
Tested both on Mac and Windows. I cannot find either CharisSIL or NimbusSans font file on my computer so I assume they resides somewhere in the muPDF installation.

**Comment by JorjMcKie** [comment]
> I was maybe unclear in my description. pyMuPDF story creates PDF with the NimbusSans font when defining any sans serif font in the CSS (Arial, Helvetica, sans-serif etc.) and CharisSIL for any serif fonts (Times etc.). Tested both on Mac and Windows. I cannot find either CharisSIL or NimbusSans font file on my computer so I assume they resides somewhere in the muPDF installation.

Correct - MuPDF comes with a bunch of fonts. If you ever downloaded the MuPDF source, you will find them in folder `mupdf/resources/fonts`.
Some, not all of these fonts do land in MuPDF's binary (used by applications footing on it like PyMuPDF). There are options in the binary generation that let you select fonts - a desirable feature, because including all bloats that binary's size easily up by 10 MB and more. That is a waste of space - dead code and not used for 99+% of all time.
PyMuPDF therefore uses a moderate subset - the selection being defined in [_config.h](https://github.com/pymupdf/PyMuPDF/blob/main/src_classic/_config.h). That C-header file serves as a MuPDF binary generation option.

The font situation overall remains below top satisfaction level. (Py)MuPDF cannot be dependent on the particular situation of the zillions of platforms it runs on - neither can it access the internet for additional fonts while the script is running. So it is confined to the fonts it carries with it.

MuPDF does support plugins (function stubs) that allow defining access to fonts of the (local) platform. In doing so, MuPDF will automatically include the named folders in its font searching algorithm.
In PyMuPDF, we are underway to open up access to this feature. Thanks to PyMuPDF's now active rebased architecture, these things can be more easily accessed via the `fitz.mupdf` sub-module.
This is done by a colleague - need to check with him how far we are here.

**Comment by Andreasox** [comment]
Thanks a lot for the detailed desc. I certainly understand your issues. T-Kartor has created high-quality cartographic products as EPS/PDF (incl. advanced Ghostscript usage) and needed cartographic production systems since 1989. 
I will soon create another issue/discussion about font naming which I guess tightly relates to this.

**Comment by JorjMcKie** [comment]
@lexxwork 
I don't know, maybe that MuPDF indeed does not use font-stretch as a font selection differentiator if the same font-family name is used.
I tried a few things and repeated all descriptors in both cases, but it did not help:
```css
@font-face {
  font-family: 'Roboto';
  src: url('Roboto-Regular-Condensed.ttf');
  font-stretch: condensed;
  font-weight: normal;
}
@font-face {
  font-family: 'Roboto';
  src: url('Roboto-Light.ttf');
  font-stretch: normal;
  font-weight: light;
}
```
Maybe you ask this question in MuPDF's [Discord]() channel.
You can of course always use different font-family names ...
