### ISSUE TITLE
Extracting tables across multiple pages?

### ISSUE THREAD

**Issue by CaiSamuelsFSA** [pymupdf/PyMuPDF#3114]
### Description of the bug

I am trying to extract tables that span across multiple pages while maintaining the formatting but it doesn't seem like this is possible as PyMuPDF assumes that any tables on a new page are new tables rather than the continuation of tables.

### How to reproduce the bug

page.find_tables() only extracts tables on a single page rather than across multiple pages.

### PyMuPDF version

1.23.20

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
This is intended and works as designed. There is no meaningful general way for how to determine that a table on a subsequent page is indeed a continuation.

We suggest you have a look at [this](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/table-analysis/join_tables.ipynb) folder of recipes, where you find a solution based on using the pandas DataFrame output of tables.

**Comment by CaiSamuelsFSA** [comment]
Looking at that solution, it seems to only work assuming that there is only one table on the page, however I have multiple tables spread over multiple pages.

**Comment by JorjMcKie** [comment]
Sure, depending on your situation, the application code needs to take things like this into account.

For the foreseeable future, we have no plans to extend our table features in this direction.
Extending table **_recognition_** is by far more important to us, because the chances for improving the detection rate based on application code are much lower.

In contrast to this, joining tables fragments across page breaks is achievable by app code.
