### ISSUE TITLE
text is not read by fitz like SYMBOLS LIST and E-0.0 .i attached pdf page 

### ISSUE THREAD

**Issue by vampiresati** [pymupdf/PyMuPDF#3118]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Potentially add an issue reference.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Are there several options for how your request could be met?
[3590-Conformed-Plans-2023-10-13-09-17-58-935_compressed-179-208-1.pdf](https://github.com/pymupdf/PyMuPDF/files/14112749/3590-Conformed-Plans-2023-10-13-09-17-58-935_compressed-179-208-1.pdf)

**Additional context**

**Comment by vampiresati** [comment]
text is not read like SYMBOLS LIST
![Screenshot from 2024-01-31 19-46-31](https://github.com/pymupdf/PyMuPDF/assets/13086545/3a9bec32-68d9-4e02-9995-34b63e628046)

**Comment by vampiresati** [comment]
`    pdf2=fitz.open(pdf_f_n)
    fitz_page = pdf2[0]
    fitz_page_size = fitz_page.rect
    li=[]
    page2 = fitz_page
    page2.clean_contents()
    try:
        for bno, block in enumerate(page2.get_text("dict")["blocks"]):
            if block['type'] == 1:
                pass
            if block['type'] == 0:
                for l in block["lines"]:
                    for s in l["spans"]:
                        # print('span block')
                        # print(s)
                        if s.get("text"):
                            # print('span text')
                            # print(s['bbox'], s['text'])
                            angle = page2.rotation
                            cropbox = page2.rect
                            d = {}
                            if angle==0:
                                bbox = list(s['bbox'])
                                d['bbox']=bbox
                            elif angle==270:
                                bbox = fitz.Rect(s['bbox'])
                                rect = bbox * page2.rotationMatrix
                                bbox = list(rect)
                                d['bbox'] = bbox
                            else:
                                bbox = fitz.Rect(s['bbox'])
                                rect = bbox * page2.rotationMatrix
                                bbox = list(rect)
                                d['bbox'] = bbox
                            d['text'] = [s['text']]`

**Comment by vampiresati** [comment]
pdf2=fitz.open(pdf_f_n)
    fitz_page = pdf2[0]
    fitz_page_size = fitz_page.rect
    li=[]
    page2 = fitz_page
    page2.clean_contents()
    try:
        for bno, block in enumerate(page2.get_text("dict")["blocks"]):
            if block['type'] == 1:
                pass
            if block['type'] == 0:
                for l in block["lines"]:
                    for s in l["spans"]:
                        # print('span block')
                        # print(s)
                        if s.get("text"):
                            # print('span text')
                            # print(s['bbox'], s['text'])
                            angle = page2.rotation
                            cropbox = page2.rect
                            d = {}
                            if angle==0:
                                bbox = list(s['bbox'])
                                d['bbox']=bbox
                            elif angle==270:
                                bbox = fitz.Rect(s['bbox'])
                                rect = bbox * page2.rotationMatrix
                                bbox = list(rect)
                                d['bbox'] = bbox
                            else:
                                bbox = fitz.Rect(s['bbox'])
                                rect = bbox * page2.rotationMatrix
                                bbox = list(rect)
                                d['bbox'] = bbox
                            d['text'] = [s['text']]

**Comment by JorjMcKie** [comment]
I am afraid I don't understand what you mean by "support" or "text is not read".

When using text extraction, everything on the page that is **_defined_** as text is also **_extracted_** as text: there are no unrecognized glyphs or similar.

Things you see on the page that are not included in the output of `page.get_text()` ... these things are no text, but either images or vector graphics.
There is no way to convert these objects to text by some magic - even not by applying OCR techniques in most cases, as far as I can see. The reason is that even an OCR engine needs to know a font that can resemble those graphics as a glyph, and I am not aware of any such support. You can try out yourself and see how far this approach gets you.

Let me put it the other way round:
If you have a PDF containing text written in a supported font, then it will be extracted by PyMuPDF.
For anything else on the page there forever only exist the options to either
* convert it to text via OCR
* extract it as vector graphics
* extract it as image

**Comment by vampiresati** [comment]
okay thanks.i will use another kind of methods to achieve this
