### ISSUE TITLE
Get cropbox and mediabox from PyMuPDF

### ISSUE THREAD

**Issue by cges30901** [pymupdf/PyMuPDF#317]
I was using PyPDF2 to get cropbox or mediabox of a page (because I want to crop the page), now I want to do the same thing with PyMuPDF. However, PyPDF2 and PyMuPDF return different cropbox and mediabox for one of my PDF documents. Here is the test code:
```
import fitz
from PyPDF2 import PdfFileReader

fitzdoc=fitz.open("test.pdf")
fitzpage=fitzdoc.loadPage(0)
print(fitzpage.rect)
print(fitzpage.CropBox)
print(fitzpage.MediaBox)
print(fitzpage.bound())
xref = fitzpage.xref
print(fitzdoc._getXrefString(xref))

pypdfdoc=PdfFileReader("test.pdf")
pypdfpage=pypdfdoc.getPage(0)
print(pypdfpage.mediaBox)
print(pypdfpage.cropBox)
```
Here is the output:
```
Rect(0.0, 0.0, 1006.0, 750.0)
Rect(0.0, 0.0, 1006.0, 750.0)
Rect(0.0, 0.0, 1006.0, 750.0)
Rect(0.0, 0.0, 1006.0, 750.0)
<<
  /Type /Page
  /Contents 3 0 R
  /Resources 5 0 R
  /MediaBox [ 9 11 1015 761 ]
  /Parent 2 0 R
>>
RectangleObject([9, 11, 1015, 761])
RectangleObject([9, 11, 1015, 761])
```
From the output, we can see that rect, CropBox, MediaBox and bound() from PyMuPDF return Rect(0.0, 0.0, 1006.0, 750.0). So is there a way to get (9, 11, 1015, 761) from PyMuPDF?

(I think the original PDF is copyrighted, so I only upload the first page.)
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/3348438/test.pdf)

**Comment by JorjMcKie** [comment]
Yes there is a way. Let me explain some things around the topic:
* (Py-) MuPDF always uses a page's top-left point as the origin (0,0) of its coordinate system - for whatever reason, prresumably because it does not only deal with PDF, but also other document types.
* PDF uses a page's **bottom-left** point as (0,0).
* MuPDF provides a way to translate between those two coordinate systems: the so-called transformation matrix, available in PyMuPDF via ``page._getTransformation()``. This matrix takes the original PDF geometry of a page and translates it to the MuPDF geometry. The **inverse** of that matrix then obviously generates original PDF coordinates from any geometry object defined in PyMuPDF. "Geometry" objects are things like ``Rect``, ``IRect``, ``Point`` and ``Matrix``.
* In PyMuPDF, you can access the values of the page rectangle, CropBox and MediaBox via properties ``page.rect``, ``page.CropBox``, ``page.MediaBox`` - all in MuPDF coordinates. Those three are normally, but not always equal.

Here is what happens in your example:

```python
>>> import fitz
>>> doc=fitz.open("test.pdf")
>>> page=doc[0]
>>> page.rect
Rect(0.0, 0.0, 1006.0, 750.0)
>>> page.CropBox
Rect(0.0, 0.0, 1006.0, 750.0)
>>> page.MediaBox
Rect(0.0, 0.0, 1006.0, 750.0)
>>> # we see: there are all the same
>>> # the page transformation matrix:
>>> mat = page._getTransformation()
>>> mat
Matrix(1.0, 0.0, 0.0, -1.0, -9.0, 761.0)
>>> # recover original rect / MediaBox / CropBox:
>>> page.rect * ~mat  # multiply with inverted transformation matrix
Rect(9.0, 11.0, 1015.0, 761.0)
>>> # this is the definition in the PDF file, as we see here:
>>> print(doc._getXrefString(page.xref))
<<
  /Type /Page
  /Contents 3 0 R
  /Resources 5 0 R
  /MediaBox [ 9 11 1015 761 ]
  /Parent 2 0 R
>>
>>>
```

**Comment by JorjMcKie** [comment]
By the way, you can set a page's cropbox in PyMuPDF, too: ``page.setCropBox(r)`` with any rect-like sequence r.

**Comment by cges30901** [comment]
Thank you for your explanation! Now I know what to do.
