### ISSUE TITLE
Page.get_text("rawdict") not contains images

### ISSUE THREAD

**Issue by CarlosRCDev** [pymupdf/PyMuPDF#3171]
### Description of the bug

Older version of Pymupdf, for example pymupdf==1.19.2, contains images in blocks of page.get_text("rawdict").
New version pymupdf==1.23.22 not contains images, using page.get_images() find images, but i need read pdf in the same order that was created.
I am not using modified flags.
I read in documentation that this method should return images.
This method has changed?

### How to reproduce the bug

page.get_text("rawdict")

### PyMuPDF version

1.23.22

### Operating system

Linux

### Python version

3.12

**Comment by JorjMcKie** [comment]
Please provide a reproducing file. We cannot otherwise accept a bug report.
Just confirmed: "rawdict" option **_does_** extract images!

**Comment by JorjMcKie** [comment]
@CarlosRCDev just to make sure: my previous post says that `get_text("rawdict")` does indeed extract images.
So you must demonstrate your case by a failing example PDF - otherwise this issue cannot be accepted.

**Comment by JorjMcKie** [comment]
How important reproducing files are!

There **_was_** a change in between these versions:
Since some versions we only include objects (text or images) if **_(1) they are fully_** contained in the clip, where **_(2) the default clip_** is the page rectangle.

This image however is **_not_** fully contained in page.rect, although the part outside is very small here.

If you do not want to be bothered with this type of problem, extract like so:
```python
page.get_text("rawdict",clip=fitz.INFINITE_RECT())
```
The infinite rectangle makes sure that you always will get everything ...
