### ISSUE TITLE
Confidence Score while extracting Images or Tables

### ISSUE THREAD

**Issue by Curiosity007** [pymupdf/PyMuPDF#3303]
Right now, when I use find_tables or get_images functions, I don't think it has a threshold score, where I can restrict the output to only good images or tables. Right now, I am getting unnessary tables which are actually not tables. Is there a way to control the output?

**Comment by JorjMcKie** [comment]
I am not sure what you mean by a "good image" - please elaborate.

Otherwise, improving our table detection is part of our regular work and we have a long list of things we want to do here going forward.

But there no plans to implement anything like a quality score. After all you have all batteries on board for writing code that throws away unwanted table candidates. Among them are specifying a clip that restricts the page area to even consider for table detection.
