### ISSUE TITLE
page.searchFor return a strange rect

### ISSUE THREAD

**Issue by pluieciel** [pymupdf/PyMuPDF#336]
Hello team,

Thanks a lot for your work of a really helpful library!

I have some issue when addhighlight based on text, the "page.searchFor" returns a strange rect (like a line since y0 and y1 are very near). so some of the sentence is highlighted with a underline.
Could you please help me figure out why it is happening?

#my code:
text_instances = page.searchFor(text)
if text=='<Q>: And my final question has to do with SBS again and the acquisition Apak.':
      print(text_instances)
elif text=='So what we want to do is improve progressively.':
      print('*',text_instances)
#result:
strange: [Rect(96.0, **543.5599975585938**, 418.2300109863281, **543.469970703125**)]
normal: * [Rect(279.84002685546875, 338.4700012207031, 475.10003662109375, 351.80999755859375)]

**Comment by JorjMcKie** [comment]
Uhm, hard to say. I probably need the PDF to see what is happening.
There always is the risk that a PDF is somehow malformed ...
How do you know what should be "normal"?

**Comment by pluieciel** [comment]
Hi @JorjMcKie 
Thanks for your reply!
I have highlight the whole pdf, sentence by sentence to test. Normal is those highlighted correctly.
I found that all sentences begin with "\<Q\>" or "\<A\>" have that problem.
Does that mean "\<" need to be treated specially when I do page.searchFor(text)?

**Comment by JorjMcKie** [comment]
> Does that mean "<" need to be treated specially when I do page.searchFor(text)?

No, PyMuPDF wouldn't know anything of the text semantics.
But maybe these parts of the text come in a different **font** than the rest? I have seen issues which MuPDF has with some ill-defined fonts: in those cases MuPDF did not report the text height correctly (but zero instead).
My "own" text extraction parts do correct those situations - these are methods ``getText``, ``getTextWords`` annd ``getTextBlocks``.
How to confirm that this may be your case:
* Look at the rectangle heights in ``page.searchFor("<Q>")`` - are they zero?
* Create the list of lists ``page.getTextWords()``. Every item represents one word and has the format ``[x0, y0, x1, y1, word, bn, ln, wn]`` (bn, ln, wn = block, line, word number - can be ignored).

    - iterate through the items, if word == "<Q>" check the height of ``fitz.Rect(x0, y0, x1, y1)``. These should show the correct box for "<Q>".

**Comment by pluieciel** [comment]
Hi @JorjMcKie 
I've tried, here's the results:
**Situation1**:`page.getTextWords()`+iterate through the items
-`if i[4]=="<Q>:":print(i)`  
==(96.0, 235.47000122070312, 117.95999908447266, 249.41000366210938, '\<Q\>:', 18, 0, 0)  
\#_y0&y1 are ok_
**Situation2**:`page.searchFor("<Q>")`
==Rect(96.0, 235.55999755859375, 115.18000030517578, 249.41000366210938)  
\#_y0&y1 are ok_
**Situation3**:`page.searchFor("<Q>:")`
==Rect(96.0, 235.55999755859375, 117.95999908447266, 235.47000122070312)
\#_y0>y1_
**Situation4**:`page.searchFor("<Q>: Thank you.")`
==Rect(96.0, 235.55999755859375, 166.010009765625, 235.47000122070312)
\#_y0>y1_

Is that enough to figure out the reason? If not, I could send the pdf to help understand.
Thanks a lot in advance!

**Comment by JorjMcKie** [comment]
Seems that my suspicion is being confirmed, right?
So you do have a problem-PDF, where MuPDF (background SW behind searchFor) does not sufficiently support the font.
Unfortunatly, there is no easy way out.
* you could **underline** the text instead of **highlighting** it. That should also work with rectangles having a small height - just make sure the height is > 0 and the rectangle is **finite**.
* you could "rebuild" the text using [textbox extraction](https://pymupdf.readthedocs.io/en/latest/faq/#how-to-extract-text-from-within-a-rectangle), and determine the rectangle coordinates you want to underline by joining the single word rectangles yourself ... ufff!

* If you do ``page.getText("dict")`` you will get a dictionary with lots of information apart from the text itself. The rectangles ("bbox-es") therein should all be correct. Text in a line with the same font attributes is grouped in "spans" of text. Chances are, that you find what you search for always within a span. Then you could highlight the bbox of a span.

**Comment by pluieciel** [comment]
Sure, I think I will underline those \<Q\> sentences.
Thanks a lot for your help and for the great library ! 👍
