### ISSUE TITLE
addFreetextAnnot fill color disapears when annotation is moved by a user in open pdf

### ISSUE THREAD

**Issue by armenic** [pymupdf/PyMuPDF#347]
## Describe the bug (mandatory)
`addFreetextAnnot` fill color disapears when annotaiton is moved by a user in open pdf

## To Reproduce (mandatory)
```python
# the idea is to add DM.USUBJID annotation filled with blue color
# whenever there is "word 1" text.

import fitz
doc = fitz.open("word1.pdf")

# colors
# fill color
blue = [0, 0, 1]
# text color
black = (0, 0, 0)
border = {"width": 0.5}

# text to find
t = "word 1"

# text for annotation
ta = "DM.USUBJID"

# work with first page only
page = doc[0]

# get list of text locations
r1 = page.searchFor(t)

ra = fitz.Rect(72 + 40, 74, 103 + 120, 85)
anno = page.addFreetextAnnot(ra, ta, fontsize=6)

# this is necessary to overwrite the default flag 28
# which did not allow zoom of the anno
anno.setFlags(0)
anno.setBorder(border)
anno.update(fill_color=blue)

doc.save("word1_anno.pdf")
```

## Expected behavior (optional)
In `word1_anno.pdf` I left click on the free text annotation box and move. I expect the fill color to stay, but it disappears. It seems that the fill color property is not set when I am checking with the right click. Later is when I set it manually in the Acrobat Reader then moving the free text annotation box preserves the fill color as expected. Please see the animation below

## Screenshots (optional)
![free_text_fill_color](https://user-images.githubusercontent.com/7897325/63214966-93be1180-c0ed-11e9-9749-a36703c66e8a.gif)

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
![os](https://user-images.githubusercontent.com/7897325/63215000-0b8c3c00-c0ee-11e9-880c-6453bdecea35.png)

 - Python version, bitness
`Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32`

 - PyMuPDF version, installation method (wheel or source generated).
```
PyMuPDF 1.14.20: Python bindings for the MuPDF 1.14.0 library.
Version date: 2019-08-11 03:47:55.
Built for Python 3.7 on win32 (64-bit).
```

## Additional info
The `word1.pdf` as well as `word1_anno.pdf` are attached.
[word1.pdf](https://github.com/pymupdf/PyMuPDF/files/3512222/word1.pdf)
[word1_anno.pdf](https://github.com/pymupdf/PyMuPDF/files/3512224/word1_anno.pdf)

**Comment by JorjMcKie** [comment]
Hi,
this is a peculiarity of every PDF viewer / editor, unfortunately.
Adobe does it “wrong“, PDF-Xchange Viewer does it “right“, Nitro PDF Reader doesn't allow it at all (but supports it for its own free text annotations), etc.

If you use ``annot.setRect`` in PyMuPDF, it also works … but **do not use** ``annot.update`` in this case, or otherwise include all the original parameters of the annotation as well (fill color, rotate, etc.).

There are other examples for Adobe doing unexpected things: try and move some of the other annotations in [this](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/annotations/new-annots.pdf) example file for a demonstration.

The only advice I can give is to select the most compatible PDF editor ... there is nothing I can do about it.
Sorry about that!

**Comment by armenic** [comment]
Thank you very much @JorjMcKie,
I never realized that there are so much different standards for PDF. I tried your suggestion to programmatically move the annotation and it nicely preserved the fill color:
 `anno.setRect(ra + (5, 5, 5, 5))`

Thank you so much for this awesome package and excellent contributions!
