### ISSUE TITLE
Drawing reactangle to a list of words

### ISSUE THREAD

**Issue by Singrig** [pymupdf/PyMuPDF#350]
Hi I need to draw rectangle to list of words, where I'm able to do a single word but not to multiple words

pdf = fitz.open('abc.pdf')
Col = fitz.utils.getcolor("py_color")
page_count= pdf.pageCount

for z in range(0, page_count):
     Page2 = pdf[z]
     dl  = Page2.getDisplayList()
      tp = dl.getTextPage()
            for I, Val in enumerate (<list of words>):
                 rl = to.search(Val, quads = True)
                 for i in rl:
                       Page2.drawrect(i[0] color = col, fill = col, overlay = True)

pdf.save('abc2.pdf)

For above I'm getting error like "bad sequ. Length"

Is the above approach will be drawn rectangle to entire list of words or is any other way to do the same?

And sorry for there might be indent error bcoz I have typed from mobile.
Thanks in advance

**Comment by JorjMcKie** [comment]
You are returning quads, not rects from the search method.
When drawing, there is a difference between the two! Use ``drawQuad`` instead of ``drawRect``.

Background:

* ``drawRect`` leads to the highly efficient PDF operator ``re``
* ``drawQuad`` in contrast uses single lines to connect the corners (in effect a ``drawPolyline``)

In addition, I would use the analogous, same-named methods of the ``Shape`` class for this - mainly for performance reason and for a smaller output PDF.
The page methods internally do that, too, but repeatedly as many times as you use them. Each time, a new page ``/Contents`` object is written, and a ``Shape`` instance created and destroyed again.

Depending on your requirements, you may also consider using annotations instead. The new support in 1.14.20 will highlight (underline, strikout, squiggle) all found text in **one single statement** ... something like

```python
rl = page.searchFor(needle, hit_max=many, quads=True)
annot = page.addHighlightAnnot(rl)
annot.setColor(...)
annot.update()
# done
```

As you see, you also don't need to use ``DisplayList`` or ``TextPage`` yourself as long as you do not exploit their potential performance benefits.

**Comment by Singrig** [comment]
Thanks I'll try this, but while searching and using addHighlightAnnot i'm finding ups and downs it's logical but can we control it? Please find below example for more details,

I want a Highlight a word "SK" in entire PDF
When I use search and highlight it highlights "SK" along with it highlights other words containing "SK" like "Risk" it will highlights "sk" in "Risk" can we control this somehow?

**Comment by JorjMcKie** [comment]
I am again without a real operational internet, so putting this on my e-mail out basket and hope for the best:
The search function is directly based on MuPDF, so there is no way to modify its behavior (being case-insensitive).
But you could maybe search for your string enclosed in or prepended by spaces.
Or you could make a list of words on the page  - getTextWords() - (my own making). This list has an entry like “[x0, y0, x1, y1, ‘word’, n, n, n]” for each string delimited by white spaces. Then iterate through this list looking for entries like “SK?” or “?SK” or “SK” etc., and then use the rectangle defined by the 4 floats.


Von meinem iPhone gesendet

>

**Comment by JorjMcKie** [comment]
The drawbacks of ``page.getTextWords()``:

1. It does not recorgnize strings containing spaces, because it splits the text at exactly those
2. It will treat hyphenated words distributed across two lines as different words, e.g. ``"distri-"`` and ``"bution"``. But that's similar to the ``page.searchFor()`` method: it will neither find this occurrence if you let it look for ``"distribution"``

**Comment by JorjMcKie** [comment]
Are your questions answered for the moment?

**Comment by JorjMcKie** [comment]
Closing for lack of reaction.
Please come back with more questions any time.
