### ISSUE TITLE
Bug - metadata not found in the encrypted file

### ISSUE THREAD

**Issue by Matmaus** [pymupdf/PyMuPDF#359]
## Bug description
Since version 1.16.0, I have a problem with extracting metadata from files. It seems that problem is only with some encrypted files. In the older version 1.14.20 there were metadata present, but in the newer version they are not.

#### test.py:
```
#!/usr/bin/env python3

import json
import sys

import fitz as pymupdf


def main(filepath):
    doc = pymupdf.open(filepath)
    result = {}

    known_passwords = [
        '',
        '123',
        '1234',
        '12345',
        '123456',
        '1234567',
        '12345678',
    ]

    if doc.isEncrypted:
        result['encrypted'] = True
        for password in known_passwords:
            if doc.authenticate(password) != 0:
                break
        else:
            return result
    if doc.metadata:
        result['version'] = doc.metadata['format'][4:]
        result['metadata_title'] = doc.metadata['title']
        result['metadata_subject'] = doc.metadata['subject']
        result['metadata_keywords'] = doc.metadata['keywords']
        result['metadata_author'] = doc.metadata['author']
        result['metadata_modified_date'] = doc.metadata['modDate']
        result['metadata_creation_date'] = doc.metadata['creationDate']
        result['metadata_creator'] = doc.metadata['creator']
        result['metadata_producer'] = doc.metadata['producer']
    if doc.pageCount:
        result['first_page_text'] = doc.loadPage(0).getText('text')
        result['last_page_text'] = doc.loadPage(-1).getText('text')

    print(json.dumps(result, indent=4, sort_keys=True))


if __name__ == '__main__':
    main(sys.argv[1])
```
#### How to run:
To reproduce this problem you can run program above with following file [test.pdf](https://github.com/pymupdf/PyMuPDF/files/3595118/test.pdf)
```
$ python testy.py test.pdf
```

## Expected behavior
```
{
    "encrypted": true,
    "metadata_author": null,
    "metadata_creation_date": "D:20190522153402Z",
    "metadata_creator": "Aspose Ltd.",
    "metadata_keywords": null,
    "metadata_modified_date": "D:20190522173603+02'00'",
    "metadata_producer": "Aspose.Pdf for .NET 17.9",
    "metadata_subject": null,
    "metadata_title": null,
    "version": "1.5"
}
```

## Current behavior
```
mupdf: cannot recognize xref format
mupdf: corrupt object stream (11 0 R)
{
    "encrypted": true,
    "metadata_author": null,
    "metadata_creation_date": null,
    "metadata_creator": null,
    "metadata_keywords": null,
    "metadata_modified_date": null,
    "metadata_producer": null,
    "metadata_subject": null,
    "metadata_title": null,
    "version": "1.5"
}
```

## My configuration
 - 4.19.66-1-MANJARO
 - GCC 9.1.0
 - Python 3.7.4
 - PyMuPDF 1.16.1, PyPI.

**Comment by JorjMcKie** [comment]
This file definitely **is damaged:** neither Adobe Acrobat, SumatraPDF, Foxit Reader or PDF XChange Reader can open it. Some offer a password dialog before giving up others (Adobe) do not even try.

Opening with PyMuPDF **pre v1.16.0** only *seems* to work better, but look at its error log:
```python
>>> print(fitz.TOOLS.fitz_stderr)
error: cannot recognize xref format
warning: trying to repair broken xref
warning: repairing PDF document
warning: aes padding out of range
warning: ... repeated 4 times ...
warning: ignoring zlib error: incorrect header check
error: corrupt object stream (11 0 R)
warning: ignoring broken object stream (11 0 R)
warning: invalid string length for aes encryption
warning: ... repeated 2 times ...
warning: aes padding out of range

>>>
```

The handling in v1.16.x seems to be somewhat stricter, so that there is no attempt to decrypt the metadata after a desaster. But the two error messages are shown in Python ``sys.stderr`` as they should and the same warnings are there:
```python
>>> import fitz
>>> doc=fitz.open("test.pdf")
mupdf: cannot recognize xref format
mupdf: corrupt object stream (11 0 R)
>>> print(fitz.TOOLS.mupdf_warnings())
trying to repair broken xref
repairing PDF document
aes padding out of range
... repeated 4 times...
ignoring zlib error: incorrect header check
ignoring broken object stream (11 0 R)
invalid string length for aes encryption
>>> 
```

**Comment by JorjMcKie** [comment]
Actually the file is correctly decrypted and object have been recovered as much as possible. Look at this output made with PyMuPDF low level functions:
```python
>>> doc.authenticate("1234")
6
>>> xrefl = doc._getXrefLength()
>>> for xref in range(1, xrefl):
	print(xref, "0 obj")
	print(doc._getXrefString(xref))

	
1 0 obj
<<
  /CreationDate (D:20190522153402Z)
  /Creator (Aspose Ltd.)
  /ModDate (D:20190522173603+02'00')
  /PTEX.Fullbanner (This is pdfTeX, Version 3.14159265-2.6-1.40.18 \(TeX Live 2017\) kpathsea version 6.2.3)
  /Producer (Aspose.Pdf for .NET 17.9)
  /Trapped /False
>>
2 0 obj
<<
  /Type /XRef
  /Length 48
  /Filter /FlateDecode
  /DecodeParms <<
    /Columns 4
    /Predictor 12
  >>
  /W [ 1 2 1 ]
  /Size 3
  /ID [ <EA28DCD52A89F18A846420E4D9E328F3> <3C41AC78B3170F952C080B2DA1842555> ]
>>
3 0 obj
<<
  /Linearized 1
  /L 18378
  /H [ 700 125 ]
  /O 7
  /E 17849
  /N 1
  /T 18097
>>
4 0 obj
<<
  /Type /XRef
  /Length 80
  /Filter /FlateDecode
  /DecodeParms <<
    /Columns 4
    /Predictor 12
  >>
  /W [ 1 2 1 ]
  /Index [ 3 17 ]
  /Info 1 0 R
  /Root 5 0 R
  /Size 20
  /Prev 18098
  /ID [ <EA28DCD52A89F18A846420E4D9E328F3> <3C41AC78B3170F952C080B2DA1842555> ]
>>
5 0 obj
<<
  /Pages 15 0 R
  /Type /Catalog
  /Names 20 0 R
  /Metadata 22 0 R
>>
6 0 obj
<<
  /Filter /FlateDecode
  /S 36
  /Length 80
>>
7 0 obj
<<
  /Contents 8 0 R
  /MediaBox [ 0 0 595.276 841.89 ]
  /Parent 15 0 R
  /Resources 12 0 R
  /Type /Page
>>
8 0 obj
<<
  /Filter /FlateDecode
  /Length 144
>>
9 0 obj
<<
  /Filter /FlateDecode
  /Length1 1365
  /Length2 5943
  /Length3 0
  /Length 6912
>>
10 0 obj
<<
  /Filter /FlateDecode
  /Length1 1532
  /Length2 7947
  /Length3 0
  /Length 8992
>>
11 0 obj
<<
  /Type /ObjStm
  /Length 560
  /Filter /FlateDecode
  /N 8
  /First 54
>>
12 0 obj
null
13 0 obj
null
14 0 obj
null
15 0 obj
null
16 0 obj
null
17 0 obj
null
18 0 obj
null
19 0 obj
null
20 0 obj
<<
>>
21 0 obj
<<
  /Filter /Standard
  /UE <5C2652EADACF684F792741D82458BC67662A538495AE95467F6FDE622166F08A>
  /OE <4D074698D0A78932BBA5104A60A8ACA268E817190E3E9D9AF3B954A062A83974>
  /Perms <A24DCD4531832A847DB3A7018DFF9E51>
  /O <00F879724CD6EA8FFB20FDCC802D0219877F8F95C3D3C18549841836F6A2A9A2820162514B3886E4F0E7622B0E63103A>
  /U <A38CABC0AAC44B139C95089893BCA86FF3827C51257739657792B2F61DCA1FB11F641695F23811942F4722E153A5B631>
  /P -3904
  /R 5
  /V 5
  /Length 256
  /StmF /StdCF
  /StrF /StdCF
  /CF <<
    /StdCF <<
      /AuthEvent /DocOpen
      /CFM /AESV3
      /Length 32
    >>
  >>
>>
22 0 obj
<<
  /Length 256
  /Type /Metadata
  /Subtype /XML
>>
23 0 obj
<<
  /Root 5 0 R
  /Info 1 0 R
  /Encrypt 21 0 R
  /ID [ <EA28DCD52A89F18A846420E4D9E328F3> <3C41AC78B3170F952C080B2DA1842555> ]
  /Type /XRef
  /W [ 1 2 2 ]
  /Index [ 0 24 ]
  /Size 24
  /Length 120
>>
>>> doc.save("decrypted.pdf")  # trying to save shows that critical objects are missing
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    doc.save("decrypted.pdf")
  File "C:\Users\Harald\AppData\Local\Programs\Python\Python37\lib\site-packages\fitz\fitz.py", line 2780, in save
    raise ValueError("cannot save with zero pages")
ValueError: cannot save with zero pages
>>> # the PDF page tree could not be recovered, so that it appears to have 0 pages.
```
Strictly speaking, the metadata object (xref 1) is there and decrypted, but because of the faulty situation, the point to it is no longer accepted in v1.16.0:
MuPDF has created **a new trailer object** and is no longer using the old one which now appears under xref 23:
```python
>>> print(doc._getTrailerString())
<<
  /Size 24
  /Root 5 0 R
  /Encrypt 21 0 R
  /ID [ <EA28DCD52A89F18A846420E4D9E328F3> <3C41AC78B3170F952C080B2DA1842555> ]
>>
>>> 
```

**Comment by Matmaus** [comment]
Thank you for investigation.

Would it be possible to use previous approach and return as much data as possible even if file is corrupted? This approach could be specified by some parameter too.

I have another [file.pdf](https://github.com/pymupdf/PyMuPDF/files/3595523/test2.pdf). In this case even text is extracted successfully.

Expected output:
```
{
    "first_page_text": "empty-encrypted-pdf\n1\n",
    "last_page_text": "empty-encrypted-pdf\n1\n",
    "metadata_author": "matus",
    "metadata_creation_date": "D:20190522101945+02'00'",
    "metadata_creator": "Aspose Ltd.",
    "metadata_keywords": "PQcgm\u00f8nE\u017eR\u00a4\u00ebo\"n\u00ba",
    "metadata_modified_date": "D:20190522102601+02'00'",
    "metadata_producer": "Aspose.Pdf for .NET 17.9",
    "metadata_subject": "\u00a7L\u00be\u017ex \u02dc\u00a6\u00a72",
    "metadata_title": "empty-encrypted-pdf",
    "version": "1.5"
}
```

**Comment by JorjMcKie** [comment]
This very much depends on what data are still accessible. In your previous case, the file had a corrupted XREF table, which in addition was in that modern binary format. So, while object 1 was recognizable for human eyes, it was hard / impossible to identify a programmatic cure.

**Comment by JorjMcKie** [comment]
The new file announces not to be encrypted, otherwise similar damage:

```python
>>> import fitz
>>> doc=fitz.open("test2.pdf")
mupdf: cannot recognize xref format
>>> doc.needsPass
False
>>> len(doc)
1
>>> doc.save("test2-repaired.pdf", garbage=3)
mupdf: aes padding out of range: 67
>>> print(fitz.TOOLS.mupdf_warnings())
trying to repair broken xref
repairing PDF document
invalid string length for aes encryption
... repeated 2 times...
read error; treating as end of file
>>> 
```
I see no other way than trying to do a semi-manual, interactive repair similar to the one shown above. There are several more low level functions available to help you do that: have a look at https://pymupdf.readthedocs.io/en/latest/functions/.

You can also try and create a new PDF and then copy the old one into it using insertPDF. Depending on how successful this is, "manually" add objects and streams to the new one:
* ``doc._getXrefString(xref)`` delivers a complete object definition
* ''doc.isStream(xref)`` - indicates whether this is a stream object
* ``doc._getXrefStream(xref)`` delivers the stream content
* ``doc._getNewXref()`` creates a new empty xref
* ``doc._updateObject(xref, text)`` updates / fills an object definition into the xref
* ``doc._updateStream(xref, bytes, new=True/False)`` replaces / creates stream for an object
* ...

**Comment by Matmaus** [comment]
This solution is too much specific and I don't really want to fix those files. The reason is that I have too many files to process. Rather I would like to be able to extract as much data as possible, even from corrupted files. That means, I don't want to repair xref tables and files at all, but to extract everything possible.

**Comment by JorjMcKie** [comment]
Utterly understandable. However, damages can be arbitrary in their effect:

  *   The PDF may appear not to have pages at all (len(doc) == 0). In that case “insertPDF()” will not work. But image or font extraction iterating over xref numbers might still.
  *   The PDF may appear not to be encrypted – while de facto being so. Hopeless case.
  *   Maybe the metadata dictionary is recognizable by some heuristic approach: if some xref string contains any of those  typical keys (/Producer, /Author, …), take the string and parse its content.
  *   Maybe a good start in applicable cases is doing a “insertPDF()“ and enrich the result with other parseable data of the origin …

Jorj

________________________________
Von: Matmaus <notifications@github.com>
Gesendet: Tuesday, September 10, 2019 9:11:40 AM
An: pymupdf/PyMuPDF <PyMuPDF@noreply.github.com>
Cc: Jorj X. McKie <jorj.x.mckie@outlook.de>; Assign <assign@noreply.github.com>
Betreff: Re: [pymupdf/PyMuPDF] Bug - metadata not found in the encrypted file (#359)


This solution is too much specific and I don't really want to fix those files. The reason is that I have too many files to process. Rather I would like to be able to extract as much data as possible, even from corrupted files. That means, I don't want to repair xref tables and files at all, but to extract everything possible.

**Comment by Matmaus** [comment]
Ok, thank you for your explanation.

**Comment by JorjMcKie** [comment]
close the issue?
