### ISSUE TITLE
Lift an annotation from one page and add it to another

### ISSUE THREAD

**Issue by emarshz** [pymupdf/PyMuPDF#3719]
**Is your feature request related to a problem? Please describe.**
I am wanting to pull an annotation object from on page object and directly add that annotation object to a different page object. Currently, it appear I have to use a specific add annotation function in order to add the annotation object's contents. Is this correct or is there a way for me to simply lift an annotation object and directly add it into a different page. 

**Describe the solution you'd like**
I want there to be one function or workflow that would allow me to add the annotation object directly into the page without having to know what type of annotation it is

**Comment by emarshz** [comment]
Potentially, can you explain?

**Comment by JorjMcKie** [comment]
It is impossible to copy annotations between pages of different files - without going through the effort of adding an annotation on the target page by re-using the properties of an annotation on some target page.
Because annotation appearance is highly dependent on the tool, even that way will not lead to satisfactory results, e.g. PyMuPDF does not support all annotation properties that are supported by Adobe or Nitro, etc., and vice versa.

Some hacky way is imaginable to copy annotations between pages of the same PDF - by copy xref content on a low level.

**Comment by emarshz** [comment]
Okay I understand. Thank you for the explanation.
