### ISSUE TITLE
Could fill_textbox tolerance be optional?

### ISSUE THREAD

**Issue by damiankucharski** [pymupdf/PyMuPDF#3728]
I do not really see a purpose of this line, it seems a bit confusing to me and sometimes the default starting point is set outside of the rectangle that would otherwise fit the text inside. Maybe it could be a parameter with a default value? I do not thing documentation mentions that the texts does not start at the border of the rectangle specified...

https://github.com/pymupdf/PyMuPDF/blob/9717935eeb2d50d15440d62575878214226795f9/src/utils.py#L4546

**Comment by JorjMcKie** [comment]
This value controls the distance of the bottom-left point ("origin") of the first character in a line. The intention has been to make sure that the whole visible part of the character is inside the the rectangle.
Unfortunately (and unexpectedly at that time) it turned out that this is not always the case: some calligraphic fonts do not follow that rule, so portion of the first character still land to the left of the rectangle border.
It is not a big deal - simply enlarge the rectangle to the left somewhat.
