### ISSUE TITLE
apply_redactions hides Path objects from macOS Preview/Quicklook/Safari

### ISSUE THREAD

**Issue by mac5yver** [pymupdf/PyMuPDF#3748]
### Description of the bug

Path objects (paragraph rules, paragraph borders) in a PDF created by Adobe InDesign become hidden or invisible to macOS Preview, Safari, and Quicklook after applying redactions. 

Preview shows all the paths of '1 source.pdf' correctly but after redaction ('3 apply redactions.pdf') none of these Path objects are visible in Preview (see 'preview.png'). The content structure of both documents appear to be the same (see 'compare content.png'), but something seems to have changed as a result of redaction. The Paths render correctly in Acrobat and Chrome on macOS.

### How to reproduce the bug

I would expect that after applying redactions the Paths would continue to be visible in Preview/Quicklook but they are not.

```python
import pymupdf
doc = pymupdf.open("1 source.pdf")
for page in doc:
    page.add_redact_annot([0, 792, 612, 600])
    page.apply_redactions()
doc.save("3 apply redactions.pdf")
doc.close()
```

[1 source.pdf](https://github.com/user-attachments/files/16475543/1.source.pdf)
[2 redact rects.pdf](https://github.com/user-attachments/files/16475542/2.redact.rects.pdf)
[3 apply redactions.pdf](https://github.com/user-attachments/files/16475541/3.apply.redactions.pdf)

preview.png
![preview](https://github.com/user-attachments/assets/2512f65a-e94b-4b37-ae5e-cadc35c9c9e0)

compare content.png
![compare content](https://github.com/user-attachments/assets/59368fdb-bdef-4259-a652-1890682c2845)

### PyMuPDF version

1.24.9

### Operating system

MacOS

### Python version

3.12

**Comment by JorjMcKie** [comment]
Please consult the documentation of [apply_redactions](https://pymupdf.readthedocs.io/en/latest/page.html#Page.apply_redactions)!
Since several versions, drawings are also removed when overlapping redactions rectangles.
In addition, text, images and drawings can be handled independently from each other in redactions applications.
To keep drawings use parameter `graphics=pymupdf.PDF_REDACT_LINE_ART_NONE`.

**Comment by beeing** [comment]
Hi, I have similar issue. Just to clarify that the "text: 1" for apply_redactions is working properly, however the text was somehow masked or so. Refer to the image from Preview app which I can still select the text and copy it out.

The only thing is the text on the left section seems to be transparent.

![Untitled](https://github.com/user-attachments/assets/f08ff56f-5a6b-439b-be98-9e038d0c52ea)

Hope this helps. Thanks.

**Comment by mac5yver** [comment]
> Please consult the documentation of [apply_redactions](https://pymupdf.readthedocs.io/en/latest/page.html#Page.apply_redactions)! Since several versions, drawings are also removed when overlapping redactions rectangles. In addition, text, images and drawings can be handled independently from each other in redactions applications. To keep drawings use parameter `graphics=pymupdf.PDF_REDACT_LINE_ART_NONE`.

@JorjMcKie Thank you for the quick reply. I have tried the various graphics and image handling options in the apply redactions documentation, but the issue remains. Please note none of the redact rectangles overlap the path drawings that appear to be removed. (see original post attachment [2 redact rects.pdf](https://github.com/user-attachments/files/16475542/2.redact.rects.pdf))

Our use-case requires that we do remove _overlapping_ text, images, and drawings.

The issue remains in these new example files created with this code:
[1 source.pdf](https://github.com/user-attachments/files/16495735/1.source.pdf)
[3 PDF_REDACT_LINE_ART_NONE.pdf](https://github.com/user-attachments/files/16495736/3.PDF_REDACT_LINE_ART_NONE.pdf)

```python
import pymupdf

doc = pymupdf.open("1 source.pdf")

for page in doc:
    page.add_redact_annot([0, 792, 612, 600])
    page.apply_redactions(graphics=pymupdf.PDF_REDACT_LINE_ART_NONE)

doc.save("3 PDF_REDACT_LINE_ART_NONE.pdf")
doc.close()

```
![redact_rects and apply_redactions](https://github.com/user-attachments/assets/64668c0f-48f5-42d6-835a-4d6dddb43407)

**Comment by JorjMcKie** [comment]
@beeing please open a separate issue - your situation is not the same.

**Comment by JorjMcKie** [comment]
@mac5yver - thanks for your reply. I have opened the redacted (result) file with all the PDF viewers I usually employ - and it does look perfectly ok with all of them: evince (Linux), Adobe Acrobat, PDF XChange Viwer, Nitro, Foxit reader, MuPDF.
So there is no can-do for me - especially considering that Adobe Acrobat is among them.

**Comment by mac5yver** [comment]
@JorjMcKie Thanks for your time. We regularly employ macOS Preview as a PDF viewer, but do also have access to Acrobat. We'll just have to find a way to ensure the redacted PDFs are never opened or printed from Preview or Safari, since the apparent result is incorrect.

**Comment by beeing** [comment]
> @beeing please open a separate issue - your situation is not the same.

Sure, I've created in #3751. Thank you!

**Comment by yuhuang-cst** [comment]
> @mac5yver - thanks for your reply. I have opened the redacted (result) file with all the PDF viewers I usually employ - and it does look perfectly ok with all of them: evince (Linux), Adobe Acrobat, PDF XChange Viwer, Nitro, Foxit reader, MuPDF. So there is no can-do for me - especially considering that Adobe Acrobat is among them.

I encountered a similar issue with the newly generated PDF files after using the apply_redactions function,. PDF readers that display the file correctly include Adobe Acrobat Reader, Chrome, and WPS. Those that display it incorrectly include **Mac Preview, Safari, UPDF, and PDF Expert**. If you open the file `3 apply redactions.pdf 3 apply edactions.pdf` provided in this issue with the aforementioned PDF readers, you can verify this. Please take this issue seriously as this is likely caused by some wrong changes made by `apply_redactions`, and it affects more than just the Mac Preview PDF reader.

**Comment by yuhuang-cst** [comment]
> @mac5yver - thanks for your reply. I have opened the redacted (result) file with all the PDF viewers I usually employ - and it does look perfectly ok with all of them: evince (Linux), Adobe Acrobat, PDF XChange Viwer, Nitro, Foxit reader, MuPDF. So there is no can-do for me - especially considering that Adobe Acrobat is among them.

I encountered a similar issue with the newly generated PDF files after using the `apply_redactions` function,. PDF readers that display the file correctly include Adobe Acrobat Reader, Chrome, and WPS. Those that display it incorrectly include **Mac Preview, Safari, UPDF, and PDF Expert**. If you open the file 3 apply redactions.pdf 3 apply edactions.pdf provided in this issue with the aforementioned PDF readers, you can verify this. Please take this issue seriously as this is likely caused by some wrong changes made by `apply_redactions`, and it affects more than just the Mac Preview PDF reader.

**Comment by jamie-lemon** [comment]
@yuhuang-cst Agree that this "PDF doesn't display correctly in Preview after redactions take place" is a serious issue - we will hopefully get to the bottom of it on https://github.com/pymupdf/PyMuPDF/issues/3751
