### ISSUE TITLE
test_bboxlog_2885 fails with (lib)mupdf 1.24.9

### ISSUE THREAD

**Issue by Antiz96** [pymupdf/PyMuPDF#3830]
### Description of the bug

Hello,

When building PyMuPDF 1.24.9 against [(lib)MuPDF 1.24.9](https://github.com/ArtifexSoftware/mupdf/releases/tag/1.24.9), the `test_bboxlog_2885` test fails (see [check logs](https://gist.githubusercontent.com/Antiz96/2b6e454dc1f9b3f365dc85879539bb29/raw/a42ffb924ada13a1ef853120ce58ff368d9321ed/Check%2520logs)).
This test passes fine when building against (lib)MuPDF 1.24.8

### How to reproduce the bug

Build PyMuPDF 1.24.9 against MuPDF 1.24.9, run tests suite, see test_bboxlog_2885 failing.

I remain available if needed :)

### PyMuPDF version

1.24.9

### Operating system

Linux

### Python version

3.12

**Comment by julian-smith-artifex-com** [comment]
Actually this is fixed in latest PyMuPDF git.

In general, existing releases of PyMuPDF are not expected to pass all tests with newer MuPDF releases. I.e. PyMuPDF-1.24.9 is only expected to pass tests wit its hard-coded MuPDF-1.24.8.

We'll be making a new release PyMuPDF-1.24.10 in the next few days, which will come with MuPDF-1.24.9.

Hope that makes sense.

**Comment by Antiz96** [comment]
Thanks for the quick answer, makes sense. 
I'll wait for PyMuPDF-1.24.10 to be released then :)

**Comment by julian-smith-artifex-com** [comment]
Great, in that case i'll close this issue.
