### ISSUE TITLE
Image got upside down after extracting, it didn't contain exif data to know the picture's orientation

### ISSUE THREAD

**Issue by apache135** [pymupdf/PyMuPDF#385]
when I extract image via this package, I got an upside down image althought it was in normal direction on the pdf.I have 3 questions as follow:
1.I have tried rotate the page, it still kept the same. what would be the reason?
2.Parsing the image data, the exif property is None,  Could you tell me how to get the image orientation?
3.Via the interface, Could I get the image absolute coordinates, instead of the relative coordinates? my image is in the middle of the document, however I got the coordinates is (0,0,height, width).

Could you give me some hits to help me out? Thanks very much.

**Comment by JorjMcKie** [comment]
Hard to answer without more information:

* how did you extract the image ``fitz.Pixmap(doc, xref)`` or ``doc.extractImage(xref)`` or via ``page.getText("dict")``?
* to find the image rectangle on the page, you can use ``page.getImageBbox(item)`` where item is one of the ``pge.getImageList()``
* An example PDF would help me track the issue
* and of course your installation data, best ``print(fitz.__doc__)``

It may well be that we cannot find a programmatic way at all:
You may know that the ``page.insertImage`` method has a "rotate" parameter. Later extracting this  image would not betray what had been done to incorporate it in the PDF - except we find and parse the PDF command implementing this rotation ... tedious!

**Comment by apache135** [comment]
Thank you for your immediate reply. 
extract the image via fitz.pixmap(doc, xref), could't  get the image exif property. 
 The PDF is  encrypted , so I will find a similar PDF and send u.

By the way, is the image orientation  info related with the pdf file production methods？ for example ,create it via Microsoft excel , pdf  interface etc.

**Comment by JorjMcKie** [comment]
> extract the image via fitz.pixmap(doc, xref), could't get the image exif property.

This is of course impossible with that method. Try ``doc.extractImage(xref)`` instead. This returns (with some **_"luck"_**) the original binary of the image, wich should also contain the original EXIF data where present.

**Comment by JorjMcKie** [comment]
> By the way, is the image orientation info related with the pdf file production methods？ for example ,create it via Microsoft excel , pdf interface etc.

No, not to my knowledge. However, as I wrote in previous post: the PDF creator (software or person) may decide to specify some arbitrary rotation on image insert. This would then not be detectable by inspecting the binary image stream. It would, nevertheless, in principle be possible to parse the respective PDF command and find that out.

My ``page.getImageBbox`` method actually is already something in that direction - but not completely there.

**Comment by JorjMcKie** [comment]
Please tell me if your inquiry is still relevant. Otherwise we can close the issue.

Because I have code which is close to answering questions similar to yours, I made a demo script which - under not too unfortunate conditions - should be able to detect, whether a PDF image has been inserted **rotated**. Restrictions are, that this script version can only detect rotation angles which are integer multiples of 90 degrees. It would however be easy to also detect mirroring (flipping upside-down or left-right).
Here is the script and a test PDF with the same image inserted in 8 different ways (4 different angles, each with either keeping or ignoring the aspect ratio). The script output looks like this:

```
python rot-detector.py t.pdf

Matrix(150.0, 0.0, 0.0, 171.1845, 50.0, 531.4077)
Page 0, image 'fzImg0', rotation: 0 deg.

Matrix(0.0, 131.4371, -150.0, 0.0, 200.0, 551.2814)
Page 1, image 'fzImg0', rotation: 90 deg.

Matrix(-150.0, 0.0, -0.0, -171.1845, 200.0, 702.5923)
Page 2, image 'fzImg0', rotation: 180 deg.

Matrix(-0.0, -131.4371, 150.0, -0.0, 50.0, 682.7186)
Page 3, image 'fzImg0', rotation: -90 deg.

Matrix(150.0, 0.0, 0.0, 250.0, 50.0, 492.0)
Page 4, image 'fzImg0', rotation: 0 deg.

Matrix(0.0, 250.0, -150.0, 0.0, 200.0, 492.0)
Page 5, image 'fzImg0', rotation: 90 deg.

Matrix(-150.0, 0.0, -0.0, -250.0, 200.0, 742.0)
Page 6, image 'fzImg0', rotation: 180 deg.

Matrix(-0.0, -250.0, 150.0, -0.0, 50.0, 742.0)
Page 7, image 'fzImg0', rotation: -90 deg.
```
The printed matrix just serves as documentation. Only the **sign** of the first 4 coordinates of them is used to determine the rotation angle. The matrix **values** themselves may however be used to find out whether the image aspect ratio has been changed - by comparing them with the original image width / height.

[rot-detector.zip](https://github.com/pymupdf/PyMuPDF/files/3750591/rot-detector.zip)

**Comment by apache135** [comment]
Sorry to reply so late . It is really a great method to get the rotate information, I can get the rotate degree via it. Thanks very much. 

When I test another pdf file, a problem appeared. The file has 5 image, 2 of them have same name, pdf plumber can extract 5 images, fitz return 4 images, sorry for that I can’t upload the original file, could you give me some advice for troubleshooting?

**Comment by apache135** [comment]
The function returns list has no duplicate entries, if possible, how to return all the images on the page no matter the name is same

**Comment by JorjMcKie** [comment]
The list produced by ``doc.getPageImageList(pno)`` is actually simply returning a Python list for a certain PDF array it finds in the page's ``/Resources`` object. Example for this repo's documentation page 0:

```python
import fitz
>>> doc=fitz.open("PyMuPDF.pdf")
>>> print(doc._getXrefString(doc[0].xref))  # object definition page 0
<<
  /Type /Page
  /Contents 278 0 R
  /Resources 277 0 R  # pointer to the resources object
  /MediaBox [ 0 0 612 792 ]
  /Parent 282 0 R
>>
>>> print(doc._getXrefString(277))  # print resources object
<<
  /Font <<
    /F38 280 0 R
    /F39 281 0 R
  >>
  /XObject <<
    /Im1 273 0 R  # this is a pointer to an image, Im1 must obviously be unique!
  >>
  /ProcSet [ /PDF /Text /ImageC ]
>>
>>> print(doc.getPageImageList(0))  # short form for all the above:
[(273, 0, 261, 115, 8, 'DeviceRGB', '', 'Im1', 'DCTDecode')]
>>> 
```

1. No check is made as to whether the page actually contains a display command for each entry in that array. So you may see entries in the list, but not the corresponding image in any viewer!
2. The real world can be even more complicated: Resources may point to ``/XObject`` objects, which are no images, but so-called "Form XObjects", which have their own ``/Resources`` object and which may in turn point to yet other images ...
    * The method ``doc.getPageImageList(pno)`` recursively loops through all these and returns a combined list.
    * This is the only way you might see **duplicate xrefs** or **duplicate reference names** (like 'Im1' above), but **never** duplicates for the combined (xref, 'Im1') - those are unique!
    * So the same image (identical xref) may be referenced multiple times, but with different reference names. Absolutely no issue here.
    * The same reference name may point to different images (and hence different xrefs), but this can only occur if that name occurs in different, stacked ``/Resources`` objects as described before. The little script I sent you **has a weakness** here: When I find ``"Im1"`` I will stop searching. But I should check whether this "Im1" also points to the right xref ... I will correct this when I find the time.

3. Another complication is this: A page may define an **_embedded_** image. Those do not show up anywhere else - only this page knows about them, and they will not be seen in ``doc.getPageImageList(pno)``. But they do appear as image blocks in ``page.getText("dict")``, together with all other images, which the page **actually** displays. So the list of image blocks of this method and ``page.getImageList()`` are two different things. They often refer to the same set of images, but in general they are not subsets of each other.

**Comment by apache135** [comment]
I am trying this  method.  Another issue happened. I save the image as png format using the data extracted by  doc.extractimage(xref)[‘image’] via pil , most of the image seemed shrinking. It only displays part of the original image on the pdf.
 Sorry for the encrypted file,If possible,I will find a similar file to upload.

**Comment by JorjMcKie** [comment]
> I am trying this method.

If you do, you should know, that no relation to xrefs and similar is possible: It is a method which works for all document types, not just PDFs.

> Another issue happened. I save the image as png format using the data extracted by doc.extractimage(xref)[‘image’] via pil , most of the image seemed shrinking. It only displays part of the original image on the pdf.

Impossible to tell the reason here without having any data at hand.

**Comment by apache135** [comment]
The issue which is extract part of the image is solve. The image is formed by 3 part which displays like only one image.
  Thanks for your help. I will close this ticket

**Comment by zweissman** [comment]
I was looking at a similar issue and tried running your rot-detector.py script. There are a bunch of underscore methods that don't seem to exist in v 1.18.12 like
page._cleanContents()
doc._getXrefStream()
doc._getPageInfo()

Are there updates for these?

**Comment by JorjMcKie** [comment]
There exist updates on this topic indeed:
If you do `bbox, transform = page.get_imagebbox(item, transform=True)`, then `transform` is the matrix which transforms the original image rectangle such that it fits into the bbox on the page. See documentation [here](https://pymupdf.readthedocs.io/en/latest/page.html#Page.get_image_bbox) and [here](https://pymupdf.readthedocs.io/en/latest/app4.html#imagetransformation).
With this information you can analyze the situation.

As per some renamings which took place, there exists [this](https://pymupdf.readthedocs.io/en/latest/znames.html) overview.
The examples you named were very early internal names (that's why there was the underscore), which had received "official" names quite some time ago. Their final new names are:
* `page._cleanContents()` ==> `page.clean_contents()`
* `doc._getXrefStream()` ==> `doc.xref_stream()`
* `doc._getPageInfo()` ==> `doc.get_page_images()`, `doc.get_page_fonts`, `doc.get_page_xobjects()`

**Comment by zweissman** [comment]
FYI: I am using 
I am currently using this to get my image dictionaries per a previous suggestion you made to be able to get the image and bbox info in one call.

`[b for b in doc[page_number].get_text("dict")["blocks"] if b["type"] == 1]`

Per the Image Transformation Matrix docs https://pymupdf.readthedocs.io/en/latest/app4.html#imagetransformation - it looks like I should be able to get the transformation matrix back with Page.get_text() along with Page.get_image_bbox(). The docs show an optional transform=True for get_image_bbox() but not for get_text(). Is that accurate?

**Comment by JorjMcKie** [comment]
>  not for get_text(). Is that accurate?

Yes, correct. I felt that method is parameter-loaded already.
But there are more options:
* `page.get_image_info()`: this is an enriched subset of `page.get_text()`. It delivers all information of all page images. Each image with bbox and transformation information, and as many times as the image occurs (maybe be multiple). Also **_all_** images, even if there is no xref for it. Optionally, the xref can be included if any is found, plus a MD5 hashcode to identify image duplicates. The only thing not included is the binary image content itself.
* `page.image_rects()`: similar to `page.image_bbox()`. But the return is a list of (Rect, Matrix) tuples for each (potentially multiple) occurrences of an image on the page.

**Comment by zweissman** [comment]
Sorry, I did not notice that there was a `transform` key in the dictionary. I see that now. 

Again, looking at the documentation for Transformation Matrix https://pymupdf.readthedocs.io/en/latest/app4.html#imagetransformation -  I see the code sample below. The last statement, you do `shrink * transform` to get a 6-valued Matrix. From which you then deduce that the scale factor is 0.4 and the image is rotated 90 degrees anti-clockwise.

What are the six values in that matrix?

```
>>> imginfo = page.get_images()[0]  # get an image item on a page
>>> imginfo
(5, 0, 439, 501, 8, 'DeviceRGB', '', 'fzImg0', 'DCTDecode')
>>> #------------------------------------------------
>>> # define image shrink matrix and rectangle
>>> #------------------------------------------------
>>> shrink = fitz.Matrix(1 / 439, 0, 0, 1 / 501, 0, 0)
>>> imgrect = fitz.Rect(0, 0, 439, 501)
>>> #------------------------------------------------
>>> # determine image bbox and transformation matrix:
>>> #------------------------------------------------
>>> bbox, transform = page.get_image_bbox("fzImg0", transform=True)
>>> #------------------------------------------------
>>> # confirm equality - permitting rounding errors
>>> #------------------------------------------------
>>> bbox
Rect(100.0, 112.37525939941406, 300.0, 287.624755859375)
>>> imgrect * shrink * transform
Rect(100.0, 112.375244140625, 300.0, 287.6247253417969)
>>> #------------------------------------------------
>>> shrink * transform
Matrix(0.0, -0.39920157194137573, 0.3992016017436981, 0.0, 100.0, 287.6247253417969)
>>> #------------------------------------------------
>>> # the above shows:
>>> # image sides scaled by same factor 0.4
>>> # image rotated by 90 degrees anti-clockwise
>>> #------------------------------------------------
```

I did find this code in your rot-detector.py file to explain the rotation.
```
        if min(matrix.a, matrix.d) > 0 and matrix.b == matrix.c == 0:
            rot = "0 deg"
        elif matrix.a == matrix.d == 0:
            if matrix.b > 0 and matrix.c < 0:
                rot = "90 deg"
            elif matrix.b < 0 and matrix.c > 0:
                rot = "-90 deg"
            else:
                rot = "unknown"
        elif min(matrix.a, matrix.d) < 0 and matrix.b == matrix.c == 0:
            rot = "180 deg"
        else:
            rot = "unknown"
```

And in the case of the images in my sample pdf https://pr-ie-training.s3.amazonaws.com/ES2381498A1.pdf it does show the images on 1-9 as "0 deg" and the images on page 10-13 as "180 deg". But mine are not only rotated but mirrored.

The image dictionary looks like this:
```
{
  'number': 1,
  'type': 1,
  'bbox': (99.27999877929688, 83.5418701171875, 510.3745422363281, 656.2353515625),
  'width': 601,
  'height': 842,
  'ext': 'png',
  'colorspace': 1,
  'xres': 96,
  'yres': 96,
  'bpc': 8,
  'transform': (411.09454345703125, 0.0, -0.0, -572.6934814453125, 99.27999877929688, 656.2353515625),
  'size': 76929
}
```

In one of your previous response, you wrote `"It would however be easy to also detect mirroring (flipping upside-down or left-right)."` 

I'm afraid that "easy" is relative. Any suggestions?

**Comment by JorjMcKie** [comment]
Have you read the Matrix chapter of PyMuPDF's documentation?
When I wrote this, I tried my best (at that time) to explain the meaning and the effect of every single value of the six values a, b, c, d, e, f. But let's nevertheless have a look at your special case:

`(411.09454345703125, 0.0, -0.0, -572.6934814453125, 99.27999877929688, 656.2353515625)`

* The last 2 floats, 99.28 and 656.235 are the (x, y) position of the image on the page in PDF space. The latter means that y is measured from ground upwards, because in PDF (0,0) is the bottom-left point of the page, and in MuPDF it is top-left.
* Values b and c are both 0, so no rotation took place (except potential integer multiples of 180°). Look at an example rotation matrix for 30°: `fitz.Matrix(30) = fitz.Matrix(0.866025403784, 0.5, -0.5, 0.866025403784, 0.0, 0.0)`. A pure rotation (does nothing except rotate) is always (cos, sin, -sin, cos, 0, 0).
* The absolute values of a and d take care of scaling the x-, resp. y-dimension of something. Now look at the negative sign of d, which means the y-dimension has changed its direction! Compare this with the 4 rotation matrices of 90°-multiples:

```python
>>> fitz.Matrix(0)
Matrix(1.0, 0.0, -0.0, 1.0, 0.0, 0.0)
>>> fitz.Matrix(90)
Matrix(0.0, 1.0, -1.0, 0.0, 0.0, 0.0)
>>> fitz.Matrix(180)
Matrix(-1.0, 0.0, -0.0, -1.0, 0.0, 0.0)
>>> fitz.Matrix(270)
Matrix(-0.0, -1.0, 1.0, -0.0, 0.0, 0.0)
>>> 
```
This proves there has not been any rotation at all, because in that case a and d would have the same sign. We indeed have an up-down flip.
It should now be obvious, that a left-right flip would happen if a < 0 and d > 0.

Please do not hesitate to ask if anything remained unclear ...

**Comment by zweissman** [comment]
I did not see the Matrix page, that was very helpful. https://pymupdf.readthedocs.io/en/latest/matrix.html

This is really testing my memory of discrete math and matrix manipulations. But thank you for the assistance.

Am I right to assume the following? (addition of the bottom two if conditions checking matrix.a and matrix.d being positive or negative:
```
        if min(matrix.a, matrix.d) > 0 and matrix.b == matrix.c == 0:
            rotation = 0
        elif matrix.a == matrix.d == 0:
            if matrix.b > 0 and matrix.c < 0:
                rotation = 90
            elif matrix.b < 0 and matrix.c > 0:
                rotation = -90
        elif min(matrix.a, matrix.d) < 0 and matrix.b == matrix.c == 0:
            rotation = 180
            if matrix.a < 0:
                flip = True     # rotate horizontal
            if matrix.d < 0:
                mirror = True   # rotate vertical
```

That works in my example case where matrix.d < 0, but I haven't found any other horizontal flipped or horizontal and vertical flipped images to test.

**Comment by JorjMcKie** [comment]
Matrix components a through f may of course take on any value. Some one must be aware that any of the checks above only pertains to the cases: (1) rotation by a multiple of 90°, (2) horizontal or vertical flip. Anything else like arbitrary rotation angles or shearing will be ignored.
The other thing is: what do we want to do with the check result? If just a human readable display - fine.
If we want to regain the original image, then a simple calculation of the transformation's inverse would be more adequate.

Back to checking out the cases. I am trying to unravel from a different starting point ... hope I covered all cases.

```python
vflip = hflip = error = False
rotation = 0
if m.b == m.c == 0:  # means rotation by 0, 180 or flippings
    if m.a * m.d > 0:  # same sign -> no flippings 
        if m.a < 0:  # so both, a and d are negative!
            rotation = 180
        else:
            rotation = 0
    else:  # we have a flip
        if m.a < 0:  # horizontal flip
            hflip = True
        else:
            vflip = True
elif:  # rotation by 90 or 270
    if m.b > 0:
        rotation = 90
    else:
        rotation = 270
else:
    error = True

if error:
    print("unsupported matrix")
elif vflip == hflip == False:
    print("rotation by %i" rotation)
elif vflip:
    print("up-down flip")
else:
    print("left-right flip")
```

**Comment by zweissman** [comment]
Thanks for spelling that all out explicitly. Just a note, in case others want to use this code in the future, you have an elif in there that doesn't have a conditional.

Is it not possible to have a vflip or hflip AND a rotation?

Also, you wrote "If we want to regain the original image, then a simple calculation of the transformation's inverse would be more adequate." Again, my discrete math skills are minimal at best. I am going to assume that you saying this means that there is probably a way for you to just call some function that will handle the transformation for me instead of what I am doing and sending it over to opencv for further processing. Fingers crossed that is what you are going to say :)

**Comment by zweissman** [comment]
That looks to work in all of my test cases so far.

Also, you wrote "If we want to regain the original image, then a simple calculation of the transformation's inverse would be more adequate." Again, my discrete math skills are minimal at best. I am going to assume that you saying this means that there is probably a way for you to just call some function that will handle the transformation for me instead of what I am doing and sending it over to opencv for further processing. Fingers crossed that is what you are going to say :)

**Comment by JorjMcKie** [comment]
Sorry if I sounded a little mysterious here. What I simply meant is this:
There is this equation:
`bbox = imgrect * shrink * transform`
in the explanation of the docu you quoted. So, using Linear Algebra, we can deduct this equation (the ~ operator computes a matrix inverse):
`bbox * ~transform * ~shrink = imgrect`
Which means, we can construct the image's original rectangle from the data we have in the extraction info.
I am not sure how you do this, but the matrix `~transform * ~shrink` should be the one to use ...

**Comment by JorjMcKie** [comment]
> should be the one to use ...

Well I forgot to add: you will probably want to set the e and f component of that matrix to zero ...

**Comment by zweissman** [comment]
Ok, I just used the snippet above to feed into this function.

```
def rotate_image(image, rotation, mirror=False, flip=False):
    # rotation: number of degrees to rotate around the center of the image.
    # mirror: flip on the vertical axis
    # flip: flip on the horizontal axis

    if rotation == 0 and not mirror and not flip:
        return image

    if rotation != 0:
        # Remember: cv2 shows image shape (height, width, color depth)
        height, width = image.shape[0], image.shape[1]

        center = (width / 2, height / 2)
        scale = 1.0

        # Perform the rotation
        rotation_matrix = cv2.getRotationMatrix2D(center, rotation, scale)
        image = cv2.warpAffine(image, rotation_matrix, (width, height))

        if mirror or flip:
            if mirror and flip:
                flip_param = -1     # flip horizontal and vertical
            elif mirror:
                flip_param = 1      # flip vertical
            else:
                flip_param = 0      # flip horizontal

            image = cv2.flip(image, flip_param)

    return image
```

**Comment by serhii-brovarnyk** [comment]
@JorjMcKie Hello!
Can you please help me understand what is wrong in my case?
Generally, image extraction and related matrix + bbox extraction work like a charm for most cases but in this one (unfortunately, I cannot provide you with a related PDF document) I have an unsupported matrix according to your code snippet.
The bbox and matrix look like: 
(Rect(2873.48388671875, 36.491943359375, 2925.290283203125, 396.491943359375),
  Matrix(0.0, -360.0, -51.806400299072266, -0.0, 2925.290283203125, 396.491943359375))
Image width: 1499
Image height: 215

As far as I understand, there is a -90 degree rotation of the image without flipping. But for the original document, I see rotation and upside-down flipping. There is also no EXIF data that I can extract from the image (I`m using fitz.Document.extract_image(xref) method. Also I`ve tried it with fitz.Pixmap(doc, xref) too.)

Can you point out for me how I can get info on whether the image is flipped or not?

Thank you in advance!

P.S.
PyMuPDF 1.25.3: Python bindings for the MuPDF 1.25.4 library (rebased implementation).
Python 3.10 running on linux (64-bit)
