### ISSUE TITLE
I am getting an error while using this library and some of the images are saving in complete black color

### ISSUE THREAD

**Issue by reddimohan** [pymupdf/PyMuPDF#386]
## getting an error (unsupported colorspace for 'JPEG') and some images are completely black
I have two pdf files, I am able to get all the images (saving as PNG) from one pdf file succesfully without any issues. The problem is with the second file facing 2 problems
1. Getting an error while saving the images, error mentioned below
> unsupported colorspace for 'png'
2. Able to save some of the images from the second pdf but all of them are completely black

## To Reproduce
- Install the required packages
- Code can be found here - https://gist.github.com/reddimohan/7a8fb29b7bcfb597a963f0c309fb0a31
- PDF file can be downloaded from here https://we.tl/t-S8dqyiJeZn

## Expected behavior
Script should extract all images present in the pdf file without any error

## My configuration
 - Ubuntu 18.xx
 - Python 3.7.4 - using Anaconda
 - PyMuPDF 1.16.5: Python bindings for the MuPDF 1.16.0 library.
   Version date: 2019-10-13 22:50:03.
   Built for Python 3.7 on linux (64-bit).
 - used `pip` to install the lib

>  print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] 
 linux 
 PyMuPDF 1.16.5: Python bindings for the MuPDF 1.16.0 library.
 Version date: 2019-10-13 22:50:03.
 Built for Python 3.7 on linux (64-bit).

**Comment by JorjMcKie** [comment]
A few observations:
* you are using a demo script which has been developed quite some time ago for an early version of PyMuPDF - presumably v1.9.x or earlier.
* you must use a compatible PyMuPDF version to continue using it.
* for the current PyMuPDF v1.16.5, you must use a compatible script like [extract-imga.py](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/extract-imga.py), at least as going-in position.
* if you use the script named in previous point, you can set some parameters to force extraction of **all** the "unworthy" images (ones which are too small in some respect).
* the current image extractor demo uses native extraction of the image binary stream whenever it can: it will try to avoid using pixmaps. This will also deliver the original image extension (like "jpeg") instead of always producing PNGs.
* this version also understands how to handle "masked" images - which does not happen in the version you are using. Those are at least some of the cases you see coming out as black.

**Comment by JorjMcKie** [comment]
Closing this issue for now. Please open a new question issue if you need further help.

**Comment by JorjMcKie** [comment]
I think I finally understood, what your real intention was:
You probably wanted to remove those pesky watermarks, so your PDF would be shown without this shady gray copy protection text ... right?
This can be done with PyMuPDF! I just tried it out.
If you are interested, directly e-mail me: jorj.x.mckie@outlook.de.
[chemic-no-watermarks.pdf](https://github.com/pymupdf/PyMuPDF/files/3775747/chemic-no-watermarks.pdf)

**Comment by sreekaransrinath** [comment]
> * for the current PyMuPDF v1.16.5, you must use a compatible script like [extract-imga.py](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/extract-imga.py), at least as going-in position.

This link is broken @JorjMcKie - what's the current solution?

**Comment by JorjMcKie** [comment]
This is the folder: https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/examples
