### ISSUE TITLE
Fails to parse value (/V) from a form text field 

### ISSUE THREAD

**Issue by y27choi** [pymupdf/PyMuPDF#3902]
### Description of the bug

I'm parsing a digitally filled form using PyMuPDF (v1.24.10) and it fails to retrieve the value from a text field. 

example:

<img width="412" alt="image" src="https://github.com/user-attachments/assets/c47d039e-4e51-4f54-a8ef-1407ec299c6b">

from pdf file:
```
43 0 obj
<< /FT /Tx /TU (Dealership Name:) /F 4 /Subtype /Widget /DV () /DA (//Helvetica 8 Tf 0 g)
/Type /Annot /Border [ 0 0 1 ] /Rect [ 136.4 624.23 381.52 634.23 ] /M (D:20211013223400Z00'00')
/MK << >> /AP << /N 427 0 R >> /T (Dealership Name) /Ff 4096 /V (Subaru of Glendale\012\012)
>>
endobj
```

from `doc.xref_object(...)`
```
<</Type/Annot/Subtype/Widget/Ff 4096/TU(Dealership Name:)/BS<</S/S/W 1>>/Rect[136.4 624.23 381.52 634.23]/T(Dealership Name)/V()/F 4/DA(/Helv 8 Tf 0 0 0 rg)/M(D:20211013163400-06'00')/FT/Tx/AP<</N 44 0 R>>>>
```

I checked the correct `Widget` and nothing returns on `widget.field_value`.  Also noticed that these values don't show up on the pixmap as well.  Am I doing something wrong here?

### How to reproduce the bug

```
doc = pymupdf.open(file)
parsed_content = []
for page in doc:
    for widget in page.widgets():
        print("---------------------------------------")
        print(f"field type: {widget.field_type_string}")
        print(f"field name: {widget.field_name}")
        print(f"field label: {widget.field_label}")
        print(f"field value: {widget.field_value}")
        print(f"field flags: {widget.field_flags}")
        print(f"doc xref string: {doc.xref_object(widget.xref, compressed=False, ascii=True)}")
        break
```

### PyMuPDF version

1.24.10

### Operating system

MacOS

### Python version

3.10

**Comment by JorjMcKie** [comment]
Please **_always_** provide a reproducing file. This is mandatory for bug issues.

**Comment by y27choi** [comment]
Here is the file I'm having parsing issues with. 

[BDA-Incident-Report 1.pdf](https://github.com/user-attachments/files/17195494/BDA-Incident-Report.1.pdf)

Let me know if you need anything else.

**Comment by JorjMcKie** [comment]
Sorry for the tardy reaction.

Have you noticed the value in the PDF "source"? The problem is that the text is followed by 2 control characters "line feed" `\012` (octal!) = `10` (decimal) = `0x0A`.
PDF viewers behave differently in reaction to this. Adobe shows an empty field for example, others ignore these 2 white characters and show the text, and yet others (like Nitro) treat the text field as a scrollable list field (totally absurd).
MuPDF interprets the string given by `/V (Subaro of Glendale\012\012)` as empty string, equivalent to `/V ()`.
So the problem lies in the data of the PDF itself.
