### ISSUE TITLE
Consider using semantic versioning

### ISSUE THREAD

**Issue by almet** [pymupdf/PyMuPDF#3995]
Hi, and thanks for this amazing library :-)

**Is your feature request related to a problem? Please describe.**

As a consumer of PyMuPDF as a library, we found ourselves in a situation where "MINOR" or "PATCH" version bumps are making breaking changes for us. For instance, in the last release, python 3.8 support has been dropped, making it impossible to use without making important changes on our side.

To be clearer: the issue for us is not being able to reliably know if it's safe to upgrade PyMuPDF without having something break.

**Describe the solution you'd like**

One solution to this problem would be to follow the [semantic versioning scheme](https://semver.org):

> Given a version number MAJOR.MINOR.PATCH, increment the:

>    MAJOR version when you make incompatible API changes
>    MINOR version when you add functionality in a backward compatible manner
>    PATCH version when you make backward compatible bug fixes

Could it be possible to change the way the versions are currently handled? If not, you might want to document how the version numbers should be read.

**Comment by julian-smith-artifex-com** [comment]
Thanks for the appreciative comment, i'm very glad you like PyMuPDF.

I don't think dropping support for obsolete Python releases is something that should be encoded in PyMuPDF's version number, and i don't know any other Python packages that have tried to do this. Instead it is something to be mentioned in the release notes/changelog as we have done. It's also worth mentioning that Python version life cycles are well documented and the end-of-life of 3.8 has been well known literally for years - see https://devguide.python.org/versions/.

More generally, i don't think semantic versioning is particularly helpful with PyMuPDF because we only very rarely make breaking changes to the API, but are continually adding new functions and classes. And we work on a principle of continuous improvement where we release from the HEAD of our git repository fairly frequently, with no attempt to back-port fixes to old versions or maintain release branches etc

If you're interested, PyMuPDF version numbers are described here: https://pymupdf.readthedocs.io/en/latest/version.html.

**Comment by almet** [comment]
> Thanks for the appreciative comment, i'm very glad you like PyMuPDF.

Thanks for taking the time for feedback here :raised_hands: 

> If you're interested, PyMuPDF version numbers are described here: [pymupdf.readthedocs.io/en/latest/version.html](https://pymupdf.readthedocs.io/en/latest/version.html).

I completely missed this document, thanks for pointing it out! The requirement you have to follow the versioning of MuPDF itself makes it hard/impossible to follow semver indeed.

As a result, I think I was wrong expecting that patch releases would mean security patches or bug fixes (as per semver) without touching the API (in terms of code or supported python versions).
 
> I don't think dropping support for obsolete Python releases is something that should be encoded in PyMuPDF's version number, and i don't know any other Python packages that have tried to do this. Instead it is something to be mentioned in the release notes/changelog as we have done.

As you're not following semver, it's up to you to decide. I'm happy to have this discussion to clarify things and expectations on our end. On the general topic, on most of the projects I came across (I checked for requests, flask, Django), python version drop is coming at the same time of added features, and as a result the minor is bumped.

This doesn't mean you have to do it differently. It would be more comfortable for us consumers of the library, but I understand you also have your reasons for keeping the versioning as it is. As long as it's clear, it's an improvement.

> we only very rarely make breaking changes to the API, but are continually adding new functions and classes.

While working on supporting different versions of PyMuPDF on different distributions, we found that the exposed API had changed significantly between versions. Of course, it's okay and mainly a good thing — it's good to improve the APIs! —, but we couldn't really use the versioning to know when to expect changes.

> It's also worth mentioning that Python version life cycles are well documented and the end-of-life of 3.8 has been well known literally for years - see [devguide.python.org/versions](https://devguide.python.org/versions/).

This is true, and I understand how this is the reason why you dropped support for it. In our case, the reason why we want to still support it is because it's the default python version on ubuntu focal 22.04, which is still supported, until it's EOL this summer.
