### ISSUE TITLE
Is it possible to get the overlay property of the text and image for a pdf file 

### ISSUE THREAD

**Issue by apache135** [pymupdf/PyMuPDF#401]
I have tried getText(‘dict’) . The result is not seem like contain the overlay property. Is there a way to check this?  I have a pdf which has image and some text. Some text on overlay the image,others are below. I am working on a way to distinguish both kind of text.

**Comment by apache135** [comment]
one more question: is there a function to set the overlay property for the text on the page . I only find when insert new text to pdf, use insertText() to set overlay,is there a way for the text which has existed on the file?

**Comment by JorjMcKie** [comment]
You can do this:
If you do a ``page.getText("dict")``, the blocks (text and image types) are returned **_in the sequence as they occur_** in the page's ``/Contents`` object(s).
This is also something I exploit with the ``overlay`` parameter: if true, I append a new ``/Contents`` to the existing one(s), otherwise I prepend it.
So if you want you can check whether some text occurs earlier than some image or other text in that list of blocks and also whether the respective bboxes overlap.

**Comment by apache135** [comment]
Thanks. it is as your reply. 
Another issue, On the pdf, there are some textboxes . Some text boxes which contain text  are embedded in others which are filled in light background color. Is there a function to get all the textboxes objects?   I want to set the textbox under the image .

**Comment by JorjMcKie** [comment]
> Is there a function to get all the textboxes objects?

No, there is not. PDF regards all text as a flat structure, it doesn't know about notions like text boxes, tables, etc. It is the programmer's responsibility to relate text coordinates with each other or with images or other PDF drawing commands, etc.
