### ISSUE TITLE
Question: Unable to change font of widget

### ISSUE THREAD

**Issue by skale1** [pymupdf/PyMuPDF#404]
I am having trouble changing the font of a widget from anything other than Helvetica.  I am not sure if any one else is having this issue?  I had the font in my template set to Arial and Arial Italic.  I since had to change the font to Helvetica and font Size to auto for all the form fields to avoid segmentation fault.  Is this normal behavior?  So I changed my template and got it to list in all the widgets on the page without blowing up.  Then I tried to update the font but it always defaults to Helvetica.  What am I doing wrong?
I am new to python also.

**Comment by JorjMcKie** [comment]
Welcome to PyMuPDF!
Seg faults never are "normal behavior". Please open a bug issue with all the required details to follow this up.
Font support for widgets has been restricted to Helvetica, Times-Roman and Courier in my base library MuPDF since v1.16.0. Even their bold / italic versions are no longer available.
Sorry to say that.
