### ISSUE TITLE
Set Document Name when creating `pymupdf.Document` from Stream

### ISSUE THREAD

**Issue by regmibijay** [pymupdf/PyMuPDF#4087]
**Is your feature request related to a problem? Please describe.**
Currently when creating a `pymupdf` from an `io.BytesIO`, I can go ahead as following 

```
doc = Document(stream=stream)
```
which has drawback that the doc.name field is empty. If I supply `filename` kwarg in addition to `stream`, it is simply ignored.

**Describe the solution you'd like**
When `filename` is provided, set `name` attribute to provided value.

**Describe alternatives you've considered**
No alternatives currently.

**Additional context**
Using `pymupdf4llm`, when I supply `Document` to `to_markdown`, and the document object was created from stream, images are stored without a filename as it is empty. Therefore working in scale with images becomes impossible.

**Comment by julian-smith-artifex-com** [comment]
Unfortunately setting `.name` to an arbitrary value would cause problems. `.name` is tested by `Document.save()` if it is asked to do an incremental save, because incremental saves only work if the given filename is the same as the original filename (`.name`) from which the document was created.

[So for example if one loaded from a stream and set the name to `foo.pdf`, then `.save('foo.pdf', incremental=1)` would assume `foo.pdf` was the same as the original stream, and potentially break quite badly.]

In general, streams do not have names, and we probably shouldn't pretend otherwise. I think that the correct place to do what you want is elsewhere, such as in pymupdf4llm.

**Comment by JorjMcKie** [comment]
In one of the next versions of pymupdf4llm we will include a new parameter in the `to_markdown()` method to allow overriding or setting the desired filename.

**Comment by regmibijay** [comment]
Sounds like exactly what we need without hacky workarounds  @JorjMcKie  Looking forward to it.
