### ISSUE TITLE
cluster_drawings() hangs for certain pages.

### ISSUE THREAD

**Issue by Jacek11** [pymupdf/PyMuPDF#4088]
### Description of the bug

The documents in question are single page PDFs size 30"x42". They're architectural reports with a variety of symbols and tables. The page.cluster_drawings() function seems to hang indefinitely. Unfortunately, I can't provide a copy of any of the documents that hang because I don't have the permission to do so from the client.

This happens in Windows and Linux.

Would it be possible to add a timeout variable to that function, so that it'll exit once the timeout is hit even if it didn't finish processing?

### How to reproduce the bug

Maybe this should be a feature request since I can't provide a copy of the failing files.

### PyMuPDF version

1.24.14

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
Sorry, we cannot accept issues without reproducible data. Introducing timeouts is not possible, because all code is executing in the same process.

We all know that vector graphics commands may come in large quantities on some document types - among them those you are mentioning.
I haven't done any measurements but looking at the algorithm I am sure that the method's duration increases at least quadratically with the number of draw commands.
You can control its scope and behavior with a number of parameters:
* Use `clip` to only look at certain page areas.
* Use `drawings` to only consider a subset of the `get_drawings()` output. For example, you could exclude / include certain colors, or fill-only drawings, etc.
* Modify the x and y tolerance values. They express what the algorithm considers to be "neighbors". Zero for instance means that only graphics are joined that actually touch each other.

And finally you can simply check the length of the list `get_drawings()` and do not even try if this exceeds, say, 5000 or something.

**Comment by Jacek11** [comment]
That makes sense. I settled on the last option and will just skip that part of the processing on pages with more than 10k shapes. 
If the duration increases at least quadratically and if you can't add a timeout parameter then there's not much to do currently.
