### ISSUE TITLE
Question / Comment: Extracting tranparent png from pdf

### ISSUE THREAD

**Issue by silvium** [pymupdf/PyMuPDF#422]
I'm sorry I'm asking here, but there's some issue with extracting transparent images that I don't know how to explain and I can't think of the terms for a google search. Basically, if I export from a PDF editor, the image looks like this:
![00003_00008_manual](https://user-images.githubusercontent.com/3007229/71314802-5cbf8a00-2458-11ea-9d50-64eddd45c29e.png)
But when I extract it with fitz it looks like this:
![00003_00008_fitz](https://user-images.githubusercontent.com/3007229/71314825-bb850380-2458-11ea-832b-74be562bf2c3.png)
While writing I started having doubts, would this issue be better suited for stackoverflow? Should I move it there?

**Comment by JorjMcKie** [comment]
Always welcome ... 😊. Let's see if I can help.

How did you extract the image / which method of PyMuPDF did you use?
Is this PDF available or confidential?

**Comment by silvium** [comment]
I'm sorry for the delay in answering, wildly different timezones...

I used the latest (installed from wheel) PyMuPDF-1.16.10-cp36-none-win_amd64
This is the code that I'm using:

`import fitz
import os

workpath = os.path.normpath(os.getcwd())
pdfile = os.path.join(workpath, 'page.pdf')
doc = fitz.open(pdfile)
page_count = doc.pageCount
for page in range(page_count):
    imgnr=1
    p = doc.loadPage(page)
    d = p.getText("dict")
    blocks = d["blocks"]
    imgblocks = [b for b in blocks if b["type"] == 1]
    for obj in imgblocks:
    	pix = fitz.Pixmap(obj['image'])
    	pix.writeImage('{0}\\img\\{1}_{2}.{3}'.format(workpath,str(page).zfill(5), str(imgnr).zfill(5), obj['ext']))
    	imgnr+=1  
    page+=1`

The PDF is not confidential, I am attaching an extracted page:
[page.pdf](https://github.com/pymupdf/PyMuPDF/files/3992409/page.pdf)

**Comment by JorjMcKie** [comment]
I have used PyMuPDF's new feature in command line mode.
The result and some instruction is attached here.
It looks like coming close to what you want, isn't it?
[image-extract.zip](https://github.com/pymupdf/PyMuPDF/files/3992965/image-extract.zip)

**Comment by JorjMcKie** [comment]
In your program, you used method ``getText("dict")`` to extract images.
While this should work fine in most cases, you must recall, that the method

* is designed to produce images with arbitrary document types - not just PDFs
* will produce the images as displayed in document viewers

In order to extract images from a **_PDF_** in the most direct way and close to how they are physically stored in this document type, it is better to use ``Document.extractImage(xref)``.

This is what the fitz command line does. The same approach is chosen in example script [extract-imga.py](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/extract-imga.py) if you are looking for something to start with.
