### ISSUE TITLE
Question / Comment: Is there a way to transform Merged PDF tables to excel

### ISSUE THREAD

**Issue by jackyjingyi** [pymupdf/PyMuPDF#427]
Hi ,  I currently trying to extract tables from PDF, while i encounter some problems. For instance, "merged cells". Previously i use pdfminer which provides low level objects (LTCurve a line or rectangle with a bbox). it works fine for "normal" pdf, however it easily crushes when pdf are not normal (lines breaks or other issues).   
![image](https://user-images.githubusercontent.com/35633139/71974514-a11a9a80-324c-11ea-8d8b-29ad500be8a9.png)

![image](https://user-images.githubusercontent.com/35633139/71974540-b2fc3d80-324c-11ea-987a-e01753cceb04.png)

Pymupdf extract text blocks and words is significantly faster than pdfminer, so i am thinking of changing extraction engine to pymupdf. My question is, is there a way to identify lines, table cells? 

cheers

**Comment by JorjMcKie** [comment]
I have once written table extraction [scripts](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/examples), but not looked into it for quite some time now. Maybe you can use them (after whatever improvements). If I remeber right, there is a GUI (written in WxPython) which calls the actual text extractor.
The basic logic depends of the text extractor:
* extract the words between two provided vertical coordinates (let's say words below 50 and above 670)
* if a list of column coordinates is also provided, concatenate the words to text pieces which fit inside some column.
* if no column coord list is there, then try to "detect" them by some logic ...
* finally return a list of lists of text strings distributed acros the columns

----------------------------
On the very low level, you can also analyze the page's ``/Contents`` object(s) and look for the rectangle and line drawing functions written in there. The language used in PDF for this is described in "APPENDIX A Operator Summary" on page 985 of the [Adobe manual](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf).
A tedious task, I can tell you!

A **line** is drawn by command "l" and looks like this: ``x y l``. x, y are PDF point coordinates.
The command means: "draw a line from current point to point (x, y)".
The _current point_ must have been previously established by some other command:
* move: ``x y m`` = "go to point (x, y)"
* end point of a previous line command
* top left point of a previously drawn rectangle
* end point of a previous curved line drawing, etc.

A **rectangle** draw command "re" looks like ``x y width height re``.
(x, y) are coordinates of the bottom rectangle left point.

When I say **_PDF coordinates_** then this means that standard PDF geometry assigns point (0, 0) to the bottom left of a page. (Py-) MuPDF takes the top left point here.
There exists a ``fitz.Matrix`` which transforms between PyMuPDF and PDF coordinates:

``ctm = page._getTransformation()`` translates from PDF to PyMuPDF, its reverse ``~ctm`` the other direction obviously.

So, how do you get the pages ``/Contents``?

```python
page._cleanContents()  # should be done first
xref = page._getContents()[0]  # read the PDF object id
cont_bytes = doc.xrefStream(xref)  # the /Contents of the page
```

Line 1 concatenates all separate contents objects of a page (if there are several) into one, and also does some language cleanups
Line 2 determines the PDF xref of the result
Line 3 reads the contents. This is a ``bytes`` object. You either work with this, or you can try to apply ``decode("utf8")`` (or some other encoding if known). As you probably will know, decoding is a pesky thing. So probably stay with the bytes.

Because the syntax of this mini-language treats multiple spaces and line breaks always like one space, you then probably split the contents by ``cont_array = cont_bytes.split()`` and then start looking for your drawing command entries (`b"m"`, `b"l"`, `b"re"`, ...). If encountered, the preceeding 2 or 4 strings are the command's parameters( float strings.

**Good luck!!!**

**Comment by jackyjingyi** [comment]
Thanks for your quick reply! I am actually a newbie in python.
For the low level solution, I tried to understand the Adobe Manual book when i used pdfminer to extract data and transform tables. It works fine mostly but it sometimes contains some bias.

According to your answer, are you saying that I can generate line objects by translate "l" methods written in pdf objects? That's sounds very in your word tedious task really.

Let me try your approach and hope I can come back and paste my script here. 

If you are interested why i need these lines or rects. here are approaches how I establish tables (including merged ones) based on lines and rectangles;

1. Detect line or rect objects, some rectangles are actually represent a line with either x0 =x1 or y0=y1.
2. Break these line objects into three points(x,y), (top left & bottom right, and middle point)
3. Clustering points with a small enough tolerance. Then connect clusters by middle points. 
4. re-structure clusters into cell objects ( a rectangle area surrounded by 4  clusters, i consider the table like chess pane and clusters are intersections on the pane. ) After that I put text blocks into cells based on bbox.
5. So a table is a collection of cells, I create some fake cells and consider them as the smallest unit of the table , for instance a normal table without merged cells each cell object has approximately same bbox with only one fake cell. Therefore a merged cell object may contain more than one fake cells.

A very complicated approach and hope it's not boring you very much.
Thanks again for your answer!

**Comment by JorjMcKie** [comment]
> Let me try your approach and hope I can come back and paste my script here.

Sure - you are welcome.

I think I understand why you need those lines and rectangles. I also understand items 1 to 4 of your approach.

In item 1 you are referring to what MuPDF calls "empty" or "infinite" rectangles, respectively. Empty rectangles enclose an area of size 0, infinite rectangles are those where (x0, y0) is not "north-west" of (x1, y1). In PyMuPDF there are rectangle properties which check these conditions.

You may know already that PyMuPDF supports algebra with geometry objects (points, rectangles): e.g. you can add points or multiply points and rects by numbers etc. So if you have two ``fitz.Point`` point objects p1 and p2, then the middle point m of the connecting line is ``m = p1 + (p2 - p1)/2``. The distance of two points is calculated as ``abs(p2 - p1)``. Or calculate the distance of some point p to a point or rectangle x via ``p.distance_to(x)``.

Then there are ways to calculate the union and intersection of rectangles, or extend rectangles with points or other rectangles, etc.

Of item 5 I didn't understand what a "fake" cell may mean, but anyway ...

As you say: the crucial point of "decompiling" a table is finding all the table cells, Once this is done, the rest is easy stuff: text extraction from rectangles.

**Comment by jackyjingyi** [comment]
Thanks for your reply, I believe that the answer is clear enough ! Thank you!

> Of item 5 I didn't understand what a "fake" cell may mean, but anyway ...


About this  here are some descriptions, 
First, let’s recall a one cell table. As we know each cell can be represented as a rectangle area in pdf pane with bbox defines its location. With this attribute, we can create a fake cell object with same bbox but no information in it.
Let’s consider a table in pdf looks like below.
  <img width="179" alt="123" src="https://user-images.githubusercontent.com/35633139/72118201-581d3000-338b-11ea-96f9-872344fb23f3.png">
By computing all x values and y values, we can get two array,
X =[x1, x2, x3]    with length n = 3
Y = [y1, y2, y3]   with length p =3
Then create a (n-1, p-1) zero matrix as a base matrix indicate the table, each location represent a cell, and we can reach the cell by its row and column index.
In this case, the base matrix would be 
	[[0, 0];
	 [0, 0]]
Next, create (n-1)*(p-1) fake cells using values in array x and y.
For instance, 
	Fake cell B (x1, y1, x2, y2);
	Fake cell A (x1, y2, x2, y3);
	Fake cell C (x2, y1, x3, y2); 
	Fake cell D (x2, y2, x3, y3)
Then assign each Fake cell a base matrix but change its corresponding location to 1,
	Fake cell B (x1, y1, x2, y2); [[0, 0], [1, 0]]
	Fake cell A (x1, y2, x2, y3); [[1, 0], [0, 0]]
	Fake cell C (x2, y1, x3, y2); [[0, 0], [0, 1]]
	Fake cell D (x2, y2, x3, y3); [[0, 1], [0, 0]]
As you may noticed that there is only three cells in the table but we create 4 fake cells to represent it.
Therefore, in this step we need to put fake cells into real cells. For instance,
	Real cell A (x1, y2, x3, y3), contains 
Fake cell A (x1, y2, x2, y3); [[1, 0], [0, 0]] plus Fake cell D (x2, y2, x3, y3); [[0, 1], [0, 0]]
Therefore, we can assign Real cell A (x1, y2, x3, y3) a matrix by adding up [[1, 0], [0, 0]] and [[0, 1], [0, 0]], which is [[1, 1], [0, 0]]. Now we know Real cell A is a merged cell.
