### ISSUE TITLE
Characters with horizontal_line can't highlight,is it a bug or my code is not right?

### ISSUE THREAD

**Issue by sczfaker** [pymupdf/PyMuPDF#441]
Hello.
I want to highlight sentences with specific characters.But I came across that when "-" in my text, addHighlightAnnot function doesn't work.
I try some other characters,they work fine.Only text with horizontal line can't higthlight. 
![sentence_with_Horizontal_line_cant_highlight](https://user-images.githubusercontent.com/56368459/74237709-2216f700-4d0f-11ea-8b50-cf12538d33df.JPG)

**Comment by JorjMcKie** [comment]
I probably need the part of the code which identifies the desired text pieces.
The highlighting itself (inserting the annotation) knows nothing about text or whatever else is inside the annotation rectangle (or quad).

**Comment by sczfaker** [comment]
Oh I see.
It's the font file problem. I test some.It seems only msyhl.ttc fontfile can't highlight "-"(Or can't highlight correctly most of time).Default font and msyh.ttc,msyhbd.tcc maybe more other fonts can highlight normally.
Due to net problem,I can't upload the specific code and pdf file,only image file(but still hard to upload all image files to explain the problem).
![highlight_code](https://user-images.githubusercontent.com/56368459/74329095-22c09380-4dca-11ea-9526-476b12299e88.JPG)
![Uploading two_fonts_highlight_different.JPG…]()

**Comment by JorjMcKie** [comment]
As I tried to explain before:
Your problem is **_not the highlighting_** but the **identification** of the rectangle to use for highlighting - in other words, ``page.searchFor`` does not **find** the text as you expect it to find. Whether the successful search also depends on the font chosen for inserting the text may depend on **what** you specify as the text to search and how you specify it. This in turn may be influenced by the encoding chosen when the text is read from "test_string.txt".

If your problem only is the character "-" (hyphen), it may be interesting to check whether this is encoded differently in a text file compared to the PDF ...

Try to **extract** the text from the PDF and see if it is identical to the text inserted before, etc.

**Comment by sczfaker** [comment]
> As I tried to explain before:
> Your problem is **_not the highlighting_** but the **identification** of the rectangle to use for highlighting - in other words, `page.searchFor` does not **find** the text as you expect it to find. Whether the successful search also depends on the font chosen for inserting the text may depend on **what** you specify as the text to search and how you specify it. This in turn may be influenced by the encoding chosen when the text is read from "test_string.txt".
> 
Ha,It's hyphen,I got it.Thanks.

> Try it out yourself and add a highlight annotation using an image rectangle or an empty rectangle

**Comment by JorjMcKie** [comment]
> Should I need another hightlight rectangle method instead of using AddHightlightAnnot(point) directly?

No. This method has nothing to do with your problem.
Your problem is correctly **identifying the text.** If you are successful doing **this**, then everything else should work.

I have moved the example folder to another [repository](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/examples). This new link is not updated on all places, so please look there.
