### ISSUE TITLE
Question: Can a dictionary of values be added to fields within a PDF?

### ISSUE THREAD

**Issue by marksweb** [pymupdf/PyMuPDF#451]
I've been working with `PyPDF` to add data to a PDF and utilised it's ability to add a dictionary of field name & value pairs to a page (and then set them as read-only), rather than write data to specific locations on a page. 

This is a fairly simple case of;

```
from PyPDF3 import PdfFileReader, PdfFileWriter


def generate_pdf(request):
    pdf_path = 'static/pdf/form.pdf'
    template_path = os.path.join(settings.BASE_DIR, pdf_path)

    pdf_reader = PdfFileReader(open(template_path, "rb"), strict=False)
    pdf_writer = PdfFileWriter()

    data_dict = {
        'foo': 'bar',
    }

    pdf_writer.addPage(pdf_reader.getPage(0))

    # Add data to a page
    page = pdf_writer.getPage(0)
    pdf_writer.updatePageFormFieldValues(page, data_dict)

    for j in range(0, len(page['/Annots'])):
        writer_annot = page['/Annots'][j].getObject()
        writer_annot.update({
            NameObject("/Ff"): NumberObject(1)
        })

    output_stream = BytesIO()
    pdf_writer.write(output_stream)
```

I've now been asked to add functionality to take an image & add it to the PDF. This seems fairly straightforward with `PyMuPDF`, but I'd rather not use 2 libraries unless I really have to.

Can the above be achieved using `PyMuPDF`? I can't see this type of functionality covered in the docs/wiki. Or can it read the bytes at the end in order to add an image to a page & then output the PDF file?

**Comment by JorjMcKie** [comment]
Without re-capitulating what I used to know about pdfrw:
I think you are fiddling with some annotations or fields (widgets) of the PDF.
PyMuPDF does support annotations and form fields fairly completely.

What you seem to be doing with them is however even simpler, because you just modify the field flag /Ff in a way which makes the field readonly. If I understand correctly, you should however combine the value 1 with anything which is already coded in that ``/Ff`` dict value, because it actually is an array of bit indicators, i.e. you should **OR** the value 1 into it.

In PyMuPDF you have more than one option to achieve your goal:

```python
page = doc[pno]  # the desired page of document doc
...
for field in page.widgets():  # you can restrict the iterator to certain field types
    field.field_flags |= 1  # make readonly
    field.update()
```
Or if you want to be rather tough, you can also directly modify the PDF object definition on a low level (string manipulation of the field object definition). But let's skip this for the moment.

**Comment by JorjMcKie** [comment]
Answered your question?

**Comment by JorjMcKie** [comment]
Assuming this is answered.

**Comment by marksweb** [comment]
@JorjMcKie Yes, sorry, been away & mega busy so didn't get around to replying after I'd read your response & had a play around with the project again.

Really helpful, thank you!

**Comment by JorjMcKie** [comment]
A pleasure.
Please feel free to re-open or submit other inquiries ...
