### ISSUE TITLE
addRedactAnnot returned a result with an error set

### ISSUE THREAD

**Issue by sinnytk** [pymupdf/PyMuPDF#465]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I was trying to redact a PDF by adding the Redact annotations with the Quad of an input string

## To Reproduce (mandatory)
Here's the code, hope I am not doing anything:
```
for page in doc:
    quads = page.getTextPage().search('sample string here')
    for q in quads:
        page.addRedactAnnot(quads[0])
    page.apply_redactions()
```

## Expected behavior (optional)
The addRedactAnnot function should've just annotated the Quad to be removed as I apply the redaction, however it raises an error when I pass it the Quad object

## Your configuration (mandatory)
 - Windows 10 Pro
 - Python 3.6.8 using Anaconda
 - 1.16.12, installed using pip

**Comment by JorjMcKie** [comment]
> The addRedactAnnot function should've just annotated the Quad to be removed as I apply the redaction, however it raises an error when I pass it the Quad object

* You did not provide the error message - this forces me to review your code and guess ☹
* You have used ``page.searchFor(...)`` instead of using a textpage
* The ``quads`` list contains quads (or rectangles). You always pass the first item of that list ``quad[0]``, instead of ``q``.
* Did you check that ``quads`` is not empty?

**Comment by sinnytk** [comment]
> > The addRedactAnnot function should've just annotated the Quad to be removed as I apply the redaction, however it raises an error when I pass it the Quad object
> 
> * You did not provide the error message - this forces me to review your code and guess ☹
> * You have used `page.searchFor(...)` instead of using a textpage
> * The `quads` list contains quads (or rectangles). You always pass the first item of that list `quad[0]`, instead of `q`.
> * Did you check that `quads` is not empty?

Sorry for this, I am quite new to opening issues on Github. Let me correct myself:
• The error message is as follows:
```
Traceback (most recent call last):
  File "redact.py", line 15, in <module>
    annot = page.addRedactAnnot(q)
  File "c:\users\sinny\anaconda3\lib\site-packages\fitz\fitz.py", line 3468, in addRedactAnnot
    val = _fitz.Page_addRedactAnnot(self, quad, text, fontname, fontsize, align, fill, text_color)
SystemError: <built-in function Page_addRedactAnnot> returned a result with an error set
```

• I am using a search on a TextPage, am I doing it the wrong? Correct me if that's so please

• Yeah, I fixed that. Updated code is appended at the end
• Yes, I am doing that as well, see updated code.

`doc = fitz.open(ifile)
pages = len(doc)

for page in doc:
    quads = page.getTextPage().search('7107378346479')
    for q in quads:
        if isinstance(q, fitz.fitz.Rect):
            annot = page.addRedactAnnot(q)
            page.applyRedactions()

doc.save('output.pdf')`

**Comment by sinnytk** [comment]
For alternative methods to redact the view, I have tried using addRectAnnot and addFreetextAnnot, however they don't update the Content Stream and leaves the hidden text selectable.

**Comment by JorjMcKie** [comment]
> Sorry for this, ...

Never mind. I have nonetheless tried what I assumed to be your intention and indeed found errors! So thank you anyway for catching this 😉!

I already have corrected that and will soon publish a new version.

If you are in any hurry, please use the follow circumvention:

1. When you add a redaction annot, please **_always_** use a replacement text, for example a string with at least one space ``" "``, like ``addRedactAnnot(q, text=" ")``.
2. I hope the following prevents a second error: When iterating over the pages, please use two separate loops - one for adding the annotations and a second one with just ``page.apply_redactions()``.

Also please let me know if this is successful.

**Comment by sinnytk** [comment]
> > Sorry for this, ...
> 
> Never mind. I have nonetheless tried what I assumed to be your intention and indeed found errors! So thank you anyway for catching this 😉!
> 
> I already have corrected that and will soon publish a new version.
> 
> If you are in any hurry, please use the follow circumvention:
> 
> 1. When you add a redaction annot, please **_always_** use a replacement text, for example a string with at least one space `" "`, like `addRedactAnnot(q, text=" ")`.
> 2. I hope the following prevents a second error: When iterating over the pages, please use two separate loops - one for adding the annotations and a second one with just `page.apply_redactions()`.
> 
> Also please let me know if this is successful.

Added the text argument and it worked like a charm!
Thanks for this @JorjMcKie

**Comment by JorjMcKie** [comment]
Two more things:

1. Always try to use ``page.apply_redactions()`` only **_once_** per page - it is a quite costly method and also does a lot of low-level stuff ...

2. I did not express myself clearly: your loop is fine like this:

```python
quads = page.searchFor("string")  # the default is a max of 16 hits - increase hit_max?
for q in quads:
    page.addRedactAnnot(q, text = " ")
```

**Comment by JorjMcKie** [comment]
> Added the text argument and it worked like a charm!

Uff, good!
The corrected version will again tolerate ``text=None`` and should also address that second error ...

**Comment by sinnytk** [comment]
@JorjMcKie I will love to see if I can solve the text=None issue and make a PR, if it's no problem.

**Comment by JorjMcKie** [comment]
@sinnytk - I would indeed welcome help!
In this case however, I already have developed a solution and I am about to finish up for the next version.

For future work, let me ask you what your areas of skills / expertise are. For PyMuPDF, this is the synopsis of requirements. Not all of them need be there, of course ...

* documentation: proficiency with the `Sphinx` package, an own working installation of PDF Latex (MiktTex?). My plan is to separate the existing documentation (currently > 300 PDF pages ...) in two manuals: (1) Reference Guide, (2) User Guide. From looking at some of the questions, it seems that the current stuff is too voluminous to be really practical.

* Python, C, SWIG: the PyMuPDF source is written in a mixture of these three languages. Most sources even contains all three languages at the same time.

* Good knowledge of writing Python C-extensions

* Good knowledge of the MuPDF package. This is written in (sort of portable) C and the base library of which PyMuPDF is a binding

* Some skills on YAML and services like provided by Travis CI would be helpful too.

One of the backburners I have is issue #398 - open since November 2019. What is needed here is a new text entry method in PyMuPDF, which makes use of MuPDF's possibility to also specify the **_language_** of text to be written out. Best read that issue thread yourself.

**Comment by sinnytk** [comment]
From all that, I think I am mostly good with Python and C.

I am quite interested in working on this so I am reading up on everything and I'll get back to you.

**Comment by JorjMcKie** [comment]
> I am quite interested in working on this so I am reading up on everything and I'll get back to you.

I am looking forward to this!
Please do not hesitate to ask for further guidance.

**Comment by JorjMcKie** [comment]
In the meantime uploaded the new version, 1.16.13, which solves your issue.
