### ISSUE TITLE
Question about non-reproducible Acrobat saving errors

### ISSUE THREAD

**Issue by smithct2** [pymupdf/PyMuPDF#472]
Hello,

Thanks so much for this package - it's been great. I have been using it in production for a high-throughput medical records processing system and it's been performing really admirably.

We've been seeing some weird behavior lately, though. Basically, we are using PyMuPDF to perform some annotation steps at the end our processing flow (drawing annotation labels, adding new bookmarks, etc). This usually works fine, but sometimes the output PDF has a problem working in Acrobat... it can be opened but then not re-saved, using either save or save-as. Acrobat will throw one of its (many) save errors, like 14 or 109.

The weirdest thing is that, other times, I can pass the exact same PDF through and everything is totally fine!

We are currently saving our output PDF with ```pdf.save(savename, deflate=True, expand=255)```. I know you recommend garbage 3+ for this (and when I used that, this error did go away), but sometimes when I try that some pages get deleted (as in, they become small white blocks and their thumbnails disappear), so that is pretty much a non-starter for the team...

I realize this is a very broad question, and unfortunately I cannot share any of the PDFs because they contain personal health information, but I was wondering:

-  Have you ever seen anything like this behavior at all? 

- Do you have any suggestions as to why it works sometimes and fails other times, or what I can do with the save function parameters?

-  If I have to enable garbage=3, any idea why pages would be getting deleted, and what I could do to try to catch/prevent that from happening? I am NOT calling clean.

Anything at all would be extremely helpful.

Thank you!

Environment details:

1. Python 3.7.3
2. PyMuPDF 1.16.10
3. OS: Oracle Linux (but also seen on Ubuntu)

**Comment by JorjMcKie** [comment]
First of all, thank you very much for finding the package useful!

> ``pdf.save(savename, deflate=True, expand=255)``

This option combination is contradictory in itself: deflate compresses everything, and expand=255 decompresses everything.
While I remember that I recommended this type of thing some time ago I would no longer do that. ``deflate``  alone should (re-) compress all eligible stuff.

Garbage option 3 is equal to the command line utility option ``mutool clean -ggg``. It will identify identical PDF objects and drop duplicates.
If objects get lost that way, this is a strong indicator for previously undetected PDF structure problems.
Of course, bugs in (Py-) MuPDF cannot be excluded either - as hard to admit as this is 😉.

If you were **changing** the PDF, then that **always** means that old versions of all changed parts continue to exist. Those will be physically deleted with garbage option 1 already.
Maybe you can try to get along with garbage=1.

I understand the confidentiality issue. But this of course is a burden to tracing down errors ...
Do you use other PDF viewers, too - like PDF Xchange? Did you try to save problem-PDFs with any of those?
What happens if you use ``mutool clean -ddd`` - any messages at all?
You could also use this tool (or an equivalent PyMuPDF script with save option garbage=3) as a preprocessor to remove any previously existing structure problems.
As I said befroe, PDF Xchange is a good tool too, to detect and remove PDF-internal inconsistencies.

> The weirdest thing is that, other times, I can pass the exact same PDF through and everything is totally fine!

You mean passing the exact same PDF to Acrobat repeatedly? This would be a strong indicator to an Acrobat error, maybe some kind of intermittent memory inconsistency. If in such a case you retry that file on an Ubuntu system - any change?

**Comment by smithct2** [comment]
Thanks for the very quick response!

>You mean passing the exact same PDF to Acrobat repeatedly? This would be a strong indicator to an Acrobat error, maybe some kind of intermittent memory inconsistency. If in such a case you retry that file on an Ubuntu system - any change?

Sorry for not being clearer; I meant that the script behavior itself was inconsistent. The vast majority of the time, everything is great; only sometimes does it create a PDF that is unable to be re-saved with Acrobat, or with some pages replaced by an all-white canvas. The issue is that even for PDFs that have the problems, it is not reproducible; I can take the source version of the PDF before it was processed and re-process it with my script, and THEN it will work. The behavior is basically like this:

Pass 1 (from source) -> pages 2, 5, 12 blank after processing; cannot be re-saved
Pass 2 (from source) -> all pages fine and can be re-saved

With the only variability being time of processing and things like system load, etc (we are using multiprocessing to handle multiple instances of this at the same time).

> If objects get lost that way, this is a strong indicator for previously undetected PDF structure problems. Of course, bugs in (Py-) MuPDF cannot be excluded either - as hard to admit as this is 😉.

I strongly, strongly suspect that some pages have source corruption to some degree, yes. But I am still at a loss as to why my script would sometimes be able to work around that and sometimes not be able to, even with the exact same file.

> Maybe you can try to get along with garbage=1.

I did this for my most recent attempt at a bugfix, but the issue was still intermittently present. I've seen this behavior (either not being able to re-save OR with pages getting dropped) when using both garbage=1 and garbage=3, unfortunately.

> What happens if you use mutool clean -ddd - any messages at all? You could also use this tool (or an equivalent PyMuPDF script with save option garbage=3) as a preprocessor to remove any previously existing structure problems.

I am thinking that using the preprocessor might be the way forward...I am just worried about data loss.

> Do you use other PDF viewers, too - like PDF Xchange? Did you try to save problem-PDFs with any of those?

The client unfortunately has a business requirement for Acrobat; I won't be able to get them to change to other readers. I have not seen this issue with evince, Foxit, or Xchange in my local testing though.

I will try with the preprocessor garbage=3 setting and see if that improves things.

**Comment by JorjMcKie** [comment]
Hm, ok, I so far understand. What else can be done ...
Can you share the PyMuPDF script you are using? I am willing to have a look at and wait for enlightenment ...

Just thinking of a way to automate that problem detection: how about the following sequence of steps (admittedly a little brute force kind of thing):

1. read the PDF and store a PNG image for every page somewhere
2. preprocess the PDF with garbage=3 or ``-ddd``.
3. read the PDF again taking PNG pictures and compare each page image with the previously stored one. There **_must_** be binary image equality page by page! Else the PDF was damaged from the start and must be taken out of the process.
4. If there was no problem in previous steps, continue as normal. I would hope that from this point on, nothing bad will happen.

Steps 1 through 3. can be made very fast. For example the generated PNG need not be the largest resolution - using a ``fitz.Matrix(0.5, 0.5)`` in page pixmap creation should suffice and would create image file sizes of about 25% of the normal ones. So I would guess it could be done within well below 20 seconds total for all 3 steps.

**Comment by smithct2** [comment]
[annotator.zip](https://github.com/pymupdf/PyMuPDF/files/4375304/annotator.zip)

Here is the PyMuPDF relevant piece. I have trimmed a lot of other stuff, but I hope it is still understandable.

You will see I have already tried to add in some redundancy to handle this error – e.g. try the final save twice (perhaps the problem is with the file I/O? it typically saves to a network share) or error out of annotating the PDF at all if we see any muPDF warnings (_having_ errors is OK, we just need to be able to capture them and route the PDF correctly – they cannot get into our “success” queue if they have this save/page deletion problem, which is currently the issue).

Your idea seems sound as well, although we do have some PDFs that are over 2GB/10000 pages :/...

**Comment by JorjMcKie** [comment]
> Your idea seems sound as well, although we do have some PDFs that are over 2GB/10000 pages :/...

Ok, got you. Then another idea could be: if a page is empty, its pixmap should consequently be very small and / or consist of white pixels only. This could be checked, e.g. like so:
```python
# make a (small) gray, low resolution pixmap of the page
pix = page.getPixmap(matrix=fitz.Matrix(0.2, 0.2), colorspace=fitz.csGRAY)
s = pix.samples  # the raw bytes of the image
# the length of s will approx. equal page.rect.width * page.rect.height / 25
# or about 20KB for a letter page
if s == b"\xff" * len(s):  # this page is empty / completely white!
    # take some action
```
So, after a preprocessing save with an appropriate garbage option, a second step could a script with the above check. When it finds white pages which shouldn't be like that, prevent further processing of the file.

I have read the script: impressive work! Nice to see how PyMuPDF does play a role in real world production work.

A few fist reactions (minor importance all of them):

* The annot deletion loop could be simplified somewhat, because ``page.deleteAnnot`` delivers the ``next`` one: ``while annot: annot=page.deleteAnnot(annot)``.
* If a page cannot be loaded (damaged page tree), then the world is not necessarily in order if the next page **_can_** indeed be loaded. There is a fairly high probability that the damage causing this error is not local to that page. Sometimes the MuPDF error message gives a clue on the severity.

As we discussed before, the changes done by this script only justify a garbage=1. It shouldn't itself lead to multiple identical objects, consequently suggesting garbage=3.
BTW garbage=2 mainly just removes xref numbering gaps resultinbg from garbage=1 activities ...

**Comment by smithct2** [comment]
Got it - thanks for the suggestions. I am currently trying to push a fix with ```deflate=True and garbage=1```. We will see what happens.

For now, we are just building in some redundancy and trying to take a backup of the PDF before we annotate so we can rollback if anything goes wrong. I'll let you know how it goes.
