### ISSUE TITLE
Excessive paragraph marks in one line

### ISSUE THREAD

**Issue by fredshu** [pymupdf/PyMuPDF#516]
Hello, I am getting lots of paragraph marks after doing page.getText() on the 1st page of the attachment. The issue happens in 7th, 8th and 9th lines of the text (after 6 lines of tiles/subtitles):

DE\nR$\n170.000.000,00\nPARA\nR$\n196.832.000,00,\nMEDIANTE\nSUBSCRIÇÃO\nPARTICULAR\nDO\nMONTANTE\nTOTAL\nDE\nR$\n26.832.000,00,\nCORRESPONDENTE\nA\n1.200.100\nNOVAS\nAÇÕES\nORDINÁRIAS\nNOMINATIVAS,\nNAS\nSEGUINTES\nCONDIÇÕES:\nA)\nO\nVALOR\nDE\n

As you can see, there is a paragraph mark after nearly every word. I am trying to use PyMuPDF to segment sentences and identify titles/subtitles.
First time writing at GitHub, sorry for any missing information.
[0000940426945.pdf](https://github.com/pymupdf/PyMuPDF/files/4672783/0000940426945.pdf)

**Comment by JorjMcKie** [comment]
There is some algorithm in MuPDF that decides, when a new line should be started. Among those criteria is the horizontal distance to the previous text's end. There are more...

You did not mention which variant of text extraction you used. Looks like ``getText("text")`` or ``getText("blocks")``. This is too unreliable for you intentions.
I recommend you use a variant which also provides text position info, like "words" or "dict".
Then sort / re-order the output along this info and recompose the text into normal reading order.

E.g. ``getText("words")`` delivers list of items ``(x0, y0, x1, y1, "word", ...)``. This can be sorted by the y0, then by the x0 entries.
Then reconstruct each line by  concatenating the words having the same y1 (plus or minus a small allowance, which could be calculated as a percentage of the rectangle height y1 - y0), etc.

**Comment by fredshu** [comment]
Hi Jorj, thanks for your prompt help! I got your hint. Do you think that a margin of +/- 30% of (y1 - y0) should be enough to accommodate any badly-built PDF with uneven text lines, like OCR-ed files? The texts I see usually have lines around 14 pixels high.

**Comment by JorjMcKie** [comment]
> Hi Jorj, thanks for your prompt help! I got your hint. Do you think that a margin of +/- 30% of (y1 - y0) should be enough to accommodate any badly-built PDF with uneven lines, like OCR-ed files? The texts I see usually have lines around 14 pixels high.

Yes that should be enough by far. Probably even 20%.

> Is it safe to use spans instead of words to rebuild lines?

Definitely better even. Because the "dict" output better reflects the total page layout. E.g. it also reports if text is not horizontal. And then - at least _en gros_ - the text pieces are larger.
Other advantages are the detailed font information: size, color, flags.
The "words" and "blocks" variants have been created once as a high-performance alternative.

As a general comment:
One of the things I always wanted to improve, are replacing the "dict" bboxes by quads. Meaning, that I am returning the blue rectangle instead of the white one. The dict now contains the "origin", which is point "ll", and the angle of the word, given in "dir" as a tuple (cos, sin).
![img-quads](https://user-images.githubusercontent.com/8290722/82748907-97b14b00-9d73-11ea-8a08-8226b577e12c.jpg)
What is keeping me back are the changes to the API, not the effort itself.

**Comment by fredshu** [comment]
Thanks again, Jorj, and congratulations for this useful project.

**Comment by JorjMcKie** [comment]
Thank you. Glad you like it.
