### ISSUE TITLE
Different results in page.searchFor when upgrading from 1.16.18 to 1.17.1

### ISSUE THREAD

**Issue by xobed** [pymupdf/PyMuPDF#532]
## Describe the bug
page.searchFor is returning different results when upgrading from `1.16.18` to `1.17.1`

## To Reproduce
Use [test.pdf](https://github.com/pymupdf/PyMuPDF/files/4804934/test.pdf) file

Code to reproduce:
```python
from os.path import expanduser

import fitz

document = fitz.Document(expanduser('~/Downloads/test1.pdf'))
page: fitz.Page = document[0]

rect = page.searchFor('BILLED QTY')
print(rect)
```

Result with `1.16.18`
`[Rect(463.2997741699219, 157.32423400878906, 506.90350341796875, 164.17398071289062)]`
These coordinates are expected and match what I am seeing when I open the PDF in GIMP, switch to point coordinates and navigate to the 'BILLED QTY' part manually.

Same code running with `1.17.1`
`[Rect(157.32423400878906, 335.09649658203125, 164.17398071289062, 378.7002258300781)]`

## Your configuration
- OS X 10.14.6
- python 3.7.7 (default, Mar 17 2020, 09:44:48) [Clang 11.0.0 (clang-1100.0.33.17)] 
- PyMuPDF 1.16.18: Python bindings for the MuPDF 1.16.0 library.
Version date: 2020-04-22 14:00:00.
Built for Python 3.7 on darwin (64-bit).
 - PyMuPDF installed to virtual environment with `pip install PyMuPDF`

**Comment by JorjMcKie** [comment]
In versions prior to v1.17.0, coordinates **_returned_** and coordinates **_used for insertion_** of things like annotations, fields, text, images, etc. were inconsistent whenever **_rotated_** PDF pages were involved. This was partly due to inconsistencies in PyMuPDF but, more importantly, due to more inconsistencies in MuPDF, which could not be resolved.

I therefore decided to clean this up starting with v1.17.0, and continued to do this in the current v1.17.1.

This means that **_all coordinates now always refer to the unrotated page_** (hope I didn't miss any corner case!). Please refer to the first few paragraphs of the ``Page`` section of the documentation.

If you need coordinates pertaining to the rotated page, multiply them with ``Page.rotationMatrix``.
If some other software delivers rotated coordinates, get the unrotated version by multiplying with ``Page.derotationMatrix`` (the inverse of the previous one).
Both matrices automatically detect / adjust to the page rotation. So, you can do the respective multiplications without looking anything up, if you need the **physical coordinates** across rotation changes.

```python
>>> import fitz
>>> doc=fitz.open("test.pdf")
>>> page=doc[0]
>>> rl=page.searchFor("BILLED QTY")
>>> len(rl)
1
>>> page.rotation
90
>>> rect=rl[0]
>>> rect
Rect(157.32423400878906, 335.09649658203125, 164.17398071289062, 378.7002258300781)
>>> rect * page.rotationMatrix  # this delivers the rotated coordinates
Rect(463.2997741699219, 157.32423400878906, 506.90350341796875, 164.17398071289062)
>>> 
```

**Comment by xobed** [comment]
Thanks, confirming it works OK when using `rect * page.rotationMatrix`
