### ISSUE TITLE
Cannot detect signature field? 

### ISSUE THREAD

**Issue by Arbitrage0** [pymupdf/PyMuPDF#534]
I have a PDF which contains an unsigned signature field, but when I run `getSigFlags()` on the file it returns 0. The signature field was added via an API, and the sample PDF is available [here](https://docdro.id/5h5TOs4) (with signature field on the last page). 

On another note, can images be added to PDFs with signature fields and be saved incrementally without losing the fields?

**Comment by JorjMcKie** [comment]
1. This document is **_not a Form PDF_** in the sense that it contains valid fields. The list of root fields is empty.
2. Document method ``getSigFlags()`` only checks whether this PDF property exists, and if yes, it reports its content. If it is not present or has an incorrect content or otherwise does not reflect the reality ... too bad.

Your example does have a signature field on the last page (unsigned), but this contradicts point 1 above.
It does not have a ``SigFlags`` field - which admittedly is optional.
I will update the documentation accordingly, the current formulation obviously causes wrong expectations.

**Comment by JorjMcKie** [comment]
> On another note, can images be added to PDFs with signature fields and be saved incrementally without losing the fields?

Here is a quote from page 726 of the PDF manual:

> Note: If a signed document is modified and saved by incremental update (see Sec-
tion 3.4.5, “Incremental Updates”), the data corresponding to the byte range of the
original signature is preserved. Therefore, if the signature is valid, it is possible to
recreate the state of the document as it existed at the time of signing.

So presumably the answer to your question is yes (if you meant to ask, whether the signature remains valid on incremental changes).

**Comment by Arbitrage0** [comment]
Thanks for your answer, this makes a lot more sense.
