### ISSUE TITLE
Change appearance of redaction annotation

### ISSUE THREAD

**Issue by martinevanschouwenburg** [pymupdf/PyMuPDF#535]
Hi, 

I have a question regarding the redaction annotations. 

In current version the appearance of the redaction is hard coded such that it appears as a crossed-out transparent rectangle with red lines.

Would it be possible to change the addRedactAnnot function such that you can include parameters that define the appearance of the markup. I was thinking for example 'stroke' to indicate the color of the border, 'width'  to indicate line width, and a parameter that indicates if would like the cross-out or not. I understand that this goes beyond the standard PDF features that are implemented for a redaction annotation. 

Also, we would be happy to make the changes to the code ourselves and submit as a pull request if you are open to that. 

Best, 
Martine

**Comment by JorjMcKie** [comment]
Hi,
Shouldn't be a big problem to include these changes. Can you please confirm that this is the desired scope:
* ability to set the stroke color
* ability to set the line width
* ability to skip the crossing out lines, so only the rectangle survives
* No dashing required?
* Please note that (controlling the) background color setting remains impossible by all means.

> I understand that this goes beyond the standard PDF features that are implemented for a redaction annotation.

There actually is no such (PDF) standard. Just MuPDF has decided to visualize a redaction via a red rectangular border, and I disliked it enough to at least add those diagonal lines ...
Nothing (i.e. no PDF standard) would prevent us from adding things like opacity, blend mode and what not.
The limiting aspect is, that for **applying** a redaction, its object definition must be self-sufficient to generate the resulting content. This is why the original redaction cannot have a fill color: the ``/IC`` parameter is required to generate the background of the result.
But of course, via method ``annot.update()`` we can do more or less whatever we want with the annot's appearance stream.

I would certainly also welcome a PR if you want to do this. Just please make sure to use the current source v1.17.2, which I will publish within the next 2 days.

**Comment by martinevanschouwenburg** [comment]
Thanks for the quick reply! 
The desired scope is correct. We won't be using dashed lines for now. 

I'm not sure if we are able to submit the changes before the next release, but if that is not a problem, we can make the suggested changes.

**Comment by JorjMcKie** [comment]
> I'm not sure if we are able to submit the changes before the next release, but if that is not a problem, we can make the suggested changes.

No need for any rush here. I was just asking not to take the **_current_** source as a basis for a PR, because I have been doing some C syntax cleaning, and these things tend to touch a lot of code ...

**Comment by JorjMcKie** [comment]
Hi Martine,
already done, was easy-peasy. Suggesting the following API changes:

* ``page.addRedactAnnot(..., cross_out=True)`` to request those diagonal lines (default). Set to false if not desired.
* Similarly ``annot.update(..., cross_out=True)``. If **_not_** desired, then ``cross_out=False`` **_must_** be given (again) in the update method - even if the annot was created with ``False``.

Otherwise:
* ``setColors`` is fully supported for stroke and fill. As before, fill applies to the appearance **_after_** ``apply_redactions()``.
* ``setBorders`` is fully supported for width **_and_** dashes
* ``setOpacity`` and ``setBlendMode`` is supported - also respectively for the ``update()`` method.

Example:
Created with ``cross_out=False``:
![grafik](https://user-images.githubusercontent.com/8290722/85543246-e0b12500-b5e7-11ea-8f8e-c965cdf9e669.png)
Updated via
```python
annot.setBorder(width=2, dashes=(2,))
annot.setColors(stroke=(0,0,1))
annot.setOpacity(0.3)
annot.update(cross_out=True)
```
![grafik](https://user-images.githubusercontent.com/8290722/85543618-3a195400-b5e8-11ea-8e39-5bdcad53da27.png)

If you are fine with this, I will include the feature in version 1.17.2 and publish probably within the course of the week.

Note:
Stupid me: blend mode, dashing and opacity had already been supported before. They apply to all annotations.

**Comment by martinevanschouwenburg** [comment]
Great, that is awesome! 
I was just about to submit a pulse request, but this is even better. 
Thanks!

**Comment by JorjMcKie** [comment]
Just uploaded v1.17.2 to PyPI.
