### ISSUE TITLE
split page ranges based on annotation info

### ISSUE THREAD

**Issue by ousia** [pymupdf/PyMuPDF#555]
@JorjMcKie,

I wonder whether it would be possible to write a script such as the one I’m describing in PyMuPDF.

Rationale: I have a huge document (> 1100 pages [and growing]), that I need to be able to split in chapters and sections. (A sample document is attached [[ssample.pdf](https://github.com/pymupdf/PyMuPDF/files/4886127/ssample.pdf)].)

I take for granted that PyMuPDF can read annotations. I mean, it can read all annotations in the whole document.

I’m attaching a PDF document that has a similar structure to the one I have to deal with.

1. The relevant annotations are with subject `whatever`. There may be other annotations, but they should be ignored.

1. Each annotation has the title with a key, such as `1.1-start` or `1.1-synopsis-stop`.

1. There should be matching titles (in different annotations), such as `xxxx-start` and `xxxx-stop`.

1. For these ones, I would like to have a new document `xxxx.pdf`, which contains the pages from `xxxx-start` to `xxxx-stop`.

1. I would like that the new documents include the `/ViewerPreferences` dictionary from the original document.

1. There may be unmatched annotations, such as an `abcde-start` that lacks the corresponding `abcde-stop`. These ones are to be ignored.

Would it be possible to have a script that generates all required documents automatically?

Many thanks for your help.

**Comment by JorjMcKie** [comment]
Hi Pablo,
Overall I would answer **_yes_** to your compound question.
The only **exception** being, that I have not yet implemented a way to store viewer preferences. But let me discuss this point later.

> I take for granted that PyMuPDF can read annotations. I mean, it can read all annotations in the whole document.

You can read annotations page by page, and for each annotation you can access the information needed in its `info` dictionary, like title and subject.

One yould go over the document in several runs:
Run 1 builds pairs of annotation "start" title page numbers and "stop" title page numbers.
Then, for building the sub-documents, there are a few alternatives:

# Alternative 1
For each page number pair (pno1, pno2) build a list/tuple (pno1 + 1, pno1 + 2, ..., pno2) and do ``doc.select(list)``, then `doc.save("part1.pdf", garbage=3,...)` and recycle the document `doc.close();doc.open(doc.name)` to process the next page number pair.
This would leave much of the original doc structure in place (e.g. viewer options, metadata, TOC fragments).
But of course there are several opens and closes involved.
Note: Instead of method `select()` you could also use `doc.deletePageRange(pno2+1, -1)` and `doc.deletePageRange(0, pno1-1)`. May be faster.

# Alternative 2 
For each page number pair (pno1, pno2) open a new empty PDF and insert the relevant pages into it: `new.insertPDF(doc, pno1, pno2)`. Then (if important) insert doc metadata and the relevant TOC fragment.
To copy over the viewer preferences, I am afraid we must use a few lowlevel functions:
1. determine xref of catalog of document `new`: `xref = new.PDFCatalog()`.
2. read the catalog object ``newcat = new.xrefObject(xref)``
3. read old PDF root: ``oldcat = doc.xrefObject(doc.PDFCatalog())``
4. Now - via string manipulation - copy the old `/ViewerPreferences` and maybe other valuable stuff into string newcat. Because both strings are well-formatted, this process should be fairly easy to do.
5: Now `new.updateObject(xref, modified newcat)`.
6. `new.save("part1.pdf", garbage=3, ...)`


As seems obvious, alternative 1 shold be simpler to implement. The second alternative might be used if performance or other motivation suggests it.

I hope this reflects what you intend to do.
>If you imagine to delete the indicative annotations from the target PDFs: that is possible too.

**Comment by ousia** [comment]
@JorjMcKie,

huge thanks for your in–depth reply.

I don’t need the `/ViewerPreferences` dictionary that much. I could avoid that.

I wonder whether it would be possible to add a new dictionary with so much hassle (but this would be for later, in any case).

Many thanks for your help.

**Comment by JorjMcKie** [comment]
You are welcome.
I have at least a backburner plan to open the various settings in a PDF to the API. Among other things I am thinking about the best way to do that, may be a Python dict, or some new class with appropriate properties ...
Technically, in terms of accessing those data for read and write is really easy peasy. Together with the existing low-level methods, it might boild down to just Python object manipulations.
