### ISSUE TITLE
Question / Comment: Search in a pdf page returns nothing. What can be the cause?

### ISSUE THREAD

**Issue by kuharan** [pymupdf/PyMuPDF#570]
I have a pdf where the search for a specific text returns Null. The page when printing in the terminal outputs boxes - similar to this ☐. However, when I open the pdf with pdf applications like adobe reader and search manually it successfully finds the text. What are the possible causes of this issue?

```
import fitz

pdf_document = "xxx.pdf"
doc = fitz.open(pdf_document):
page1 = doc.loadPage(0)
page1text = page1.getText("text")
print(page1text)
```

**Comment by JorjMcKie** [comment]
Those square symbols (also called "TOFU" because of how they look like) usually indicate that the font  in use encodes the text in some hidden manner - to prevent you from doing what you tried to do ☹.
You should also be unable to copy / paste the text from the displayed page right?
Final clue would be possible by actually looking at the PDF.
I'm afraid the only thing you can do is deciphering via an OCR package like [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF).

**Comment by kuharan** [comment]
Hi @JorjMcKie,
I am actually able to search for the text in the pdf by opening it with Adobe reader and even copy-paste it. The only problem is that Fitz cannot find the characters ad display it.

**Comment by JorjMcKie** [comment]
Interesting. To trace the cause I need the file for reproduction. I’m currently without electricity and only able to use internet via mobile phone.

**Comment by kuharan** [comment]
Oh, I will not be able o do it, it is a sort of financial statement. Is there any other way?

**Comment by JorjMcKie** [comment]
Unfortunately not. Let’s postpone this until you find an example that you can share.

Von meinem iPhone gesendet
