### ISSUE TITLE
Utilize pikepdf to support create/edit/delete PDF outlines

### ISSUE THREAD

**Issue by Nokia808** [pymupdf/PyMuPDF#597]
Hi.
Since your program is in Python, I would like to suggest on you to utilize pikepdf as a backend to add abilities to create/edit/delete PDF outlines (TOC).

This certainly only valid if you like to make your program an editor for PDF not only viewer .....

**Comment by JorjMcKie** [comment]
I do not see any added value of this, since PyMuPDF has this feature already.
There also exists a GUI script to do that interactively.

**Comment by Nokia808** [comment]
@JorjMcKie 
Forgive me! I can not use your program because it is not available to me as Fedora user, so I did not know this. Really!! Really have this feature!! This is 1st Linux GUI program to my knowledge supporting this feature !

If so, you can close this issue. Is their a video on your tube or other site show this feature ? I read that your application has annotation tools !

**Comment by JorjMcKie** [comment]
If you cannot use one of the Linux wheels, you can still use it on Fedora once you install / build MuPDF and then PyMuPDF. This process is well documented.

The TOC maintenance script itself is pure Python based on wxPython. It is located [here](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/PDFoutline.py) alongsided by a HTML help page.

Similarly, there is a PDF link maintenance GUI (located in same folder).

And since a couple of days there also is a GUI script that lets you move, insert, delete images on PDF pages (same folder).

I am planning to also add a GUI for annotation maintenance. The required programmable features as such are already there since a long time now. Just handling them under visual control is still mssing.

The same situation for PDF form fields: fully supported, just a GUI to use it onveniently would be great.

Maybe you look into that examples folder. Over time it has become a whealthy repository of scripts for many situations.
