### ISSUE TITLE
[Packaging] Make your application available as flatpak on FlatHub

### ISSUE THREAD

**Issue by Nokia808** [pymupdf/PyMuPDF#598]
Hi.

Instead of building so many binaries - a time wasted process - you can build flatpak (a universal Linux package that working on almost all Linux distros) & add it to FlatHub .....

1. home page of FlatHub is:
    https://www.flathub.org/home
2. FlatHub repositories are at:
    https://github.com/flathub
3. when some one like to add package to FlatHub, she/he need to open PR at:
    https://github.com/flathub/flathub/pulls
4. FlatHub differ from snap by being allow any one to package not only developers of packages. So packages on FlatHub are of 2 kinds regarding this point: some are packaged by their developers like PDF Mix Tool, while other are packaged by person other than their developers. So, you can package your program by yourself. This will be ideal.
5. all packages on FlatHub are signed .....
6. even if person other than the original developer(s) maintain the package on FlatHub, FlatHub team try as much as possible to make developer(s) authorized to repositories at least to monitor & follow up the packaging ......
7. FlatHub allow both open & closed source packages. But regarding open source packages, the FlatHub team insisting on packager to make them deterministic (reproducible).

**Comment by JorjMcKie** [comment]
Thaks for submitting this. Had a glimpse at that flatpak stuff. I think there is a major misunderstanding:
* I am **_not building different binaries_** for different Linux distros! Just 1 binary per Python version which is compatible with (almost) all Linux version. The portability between different Linux flavors is already built in.
* I guess you are not telling me that flatpak would support all Python versions with the same binary extension module, or are you?
* Even if it were like that, I still have to generate separate binaries for each Py version on Windows and on OSX
* The binary generation effort is not really consuming my time, because it is largely done by the Travis CI service. All I have to do is uploading the generated binaries to PyPI and to the Github releases folder.
* One more consideration is that my users would not welcome yet another provider of the package. They want to do ``python -m pip install ...``. Even specifying Github as a provider instead of PyPI would introduce a hurdle.

**Comment by Nokia808** [comment]
@JorjMcKie 
Dear I'm not programmer ... But regarding your question "I guess you are not telling me that flatpak would support all Python versions with the same binary extension module, or are you?"
I know that flatpak package do not need for dependencies, because it is like .exe for Windows being come with all needed dependencies within same flatpak package so that this package can run perfectly on any Linux distro regardless python installed on this distro or not. So, it is not a matter which is the python version installed on system because flatpak need no python package to be installed on the system.

See the flatpak official sites:
https://flatpak.org/
https://docs.flatpak.org/en/latest/

You can use flatpak repository on GitHub to ask them:
https://github.com/flatpak/flatpak
Also, you can use forum of FlatHub:
https://discourse.flathub.org/

**Comment by Nokia808** [comment]
By the way, there is a python application on FlatHub as flatpak working okay. It is pdfarranger:
https://www.flathub.org/apps/details/com.github.jeromerobert.pdfarranger

There is some important pikepdf features that can not implemented in pdfarranger due to it's design. These features need a viewer like Okular, but Okular not compatible with python, & this what made me searched for a PDF viewer written in python & I found your PyMuPDF .... And it seem that your application not only a viewer but an editor also which can be a strong competitor for Okular ..... If your application has annotations tools like that of Okular, then we have nearly complete PDF solution on Linux if user installed both PyMuPDF & pdfarranger. For that I asked for flatpak version.

**Comment by JorjMcKie** [comment]
Well then this confirms, that flatpak etc. solve problems that PyMuPDF simply doesn't have:
* PyMuPDF is a programming component, not an application
* its binary components are Linux-independent but Python version dependent 
* PyMuPDF helps programmers building applications - which by their nature are not only Linux indepenent, but even plaform independent.

**Comment by Nokia808** [comment]
@JorjMcKie 
Thank you for clarification !
