### ISSUE TITLE
Incorrect text positioning in TextWriter if CropBox != MediaBox

### ISSUE THREAD

**Issue by JorjMcKie** [pymupdf/PyMuPDF#600]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Text is incorrectly positioned via `TextWriter.writeText` on a PDF page, where CropBox does not equal MediaBox.

## To Reproduce (mandatory)
N/A

## Expected behavior (optional)
N/A

## Screenshots (optional)
N/A

## Your configuration (mandatory)
Happens on all platforms.

## Additional context (optional)
A solution has already been developed and will be contained in the next version.

**Comment by openandclose** [comment]
@JorjMcKie 

Hello, I'm learning to use your software, and I might have encountered this bug.
I think the fix is in 'upload v1.17.5 (60e0c1fd5abadf61905253ea2fa19f62cb28e66e)',
but that's a bit too broad and I'm not certain.

I'd be happy if you could provide the exact diff and the context for the fix.

**Comment by openandclose** [comment]
OK, I give up (and may file an issue).
