### ISSUE TITLE
Question / Comment: Should the transformation matrix be different if the page rotation is different?

### ISSUE THREAD

**Issue by Jboulery** [pymupdf/PyMuPDF#619]
Hello,

I just came across this example which confuses me, I cannot share the data unfortunately:
```python
doc = fitz.open('a.pdf')
page = doc[0]
page.rotation, page.transformationMatrix
# (0, Matrix(1.0, 0.0, 0.0, -1.0, 0.0, 841.8900146484375))
```

```python
doc = fitz.open('b.pdf')
page = doc[0]
page.rotation, page.transformationMatrix
# (90, Matrix(1.0, 0.0, 0.0, -1.0, 0.0, 841.4400024414062))
```

If the pages rotations are different, shouldn't it affect the transformation matrices? 
Thanks :)

**Comment by JorjMcKie** [comment]
No, a decision I had to take was, that the transformation matrix always refers to the **_unrotated_** page.
The reasons for this include include inconsistent behaviour of the underlying library (MuPDF) when it comes to different forms of inserting object: annotations, images, text etc.
The solution is to request that all insertions (and the correspondig information in backward direction) pertain to the **_unrotated_** page.
If rotated information is necessary or provided, the new matrices `derotationMatrix` and `rotationMatrix` can be used to generate the values for the desired coordinate system.
I feel that this also provides a clear setting for the developper: treat the page always as unrotated - rotation is for final presentation to the viewer only. Otherwise it would be hard to explain or understand, why the result of, say ``page.searchFor()`` produces completely different or incompatible results before and after a ``Page.setRotation(90)``.

**Comment by Jboulery** [comment]
Alright, thanks for the answer, I'm trying to get the correct coordinates of `lines` bounding boxes obtained with `page.getText('dict')` and for some pages a rotation has to be performed. I was assuming that applying the inverse of the page transformation matrix would be the correct way of getting them:
```python
blocks = [b for b in page.getText('dict')['blocks'] if b['type'] == 0]
lines = [line for block in blocks for line in block['lines']]
for line in lines:
    r = fitz.Rect(line['bbox'])
    coords = list(r.bl * ~page.transformationMatrix) + [r.width, r.height]
    y0 = draw_cont[0]
    y1 = draw_cont[0] + draw_cont[2]
    x0 = draw_cont[1]
    x1 = draw_cont[1] + draw_cont[3]
```
And here those coordinates are not correct for some cases. Any tip then? :)

**Comment by Jboulery** [comment]
Alright, thanks for the answer, I'm trying to get the correct coordinates of lines bounding boxes obtained with page.getText('dict') and for some pages a rotation has to be performed. I was assuming that applying the inverse of the page transformation matrix would be the correct way of getting them:
```
blocks = [b for b in page.getText('dict')['blocks'] if b['type'] == 0]
lines = [line for block in blocks for line in block['lines']]
for line in lines:
    r = fitz.Rect(line['bbox'])
    coords = list(r.bl * ~page.transformationMatrix) + [r.width, r.height]
    y0 = coords0]
    y1 = coords [0] + coords [2]
    x0 = coords [1]
    x1 = coords [1] + coords [3]
```
And here those coordinates are not correct for some cases. Any tip then? :)

**Comment by JorjMcKie** [comment]
Without looking into your details too much some more comments:
* The algorithm I outlined above works via temporarily setting page rotation to zero before any insertion and before extracting object coordinates. Then the rotation is re-established to the befroe value.
* Rectangle corners under a page rotation remain rectangle corners . But the target of top-left and the traget of bottom-right **_do not define_** the rotated rectangle.
* Always keep in mind that matrix multiplication is not commutative, so in general you have this
```python
>>> ictm = ~page.transformationMatrix
>>> mrot = page.derotationMatrix
>>> mrot * ictm  == ictm * mrot
False
>>> 
```
* To not get confused, best mimic the logic above: first derotate the page, then calculate your object coordinates, then rotate back.

**Comment by Jboulery** [comment]
I'll do that, thanks for the amazing work !
