### ISSUE TITLE
Question / Comment: what is the purpose of _reset_page_refs

### ISSUE THREAD

**Issue by sant527** [pymupdf/PyMuPDF#638]
I have two pdfs without any bookmarks, links etc

I want to combine them using `doc1.insertPDF(doc2)`

While going through the code in `insertPDF` i found

```
      self._reset_page_refs()
       if links:
           self._do_links(docsrc, from_page = from_page, to_page = to_page,
                      start_at = sa)
```

What does the above code do.

**Comment by JorjMcKie** [comment]
I am without proper internet currently, so have to use smart phone.
This code completes the insertion by also copying relevant links. Because of excluding internal links to pages outside the copy range it has to be done separately.
If you do not want that use links=False or annots =False.

Von meinem iPhone gesendet

**Comment by sant527** [comment]
thank you.
