### ISSUE TITLE
Question / Comment: page.getText('rawdict') block bbox out of page

### ISSUE THREAD

**Issue by dothinking** [pymupdf/PyMuPDF#642]
Hi JorjMcKie,

First, many thanks for bringing out this awesome project. I've been using it for almost one year.

I just extract page blocks with `page.getText('rawdict')` and plot each bbox. 

```python
import fitz

# page source
pdf= fitz.open('test.pdf')
layout = pdf[0].getText('rawdict')

# plot in new page
page = pdf.newPage(width=layout['width'], height=layout['height'])
for block in layout['blocks']: page.drawRect(block['bbox'], fill=None)

pdf.save('out.pdf')
pdf.close()
```

Everything is OK until I face this [test.pdf](https://github.com/pymupdf/PyMuPDF/files/5172402/test.pdf) -> bbox out of page, overlaps, look weird... It seems due to the PDF file itself, but is there any pre-processing from `PyMuPDF`  to make the bbox-es look more reasonable? Thank you in advance.

![image](https://user-images.githubusercontent.com/13885442/92194500-6af5ef00-ee9d-11ea-9880-7b9c1481ec32.png)

**Comment by JorjMcKie** [comment]
Looks weird indeed. Re-analyzed a little, but your code correctly marked the existing blocks. The blocks sequence versus the reading sequence is also more or less okay, except the block 0 is at the bottom. Some blocks also contain a lot of line breaks, or even **_only_** line breaks ... but apart from this: nothing unusual except the wild block picture.

**Comment by dothinking** [comment]
If deep into the line contained in block, it generally has a similar height with the text font size, but in this file, the line height is much larger than font size. Seems this make the block picture look weird, but don't know the reason.

**Comment by JorjMcKie** [comment]
I have sort of an explanation:
The PDF contains 3 unnamed fonts, which are Type3 and not embedded. They all contain a huge amount of definition source **_per character_** in the PDF.
So MuPDF is forced to adhere to what those definitions prescribe it to do (haven't followed up those details).
Since you asked for a "pre-processing", I have used my new set of scripts for [font replacement](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/font-replacement) and processed the PDF with it.
And - oh wonder! - out comes a PDF with

* a much more logical and tranquilized block layout
* a smaller PDF size (below 30 KB vs. 110 KB)
* nicer looking characters
* only embedded, size-optimized fonts - no more Type3

I have attached the produced new PDF with drawn block bboxes, and the CSV file that controls which fonts to replace with what in both, before and after editing states. First line of that file resembles the unnamed fonts (empty string before the first semicolon).

Maybe this helps.
[test-new.zip](https://github.com/pymupdf/PyMuPDF/files/5174660/test-new.zip)

**Comment by dothinking** [comment]
It makes great sense and helps a lot. I noticed your new feature replacing font days ago, how surprised that it can be used to solve my newly faced problem! I'll look further into it and give feedback later on.

I've been keeping eyes on issues list of this project, and learnt a lot, not only your professional answers, but your patience. So, thank you.

**Comment by JorjMcKie** [comment]
> surprised that it can be used to solve my newly faced problem

The reason for this to work is how it technically approaches font replacement:
* **_removal_** of all text written in a font that is going to be replaced. This leads to consequential removal of the respective text spans and the reduction of existing text blocks - up to a complete removal of text blocks if all their text was in fonts to be replaced.
* re-insertion of previously removed text - now with the new fonts. This obviously creates new text blocks - the one you see in the example.
* a side effect: replacement fonts are **_always embedded_**, which is conformant with an overall tendency, and also subsetted where possible: not containing unused charatcers.

This also a way to reduce PDF size if you added text via PyMuPDF and now are annoyed about large font sizes in the file: just re-process the PDF with choosing the same name for old and new font.

**Comment by dothinking** [comment]
Many thanks for the explanation and scripts replacing fonts. Your provided pre-processing method fully solved my issue. 

In my case, I don't care much about the PDF itself, but the extracted layout. Inspired by your solution, I'd use below method, not so accurate but simpler: for those spans with **UNNAMED** contained in font name,
- create a dummy `TextWriter`
- set general font, e.g. `Arial`
- set `span['chars'][0]['origin']` as bottom-left point
- `append` span text to the `TextWriter` 
- use the returned `Rect` to update span['bbox']
- update line, block bboxes accordingly

Now, I'm about to close this issue.
