### ISSUE TITLE
Rectangle transform is wrong

### ISSUE THREAD

**Issue by dbrnz** [pymupdf/PyMuPDF#662]
## Problem description

The following transformation is intended to map a square with corners at points `p` and `q` to a 1024x1024 square. Each of the corner points are correctly mapped; however the rectangle is not.

```
>>> import fitz
>>> m = fitz.Matrix(0.0032706661366698362, 0.0, 0.0, -0.0032706661366698362, 512, 512)
>>> p = fitz.Point(-156543.03392804042, 156543.03392804042)
>>> p*m
Point(0.0, 0.0)
>>> q = fitz.Point(156543.03392804042, -156543.03392804042)
>>> q*m
Point(1024.0, 1024.0)
```
As seen above, the corner points transform as expected. However, when we define and transform the corresponding rectangle, the wrong result is returned.
```
>>> r = fitz.Rect(-156543.03392804042, 156543.03392804042, 156543.03392804097, -156543.03392804097)
>>> r*m
Rect(-156543.03125, 156543.03125, 156543.03125, -156543.03125)
>>> r.transform(m)
Rect(-156543.03125, 156543.03125, 156543.03125, -156543.03125)
```

## Configuration
- macOS 10.15.6
- Python 3.7.5
- PyMuPDF installed using `pipenv`

```
>>> fitz.version
('1.17.7', '1.17.0', '20200914063306')
```

**Comment by JorjMcKie** [comment]
The rectangle is **_infinite_**:
```python
>>> r=fitz.Rect(p,q)
>>> r
Rect(-156543.03392804042, 156543.03392804042, 156543.03392804042, -156543.03392804042)
>>> r.isEmpty
False
>>> r.isInfinite
True
```
Quote from the documentation:
```text
transform(m) 
Transforms the rectangle with a matrix and replaces the original.
If the rectangle is empty or infinite, this is a no-operation.
```

**Comment by JorjMcKie** [comment]
If the background of these data is of real importance, you can turn the rectangle in its finite version: ``r.normalize()``, then everything will work:
```python
>>> r.normalize()
Rect(-156543.03392804042, -156543.03392804042, 156543.03392804042, 156543.03392804042)
>>> r.normalize() * m
Rect(0.0, 0.0, 1024.0, 1024.0)
>>> 
```

**Comment by dbrnz** [comment]
Thanks for the explanation. I still consider this a bug (rather than a feature) as the behaviour is counter-intuitive.

If a rectangle is defined by two diagonally opposite corner points then shouldn't its transformation be that rectangle defined by the transformed corner points?? In other words, a topological homeomorphism.

**Comment by JorjMcKie** [comment]
I understand your point - and as a mathematician I once had similar reservations.
But then - this is a Python binding for an existing C library, and the notion of rectangle infiniteness is their invention. They have more counter-intuitive stuff (you don't seem to have read the resp. docu chapters): like

* rectangles that are empty **and** infinite, or
* the ``IRect`` hull of certain non-empty ``Rect``s may still be empty, or
* the corners of ``rect * matrix`` are not the points ``corner * matrix``.  The object defined by the latter is not even a rectangle in the meaning of PDF and MuPDF (even if the matrix is rectilinear), but a quad. Rectangles in PDF context **_must have_** sides parallel to the x-/y-axis.

So, a clear **NO** to your question
> shouldn't its transformation be that rectangle defined by the transformed corner points??

Whatever Artifex/MuPDF's initial motivation was: today it is import to have infinite rectangles, because they serve as a NULL argument in function calls requiring a rectangle parameter (geometry objects in their library calls are always passed by value, not by reference, so passing NULL is not an option).
I was once tempted to ignore infiniteness and always present finite rectangles in my API, but I do have enough other things to worry about in keeping a more or less plausible Python interface.

You should definitely read the documentation to avoid more surprises of that kind.

**Comment by JorjMcKie** [comment]
Correction (see above): I should have written **_"orthogonal"_** matrix.
A **_rectilinear_** matrix in PDF context produces rectangles from rectangles (in the PDF sense). So for example a rotation matrix is **_orthogonal_** (the rectangle corners will become quad corners enclosing 90 degrees), **_but_** **_not rectilinear_** (if other than 90 degree rotations): the resulting rectangle will not be congruent to the source and will have corner points unequal to the source corner images.

**Comment by JorjMcKie** [comment]
An illustration:
black is the source rectangle, which is rotated by 20 degrees (around top-left page corner). The MuPDF result (**_and also PDF result!!_**) is the green rectangle - visibly incongruent.
The blue drawing **_is not a PDF rectangle_**, but the quad constructed from the black corner point images under the rotation.
![grafik](https://user-images.githubusercontent.com/8290722/93712547-9840cf00-fb24-11ea-83b9-e2d4ea0c1e81.png)

So what PDF matrices conceptually do when transforming a rectangle, is first transforming the corners and then building their common rectangle hull.

Let me emphasize again: this is not invented by (Py-) MuPDF, but a central Adobe PDF notion.

**Comment by dbrnz** [comment]
Thanks for the clear example and further explanation. As you say, (Py-)MuPDF is implementing Adobe's PDF model, and I had not appreciated that matrix transforms in this model are not the same as the usual transforms in a 2D graphics environment...

As background, I started using PyMuPDF to convert PDF pages to images (using `getpixmap()`), already having my own rectangle and transform classes. Then when I found that PyMuPDF provided `Rect` and `Matrix`, I thought to use them instead of maintaining my own classes. As you say, read the documentation!

Thanks again.

**Comment by JorjMcKie** [comment]
You are welcome - and also welcome as a PyMuPDF user.
Please do not hesitate to ask questions, suggest improvements, clarify documentation, whatever.

> BTW: ``.transform(m)`` wrt to rectangles is a "forget function" in the general case: multiplying the resulting rect with the inverse ``~m`` **_will not recover the original_** rect.
> However, we are back to normal 2D geometry if we use quads / tetragons instead of rectangles: ``(rect.quad) * m`` delivers a quad with the expected corners, and applying the inverse will also recover the original quad (modulo rounding errors ...).
