### ISSUE TITLE
Program crashing when adding text with fitz to a certain pdf

### ISSUE THREAD

**Issue by ErikDz** [pymupdf/PyMuPDF#692]
## Describe the bug (mandatory)
I want to add text to the top left corner of a page on a certain document, but upon doing so, program crashes. The program works well with other pdfs but this one in particular crashes my program.

## To Reproduce (mandatory)
Code Im using to **add text**:
```python
class Limpiar_pag:

    def __init__(self,page):
        self.page = page #Page I want to write on
        x_default,y_default,x1_default,y1_default = self.page.rect #Getting dimension of page as coordinates
        self.x_default,self.y_default,self.x1_default,self.y1_default = x_default,y_default,x1_default,y1_default 
     
    def add_question_number(self, num_pregunta):

        text = "QUESTION " + str(num_pregunta) + "."
        where = fitz.Point(self.x_default + 50, self.y_default + 50)    # text starts here
        self.page.insertText(where, text,
                        fontsize=20,      
                        color=(1, 0, 0),   # some color (red)
                        overlay=True)      # text in foreground

```
Code I use to **call** this class from my **main** program:
```python
Limpiar_pag_ = Limpiar_pag(beginning_page)
Limpiar_pag_.add_question_number(self.total)
```
As said, it works perfectly with all pdf's I've tried it except [this one](https://drive.google.com/file/d/14kWSpW3rfTrajaWOIh_7XHecPs78x3ke/view).
Problematic page: **page 4**

## Your configuration (mandatory)
 - Operating system: Windows 10 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
 - Python version: 3.7
 - PyMuPDF version: PyMuPDF 1.18.0: Python bindings for the MuPDF 1.18.0 library.

**Comment by JorjMcKie** [comment]
Interesting case!
This PDF is ill-structured in some hidden way: I suspect there is a loop somewhere in the object definitions.
I did not locate it yet. When I tried to insert text, my script won't return and run forever. In the task manager I am seeing the storage consumption to 10 GB and more.

I will see where I need to insert check points detecting such circumstances.
As a quick solution for you is "cleaning" each page before you insert anything. Immediately before `self.page.insertText(...` insert this instruction: `self.page.cleanContents()`.
This will clean the page appearance syntax and synchronize it with the page's object definition. As a by-product, any loops will also be detected and removed.
You can always do this - it will not harm in cases where everything is already healthy.
The only potential drawback is, that you get a substantial filesize increase if you use incremental saves. This is because a lot is changed by the cleaning, which will consequentially land in the delta data appended to the file. So please make sure you save to a new file with appropriate garbage option and compression.

**Comment by ErikDz** [comment]
Awesome! Thank you so much! I would've never thought of such thing, genius!!!!

**Comment by JorjMcKie** [comment]
Muchas gracias, de verdad!
In the meantime I checked whether it's just me being fooled by your PDF and tried `mutool info -I your.pdf 1`, which lists the images referenced by the /Resources dictionary of page 1 (= page 0 when 0-based). Same happens for `-X` = /XObjects.
Y miralo: that utility also loops, which is a bit of solace.
I have changed PyMuPDF now to detect these circular references. The issue with this type of thing is, that those loops may be **very** long.
Text insertion with your PDF now works again without needing `page.cleanContent()`, which - as commented above - has potentially unwelcome collateral effects.
Your report is very important, because it's not just text insertion which fails:  all information methods `doc.getPageFontList(pno)` and friends will also loop. And this is really serious, because an unsuspecting programmer wouldn't do a `cleanContents()` before this - he might not even have loaded the page with number pno.
So thanks again for bringing this up!

If you would like a pre-version, please let me know and I will drop a wheel in this chat.
Would you agree to send this PDF to the bug report system of MuPDF?

**Comment by JorjMcKie** [comment]
New version 1.18.1 uploaded to PyPI.

**Comment by ErikDz** [comment]
Of course you can have this PDF! Thank you very much again. Im glad that reporting this helped you. As you say, really curious case! :D
