### ISSUE TITLE
How do I delete a searched phrase?

### ISSUE THREAD

**Issue by HydeFromT70s** [pymupdf/PyMuPDF#698]
Hi.

I have the following problem that I have been working on for 3 days without any results.

I have a PDF file with, among other stuff, the same hidden text on each page. It's not a Annotation nor Watermark. Let say it's a "Sample text 1234" string. I want to find this phrase on each page and replace it with, for example, "Blah blah blah" or even better - to completely remove it.

The thing is this text shows as a "normal text" on some pages, I mean the .getText() function can display it and on some pages it can't because this text is "invisible" (it looks like it's written in a rectangle because the .searchFor() function returns a Rect object and the .getTextbox() function can displays this).

I'm not a python expert so please forgive me if I made some elementary mistakes. So far I have come up with something like this. In theory program searches each page for searchedPhrase and if it finds it, it replaces it with newPhrase. Finally, it updates the current and modified stream and writes to a new file. In theory, since the new file still has the text unmodified.

It is very important for me that this program works as it should, but I cannot cope with it myself :(
Can someone help me, please?

`    import fitz

    doc = fitz.open("sample.pdf")
    searchedPhrase = "Sample text 1234"
    newPhrase = "New text"

    for page in doc:
        xref = page.getContents()[0]
        pageStream = doc.xrefStream(xref).decode("utf8").splitlines()
        tempStream = []

        for line in pageStream:

            if line.startswith("BT"):
                textBeginPosition = line.find(searchedPhrase)

                if textBeginPosition:
                    line = line.replace(searchedPhrase, newPhrase)

            tempStream.append(line)

        finalStream = "\n".join(tempStream).encode()
        doc.updateStream(xref, finalStream)

    print(f"Before: {pageStream}")
    print(f"After: {finalStream}")

    doc.save("a.pdf")`

**Comment by JorjMcKie** [comment]
Your case looks like ideal for redaction annotations.
This lets you (permantly) remove text, images and links. As you only want to remove some specific text, do this:
```python
# assuming you know the rectangle within which the text is located: rect
annot = page.addRedactAnnot(rect)
# add more such annotations if you have multiple such rects, finally do
page.apply_redations()
# if you want to make sure to keep overlapping images:
page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)
# then save the doc to a new PDF:
doc.save("new.pdf", garbage=3, deflate=True)
```
This process will remove everything that overlaps annotation rectangles. This decision is made by character: they get removed if their bboxes overlap.
Other users have seen cases, where the redaction rectangle overlaps unwanted other text. If that's the case, let me know to discuss further options.

**Comment by HydeFromT70s** [comment]
I don't think this is the case. The method you described does not work. Perhaps I misinterpreted it, but after executing the code below, the hidden text is still present in the new PDF file. The only noticeable difference is that the hidden text has become visible on some pages.
`
    doc = fitz.open("sample.pdf")
    searchedPhrase = "Sample text 1234"

    for page in doc:
        pageTextRect = page.searchFor(searchedPhrase)
        pageText = page.getTextbox(pageTextRect)
        print(f"Before {page.number}: \n{pageText}\n\n")

        annot = page.addRedactAnnot(pageTextRect)
        page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)

        print(f"After {page.number}: \n{pageText}\n\n")

        doc.save("a.pdf", garbage=3, deflate=True)
`
Maybe I could email you this pdf file and you could take a closer look at it?

**Comment by JorjMcKie** [comment]
> Maybe I could email you this pdf file and you could take a closer look at it?

Yes, please do so.

**Comment by flamedmg** [comment]
It doesn't work for me either. Text blocks are still on their places

**Comment by JorjMcKie** [comment]
@flamedmg 
> It doesn't work for me either. Text blocks are still on their places

It did work in the example of @HydeFromT70s - he sent me his file offline and we solved the problem easy-peasy.
So, why don't you also submit your file and code snippet.

**Comment by JorjMcKie** [comment]
To clarify that the original issue was **_resolved_** I have marke it correspondingly.

**Comment by flamedmg** [comment]
That's because my hands are typing faster then my mind is able to think :) It removes text, but i found a way how to remove header and footer just by not copying them to the resulting pdf. Thank you, for you prompt help!

**Comment by deepak-coding-art** [comment]
Can there be another solution to delete the original text line in the blocks because redaction annotations also covers if there is under the text like a signature.

I extracted the text by using `page.get_text("dict", sort=False)`

now I have a dictionary with `blocks` -> `lines` -> `spans`
 
I want to delete the text in a line and add new text by using the `page.insert_text()` method 
I can use the origin given in the dictionary for placing the text but I need a way to delete the old text 

Thanks

**Comment by JorjMcKie** [comment]
Redactions delete **_any_** character that intersects the redaction rectangle, and - depending on the apply option - punches holes in **_any_** intersecting images.
This cannot be influenced otherwise. Specifically, you cannot have exceptions for selective characters or images. Everything that overlaps, will be deleted.

**Comment by deepak-coding-art** [comment]
actually I want to make script for translating the pdf document so i want to remove the original text and add the translate text in its place

**Comment by JorjMcKie** [comment]
> actually I want to make script for translating the pdf document so i want to remove the original text and add the translate text in its place

You can of course remove all original text and then write the translated new text onto the page.

**Comment by deepak-coding-art** [comment]
this is the code i am using for adding the annotations to all lines of the page:

```
# Add white annotation
def add_anno(page,rect):
    page.add_redact_annot(fitz.Rect(rect), text=None, fontname=None, fontsize=11, align=0, fill=(1,1,1), text_color=(0, 0, 0), cross_out=True)
    page.apply_redactions(2)

# add the annotation to all the lines in a page
def add_all_anno():
    for pageIndex, pageElement in enumerate(pageElements):
     page = pages[pageIndex]
     blocks = pageElement["blocks"]
     for blockIndex, block in enumerate(blocks):
          if "lines" not in block:
              continue
          lines = block["lines"]
          for lineIndex, line in enumerate(lines):
            bound_box = line["bbox"]
            span = line["spans"][0]
            if "text" not in span:
                continue
            text = span["text"]
            if text == "":
                continue
            if text == "\n":
                continue
            if text == " ":
                continue
            add_anno(page,bound_box)
```

**Comment by deepak-coding-art** [comment]
Can there be another solution for removing the text like remove the text directly just like a pdf editor software does like: LibreOffice-Draw

**Comment by deepak-coding-art** [comment]
Okay 
thanks for helping

**Comment by james-curtis** [comment]
> > Can there be another solution for removing the text like remove the text directly just like a pdf editor software does like: LibreOffice-Draw
> 
> There is no such thing, sorry.

Sorry to wake this thread again. I would like to confirm once again whether it is possible to implement the Adobe Acrobat 'Content:View and edit page content information' function, so as to achieve the direct deletion of 'text', 'image', 'path' and so on

![image](https://github.com/pymupdf/PyMuPDF/assets/49338067/dbfa9bc5-7c69-44cc-85f9-6c9213cf26e2)

**Comment by JorjMcKie** [comment]
Ok, then let me re-iterate:
The only clean, non-hacky method to remove and replace text from a page is using redaction annotations.
This approach has the additional advantage that undesired text present as part of an image **_is supported!_**  The one prerequisite for the latter is the we must know the coordinates of that text (e.g. via OCR-ing the image).

PyMuPDF since some time also supports a clean way to remove (or replace) images from pages.

Removing or modifying vector graphics has no such corresponding feature.

If however you are not afraid of the effort, then you can access and edit a PDF page's "appearance source code", the `/Contents` object(s).
These objects in PDF's nomenclature are "streams": any number of bytes wrapped in the string pair "stream" / "endstream".
PyMuPDF lets you extract them via `doc.xref_stream(xref)` and rewrite them via `doc.update_stream(xref, newstream)`.

Such an undertaking requires a lot of background knowledge - too much to go into any detail here.
To create a foolproof way to do it this way, requires to n essence write your own PDF viewer.
