### ISSUE TITLE
cannot import when making a executable file with Pyinstaller

### ISSUE THREAD

**Issue by PyJudge** [pymupdf/PyMuPDF#712]
I have tried to make a exe file using pyInstaller several times, with or without the option --hidden-import 
However, I kept getting messages like this.
(Windows 10 64)

Traceback (most recent call last):
  File "LawClerk_Kwon\main_window.py", line 10, in <module>
  File "C:\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "LawClerk_Kwon\PDF_parser\save_case_from_PDF.py", line 2, in <module>
ModuleNotFoundError: No module named 'fitz'
[40400] Failed to execute script main_window

Any suggestions? 
Thanks a lot in advance!

**Comment by JorjMcKie** [comment]
Cannot reproduce at the moment, because my pyinstaller version has the issue
```
AttributeError: type object 'Callable' has no attribute '_abc_registry'
pre-safe-import-module hook failed, needs fixing.
```
But you could experiment and try additional hidden import from fitz import _fitz or insert this line in your script.
I remember that nuitka had to include this as hidden import, too.
BTW you could use nuitka to create the exe file as well.

**Comment by JorjMcKie** [comment]
Did this help you in any way?
