### ISSUE TITLE
Highlight if matched whole word only 

### ISSUE THREAD

**Issue by jaichandrasreeram** [pymupdf/PyMuPDF#715]
Hi,

I am trying to highlight the words which are matched exactly in the PDF with the custom list, currently, if the word is residing in between the other word also it's highlighting 
like if I have the word _**"harm"**_ in the list, its searched in pdf and its highlighting _p**harm**acy_  also 
![image](https://user-images.githubusercontent.com/74171485/98652733-15890300-2362-11eb-944c-484c51a0453a.png)

Please suggest on this, and below is the code snippet which I am using

```
import fitz
pdf_file = "12300395.pdf"
blue  = (0, 0, 1)
doc = fitz.open(pdf_file)
NumPages = doc.pageCount

m = ["harm", "monitor", "glucose"]
for i in range(0, NumPages):
    page = doc[i]  
    word_customs = page.getText("words")

    for word in word_customs:
        print(word[4])
        text_instances = page.searchFor(word[4])
        for inst in text_instances:        
            annot = page.addRectAnnot(inst) # 'Square'
            annot.setBorder(width=0)
            annot.setColors(stroke=blue,fill=blue)
            annot.setOpacity(0.3)
            annot.update() 

doc.save("output.pdf")
```

**Comment by JorjMcKie** [comment]
I recommend looking at [this](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/word%26line-marking) folder.
I think you will find a solution for your case.

Some general comments:
I don't see you need `page.searchFor` in your case, because the wordlist already contains all information you'll ever need.
So, in principle you could check whether `word[4]` contains one of your search candidates in `m` (maybe after first converting to lower case).
If `word[4].lower()` is exactly equal to (e.g.) "glucose", you are done and can use the word rectangle rightaway. Otherwise:
If `word[4].lower().endswith("glucose")`, skip it because its some compound word containing glucose.
If  `word[4].lower().startswith("glucose")`, some more logic is required:
1. alphabetic characters may follow: this is another case to skip (compound word)
2. only punctuation character(s) follow: this is a **_valid_** case, but you need to remove the punctuations to compute the reduced rectangle.

All this is covered in script `mark-words.py` in the mentioned folder:
* modify line 117, to skip if `word[4].lower()` does not start with one of the `m` items
* after line 122, add a check whether `rect` indeed equals one of `m` using `page.getTextbox(rect)`.

**Comment by JorjMcKie** [comment]
Please let me know how this works out for you.

**Comment by JorjMcKie** [comment]
I have changed the mentioned script somewhat.
It should now exactly do what you need!

**Comment by jaichandrasreeram** [comment]
Hi,

Thank you for your suggestions it really worked for me, I used
 page.getText("words"),  as i was using before* page.searchFor *this helped
to achieve

Thank you so much for your hep

**Comment by SuryaViswanath** [comment]
I am having a similar issue, but the thing is I need to search for those texts in the pdf file. For this, is there any workaround that you can suggest for me?
