### ISSUE TITLE
pdf2img problem: when pdf form value has some chinese word, the img don't contain the word

### ISSUE THREAD

**Issue by reesezxf** [pymupdf/PyMuPDF#721]
_**Please provide all mandatory information!**_
platform: windows 10
Python version: 3.7 
pymupdf version: 1.18.2
## Describe the bug (mandatory)
 I use pymupdf to convert pdf file to image, I found when pdf form value has some chinese words, the created img don't contain those words。

the pdf2img code 
```
def pdf2img():
   
    pdf_file = os.path.abspath(r'.\_test\work.pdf')
    img_path = os.path.abspath( r'.\_test\tmp')
    pdf_name = os.path.basename(pdf_file)
    pdf_doc = fitz.Document(pdf_file)
    for pg in range(pdf_doc.pageCount):
        page = pdf_doc[pg]
        zoom_x = 1.4
        zoom_y = 1.4
        mat = fitz.Matrix(zoom_x, zoom_y).preRotate(0)
        pix = page.getPixmap(matrix=mat, alpha=False)
        pix.writePNG(img_path+'/'+'img_%s.png' % pg)
```
origin pdf:
![origin_pdf](https://user-images.githubusercontent.com/24872718/98815853-bc54c880-2462-11eb-9c9e-cfbb22cd4db8.png)
created img:
![pdf2img](https://user-images.githubusercontent.com/24872718/98815864-c1197c80-2462-11eb-87ce-8ef424211d46.png)

**Comment by JorjMcKie** [comment]
Please provide a file to reproduce the issue.

**Comment by reesezxf** [comment]
> Please provide a file to reproduce the issue.
thank you for reply, this is a example pdf file .
[work.pdf](https://github.com/pymupdf/PyMuPDF/files/5527524/work.pdf)

**Comment by JorjMcKie** [comment]
Thanks for the file.
Unfortunately it turns out that the problem is "upstream": MuPDF does not support Chinese language in form fields.
This is implicitely stated in the documentation (class `Widget`), but not clearly enough to understand the implication for pixmaps.

I understand that you must feel dissatisfied - but that's the situation. You may want to submit a bug report to MuPDF's system, https://bugs.ghostscript.com/enter_bug.cgi and attach your example file there.
