### ISSUE TITLE
Question / Comment: How can I make Freetext annot transparent?

### ISSUE THREAD

**Issue by chanhlt12** [pymupdf/PyMuPDF#727]
I'm a newbie on Python and PyMuPDF.
I'm trying to add a Freetext annotation to a PDF page.
And I want it to be transparent.
But I don't know how to do that.
I tried to set the `fill_color` to `None`, but that is not the solution.
Please help me this.

Here is my code.

```python
rect = fitz.Rect(0, 0, 100, 100)
text = "Hello world"
annot = page.addFreetextAnnot(rect=rect, text=text, fill_color=None)
annot.update()
```

Thank you.

**Comment by JorjMcKie** [comment]
Here is an example:
```python
import fitz

print(fitz.__doc__)

# some colors
blue = (0, 0, 1)
green = (0, 1, 0)
red = (1, 0, 0)
gold = (1, 1, 0)

# a new PDF with 1 page
doc = fitz.open()
page = doc.newPage()

# start with this rectangle
r = fitz.Rect(100, 100, 200, 150)

# the text, Latin alphabet
t = "¡Un pequeño texto para practicar!"
fonts = ("Helv", "TiRo", "Cour")
# add 3 annots, modify the last one somewhat
for font in fonts:
    annot = page.addFreetextAnnot(r, t, fontname=font, text_color=red, fill_color=gold)
    annot.setBorder({"width": 0.9, "dashes": (3, 2)})
    annot.setOpacity(0.5)  # transparency 50%
    annot.update(border_color=blue)
    r += (0, 75, 0, 75)

# save the PDF
doc.save("a-freetext.pdf")
```

**Comment by chanhlt12** [comment]
@JorjMcKie Thank you for the example.
I am sorry for unclear question.
Actually, I don't want to make everything transparent.
I only want to remove the fill color. That's all.
I don't want to blur the text.

**Comment by JorjMcKie** [comment]
> From the example above, if I set the Opacity to 0, the text will completely disappear.
How can I keep the text ?

Forget about opacity then.
The problem is this: my base library MuPDF (to which PyMuPDF is a Python binding) does not support unfilled freetext rectangles.
Your are the first one to admonish this.
I have just develop a tweak to enforce support of this. Will be published with the next version - probably over the weekend.
What you can do right now: ``annot.update(blend_mode="Multiply",...)`` (watch the right spelling!).
This will cause a similar effect - although not perfect, because annot text does not really **_overlay_** background text, but ... well will be multiplied with its color.

**Comment by JorjMcKie** [comment]
This is the look with a colorless background implemented by the tweak:
![grafik](https://user-images.githubusercontent.com/8290722/99807377-d606a780-2b15-11eb-8ce3-0b9ba417ca72.png)
This is the effect of ``blend_mode="Multiply"`` (note: annot rectangle is filled white!):
![grafik](https://user-images.githubusercontent.com/8290722/99807611-2251e780-2b16-11eb-9956-fce4f25d9827.png)
Looks as if annot text being _**behind**_ background text. This is because black is darker than red (annot text color) and therefore "wins" the multiply game.

**Comment by JorjMcKie** [comment]
New version available on PyPI:
