### ISSUE TITLE
Question / Comment: 

### ISSUE THREAD

**Issue by SuryaViswanath** [pymupdf/PyMuPDF#730]
### Pointing to empty space with quads from getTextBlocks

First of all thanks for creating such a wonderful library to use. I am currently working on a project where I am trying to find the occurrences of a word in the document and highlighting them. For this I am trying to retrieve the text coordinates and using those I am trying to annotate using the `addHighlightAnnot()` function. For the sake of the functions `getTextWords()` and `getTextBlocks()` however, the quads I am obtaining from both of the functions are pointing me to an empty space on the pdf page.
`

    for inst in results:
        text_instances = page.searchFor(inst)
        for text in text_instances:
            highlight = page.addHighlightAnnot(text)`

#532 I was going through this where this pointed me towards the potential issue with the rotation/ coordinates with pdf file however this did help me get the initial `x1,y1` close to the actual position. If anyone could help in pointing me in the right direction to resolve this issue I will be very thankful

**Comment by JorjMcKie** [comment]
As mentioned in the quoted issue, I have undertaken a majpr overhaul of this logic since then:
* All coordinates returned to Python refer to the **unrotated** page
* Before inserting anything (annots, images, text, ...) I am derotating the page, and rotate it back after that. This implies that coordinates provided with such insertions must refer to the unrotated page.

So bottom line: this should not be your problem (fingers crossed ...).

A thing independent from this is what is covered in [this](https://pymupdf.readthedocs.io/en/latest/faq.html#common-issues-and-their-solutions) section, topic **_"Misplaced Item Insertions on PDF Pages"_**. You may have to "neutralize" sloppy geometry changes before your insertions as detailed out there.
If this doesn't help, please provide minimal material to reproduce the case.

**Comment by SuryaViswanath** [comment]
Thanks for the quick reply, the article that you mentioned yes it helped me with the correction of the coordinates. If there is anything that pops up in the future within the same lines of the question I mentioned before I would open this question again. Thanks for your timely help

**Comment by JorjMcKie** [comment]
I hope that this class of problems is tackled. From time to time I have been thinking of ways to prevent this from happening automatically.
That would mean checking `Page.isWrapped` before every insertion ... which may have very unpleasant performance implications.
Maybe setting and checking a ``wrapped`` indicator per page would be a solution ...
