### ISSUE TITLE
"€" character replaced by dot using insertText()

### ISSUE THREAD

**Issue by obensch** [pymupdf/PyMuPDF#733]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When using insertText() to add a string containing the "€" character, this character gets replaced by a dot.
I'm using the default (encoding=fitz.TEXT_ENCODING_LATIN) encoding as described in the documentation: https://pymupdf.readthedocs.io/en/latest/faq.html#how-to-use-non-standard-encoding

## To Reproduce (mandatory)
import fitz
doc = fitz.open()  
page = doc.newPage()  
string = "66,51 €"
page.insertText(fitz.Point(10, 10), string)
doc.save("Test.pdf")

## Screenshots (optional)
Result PDF:
![grafik](https://user-images.githubusercontent.com/6650856/100233170-a5fe4080-2f29-11eb-95ca-6a01df16c138.png)

## Your configuration (mandatory)
 - Windows 10 / VSCode
 - Python 3.8.5
 - PyMuPDF latest version from pip (1.18.4).

**Comment by JorjMcKie** [comment]
This is because:
1. the text is unicode b/o Python 3
2. as such the Euro symbol has ord("€") = 8364 = 0x20ac
3. the implicitely used font Helvetica is a simple font, for which all character codes beyond 255 are converted to the replacement character you saw.

To resolve this, use a font supporting more unicode points, e.g. "C:/Windows/Fonts/arial.ttf", or use the (unofficial) € presentation contained in the Base-14 fonts chr(128) like this: ``text="66,51 " + chr(128)``.

**Comment by JorjMcKie** [comment]
Close issue?
