### ISSUE TITLE
Boldness of font not detected

### ISSUE THREAD

**Issue by mc373906408** [pymupdf/PyMuPDF#742]
In version 1.7. X, bold and italics can be recognized normally, and the updated version can be recognized as lining

{'width': 960.0, 'height': 540.0, 'blocks': [{'number': 0, 'type': 0, 'bbox': (299.260009765625, 211.1668701171875, 660.4839477539062, 271.1908874511719), 'lines':
[{'spans': [{'size': 60.02399826049805, 'flags': 4, 'font': 'SimHei', 'color': 0,
'text': '士大夫士大夫', 'origin': (299.260009765625, 262.75), 'bbox': (299.260009765625, 211.1668701171875, 660.4839477539062, 271.1908874511719)}], 'wmode': 0, 'dir': (1.0, 0.0), 'bbox': (299.260009765625, 211.1668701171875, 660.4839477539062, 271.1908874511719)}]}]}

[2222.pdf](https://github.com/pymupdf/PyMuPDF/files/5629422/2222.pdf)

**Comment by JorjMcKie** [comment]
for v1.18.X and v1.17.X the fllags field is 4 - no difference.
So: what bug are you referring to?
You did not say what you expect

**Comment by mc373906408** [comment]
This is a PDF in bold text, but it is not recognized

**Comment by JorjMcKie** [comment]
> This is a PDF in bold text, but it is not recognized

1. The flags parameter comes directly from information that the font is telling about itself: If it doesn't say "I am bold", then nobody, neither PyMuPDF, nor MuPDF, can find that out otherwise. Many fonts do a sloppy job in that respect.
2. The font is indeed **_not bold_**, because in this case it turns out that the PDF creator used a "fake-bold" mechanism: text rendering mode 2. This is **_not a font property_** obviously, and it is not reflected to the `getText` interface.

So everything works as designed.

**Comment by JorjMcKie** [comment]
Please reopen if you have more questions.
