### ISSUE TITLE
Text extractions failed on character

### ISSUE THREAD

**Issue by IbrahimGerbiqi** [pymupdf/PyMuPDF#759]
## Describe the bug 
I was doing text extraction then annotating sentences that I extracted while doing this I came across a not annotated sentence that was supposed to be, after investigating the cause of the problem a came to a cross something weird that happened while extracting text a character was extracted wrong 'v' was '#'.

## To Reproduce 
[Sample.pdf](https://www.dropbox.com/s/6vo8vszdv3kx8ou/sample.pdf?dl=0)

```
import fitz

doc = fitz.open('sample.pdf')

for page in doc:
    block = page.getText('text')
    print(block)
```

## Expected behavior 
**Teto#о, June 2020** is being extracted, expected to be **Tetovо, June 2020**

 - Operating system: Windows 10
 - Python version: 3.7
 - PyMuPDF version: 1.18.4 installation method: wheel.

**Comment by JorjMcKie** [comment]
I am sorry, but this is an upstream error (i.e. MuPDF).
But the PDF does have problems, see this run protocol:
```
mutool draw -o sample.txt sample.pdf
warning: ignoring one to many mapping in cmap Adobe-Identity-UCS
page sample.pdf 1
warning: ... repeated 3 times...
```
and produces this text file: 
[sample.txt](https://github.com/pymupdf/PyMuPDF/files/5673292/sample.txt)

So I recommend you reproduce this result on your machine (do not use PyMuPDF for this!) and submit the bug to their system: https://bugs.ghostscript.com/enter_bug.cgi.

I doubt they will be very reactive though, because of the PDF's own issues.
