### ISSUE TITLE
Incomplete text retrieval using getText()

### ISSUE THREAD

**Issue by darshanabhandare** [pymupdf/PyMuPDF#771]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
getText or getBlock etc.  is not detecting the top line close to pageBreak.

## To Reproduce (mandatory)
''' 
DATA FILE
https://reports.adviserinfo.sec.gov/reports/ADV/6247/PDF/6247.pdf '''

import fitz

doc = fitz.open('D:/tmp/6247.pdf')
pages = doc.pageCount
print(pages)
p = doc[20]
print(p.getText())

## Expected behavior (optional)
Entire Page Text to be extracted

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/73514918/102312087-0403ce00-3f94-11eb-9251-3f81068c4309.png)
![image](https://user-images.githubusercontent.com/73514918/102312141-24cc2380-3f94-11eb-9f90-a249284084b9.png)

## Your configuration (mandatory)
 - Operating system, Windows + Linux
 - Python version, 3.6
 - PyMuPDF version, installation method (**wheel** or **generated** from source).
 - wheel installation

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
The C base library, MuPDF itself has issues with this PDF. Check out ``mutool draw -o page%d.txt 6247.pdf`` and then take a look at file ``page21.txt``, which is the page we are discussing!

Some background:

* In v1.18.2 I introduced a new parameter `clip` in text search and extraction - for restricting the considered areas to this rectangle. If omitted, clip defaults to the full page.
* Every single character is then checked if **_fully (!) contained_** in `clip`. Characters partly outside are not considered.
* Your PDF has these page rectangles: `Rect(0.0, 0.0, 768.0, 1008.0)`. For an unknown reason, MuPDF in its text extraction API presents also text, which is not contained therein, but has negative vertical (y-) coordinates ... which I consequently ignore.
* The first line's characters you are referring to - although visible / readable - are **_partly_** outside that page! The rectangle's y0 coordinate is negative, y1 is positive.

There are a few options to address this issue:

* You submit a bug report to Artifex / MuPDF here: https://bugs.ghostscript.com/enter_bug.cgi. Attach your file and report what goes wrong using the ``mutool draw -o page%d.txt 6247.pdf``  or ``mutool draw -o page21.txt 6247.pdf 21`` command. Do not refer to PyMuPDF, because they would then reject your report.
* Wait for PyMuPDF v1.18.5 (soon to come): this version allows you to select characters by using the minimum rectangle around them. In your case this would luckily include the first line if the respective new option is activated.

**Comment by JorjMcKie** [comment]
Compare MuPDF's output for page 20: 
[mutool21.txt](https://github.com/pymupdf/PyMuPDF/files/5701629/mutool21.txt)

With the new PyMuPDF version, you would get this:
[newblocks.txt](https://github.com/pymupdf/PyMuPDF/files/5701634/newblocks.txt)

Please compare and let me know how you want to proceed.

**Comment by darshanabhandare** [comment]
Thanks Jorj,
newblocks.txt is what I want. I will wait for new version. 
Thanks for your response nd details about the bg.

**Comment by JorjMcKie** [comment]
> I will wait for new version.

Hope I can make by next weekend.

**Comment by JorjMcKie** [comment]
Solved by v1.18.5 being uploaded now.

**Comment by JorjMcKie** [comment]
To extract the complete text of the pages, execute ``fitz.TOOLS.set_small_glyph_heights(True)``.
This will shrink every character's glyph to font size height - as opposed to the standard line height.
As a consequence, the text extraction logic will count a character as belonging to a page already, if the now smaller bbox is fully inside the page rectangle.

This option is observed by the `page.searchFor()`, `page.getTextbox()` and `page.getText(option, ...)` for option values "text", "words", "blocks", "(raw)dict", "(raw)json" - **_not_** for "(x)html" and "xml".

Unset the option with `False` parameter, inquire with no parameter or `None`. The return is always `True` or `False`.
Instead of using `False` or `True` directly, you can **_use any Python value_**: `bool(value)` will be computed and used internally.

**Comment by darshanabhandare** [comment]
> Solved by v1.18.5 being uploaded now.

Thank you so much !!!!
