### ISSUE TITLE
Can't process two pdfs with fitz in a loop

### ISSUE THREAD

**Issue by ewertonrlima** [pymupdf/PyMuPDF#789]
## To Reproduce (mandatory)

# -*- coding: utf-8 -*-#
import os
import sys
import pymongo
import fitz
import pprint
from fnmatch import fnmatch
import datetime
from datetime import datetime

def processanotas(notascorretagem):
    countnegocios = 0
    notanumero = 0
    contador = 0
    payload = []        
    
    i=0
    while i < len(notascorretagem):
        #for item in notascorretagem: 
        item = notascorretagem[i]
        s = "Empty"
        doc = fitz.open(item)
        page = doc.loadPage(0)
        page = page.getText()
        s = page
        os.remove(item)
        doc.close()
        contador +=1
        i +=1
        .... do my stuff...
    return(payload, countnegocios, notanumero)

## Expected behavior (optional)
The list passed to the function has the path for 2 files. I am trying to process both but only the second one in the list is processed.
This function is being called by a Django view when a POST happens.

## Screenshots (optional)

What am I missing here? Is this a real bug?

## Your configuration (mandatory)
 - Mac Big Sur
 - Python 3.7
 - Latest installed via PIP

Regardless which pdf I use, the function process only the second file in the list.

**Comment by JorjMcKie** [comment]
Well, it for sure is a bug, but not PyMuPDF's bug.
Unfortunately the formatting of you script listing did not work right , so I am not quite certain, how this is supposed to work.
I don't understand why you use ``while`` instead of `for`. If I see it correctly, you just want to read the text of the first page of each document, so simply do the following:
```python
for item in notascorretagem:
    doc=fitz.open(item)
    s = doc[0].getText()
    doc.close()
    print("Finished processing '%s'." % item)
```
In your script you assigned a `Page` to variable `page` and then re-assign the page text to variable `page` again, which you assign one more time to yet another variable.
Why do you try to delete the file at all? ... and even **_before_** you close it! That should never work.
Have you tried to process mutliple documents from a list of filenames outside the context (Django, etc.) you mentioned?
You would probably see, that this works without problems.

**Comment by JorjMcKie** [comment]
Well, it for sure is a bug, but not PyMuPDF's bug.
Unfortunately the formatting of you script listing did not work right , so I am not quite certain, how this is supposed to work.
I don't understand why you use ``while`` instead of `for`. If I see it correctly, you just want to read the text of the first page of each document, so simply do the following:
```python
for item in notascorretagem:
    doc=fitz.open(item)
    s = doc[0].getText()
    doc.close()
    print("Finished processing '%s'." % item)
```
In your script you assigned a `Page` to variable `page` and then re-assign the page text to variable `page` again, which you assign one more time to yet another variable.
Why do you try to delete the file at all? ... and even **_before_** you close it! That should never work.
Have you tried to process mutliple documents from a list of filenames outside the context (Django, etc.) you mentioned?
You would probably see, that this works without problems.

**Comment by JorjMcKie** [comment]
I presume your question is answered?
