### ISSUE TITLE
Page.insertImage() position shows error

### ISSUE THREAD

**Issue by xinsheng** [pymupdf/PyMuPDF#802]
PyMuPDF version 1.18.5

my code:
hFile = fitz.open("test.pdf")
hFile[0].insertImage( fitz.Rect(0,0,100,100),filename='insert.png')
hFile.save("out.pdf")

i expect the image placed on top-left corner, but the result was not, please check the attachments.
https://drive.google.com/drive/folders/13FUMDuj4_eEVQNqOn7-qd1iLYvkrhyJB?usp=sharing

test.pdf - source pdf 
out.pdf - output pdf with error result
insert.png - insert png to pdf

**Comment by JorjMcKie** [comment]
Cannot download from Google drive at the moment - server error.
In the meantime, please be more specific:

- [x] the image **_was_** inserted
- [x] but in the wrong position
- [ ] the image was **_not_** inserted
- [ ] an exception occurred

If the situation is as indicated above, then please do a `page.wrapContents()` before you insert and read [this](https://pymupdf.readthedocs.io/en/latest/faq.html#common-issues-and-their-solutions) chapter of the documentation.

Otherwise, we will have to wait until Google drive is working again.

**Comment by JorjMcKie** [comment]
Ah GD is okay again.
As I suspected: you have a PDF with internal geometry changes. Wrapping the existing page commands as indicated should solve the problem.

**Comment by xinsheng** [comment]
Wow, it works. really appreciate your help @JorjMcKie , thanks!

>>> if not page._isWrapped:
        page.wrapContents()
