### ISSUE TITLE
The fonts written in version 1.18.6 

### ISSUE THREAD

**Issue by malizheng** [pymupdf/PyMuPDF#822]
The fonts written (insertTextbox) in version 1.18.6 will become very compact, affecting the aesthetic feeling, while the previous versions will not.
How can I control the spacing between fonts ?

**Comment by JorjMcKie** [comment]
Please provide mandatory information for a **_bug_** issue.

**Comment by malizheng** [comment]
`insertTextbox(r,res,fontname="song",fontfile='font.ttf', fontsize=9, align=fitz.TEXT_ALIGN_LEFT)`
version 1.18.6
![WechatIMG634](https://user-images.githubusercontent.com/14052596/104200632-dd866500-5463-11eb-89cb-a5fcc12f0b1d.jpeg)
the previous versions  
![WechatIMG635](https://user-images.githubusercontent.com/14052596/104200751-fd1d8d80-5463-11eb-97f3-46765181c731.jpeg)

**Comment by JorjMcKie** [comment]
Ahh, got you!
I think I have introduced a mistake in that version: I tried to compute the adequate line height using properties of the font itself instead of using a fixed value fontsize * 1.2.
There must be an error in that logic.
But there is a new parameter `lineheight` in `insertTextBox` and `insertText`. Please use this for the moment. Set it to 1.2 to get the old appearance.

**Comment by malizheng** [comment]
Thank you very much. It has solved my problem.
