### ISSUE TITLE
addHighlightAnnot function produces ellipses instead of rectangles

### ISSUE THREAD

**Issue by nikolamirkov** [pymupdf/PyMuPDF#826]
## Describe the bug (mandatory)
In some PDFs, the function addHighlightAnnot gives ellipses instead of rectangles.

## To Reproduce (mandatory)

Open a (landscape PDF) document:
b = open(document, 'rb').read()
doc = fitz.open("pdf", b)

Define a rectangle e.g.
rectangle = Rect(439.5434875488281, 306.19671630859375, 444.92999267578125, 486.9599914550781)

Highlight it e.g. on a first page of the PDF:
doc[0].addHighlightAnnot(rectangle)

## Expected behavior (optional)
You are supposed to see a rectangle of highlighted text around 'data to feature continued'.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/66924236/104323273-457d8f80-54e6-11eb-9029-38d149e578b5.png)

## Your configuration (mandatory)

The output of print(sys.version, "\n", sys.platform, "\n", fitz.__doc__):

3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] 
 darwin 
PyMuPDF 1.18.3: Python bindings for the MuPDF 1.18.0 library.
Version date: 2020-11-09 07:36:17.
Built for Python 3.8 on darwin (64-bit).

**Comment by JorjMcKie** [comment]
> You are supposed to see a rectangle of highlighted text around 'data to feature continued'.

No! Highlight annotation **_never_** are simple rectangles: first, the corners are rounded and second the left and the right sides are curved.
So if the highlighted rectangle has a very small width in relation to the height, the result may appear somewhat like an ellipsis standind on a small curve.
In your case it rather looks like the page geometry has been "improperly" changed as explained in "Misplaced Item Insertions on PDF Pages" [here](https://pymupdf.readthedocs.io/en/latest/faq.html#common-issues-and-their-solutions).
Please execute `page.wrapContents()` before you add the highlight annot.

**Comment by nikolamirkov** [comment]
Hi JorjMcKie,

>Thank you so much for your reply! I'm getting "True" when I execute `doc[0]._isWrapped` so the solution you kindly proposed as well as the one on the page you suggest i.e. `Page.cleanContents()` did not solve the issue. I also tried using `sanitize=True` as suggested [here](https://github.com/pymupdf/PyMuPDF/issues/607). None of those worked. 

Do you have any other suggestions?

Thank you so much!

**Comment by JorjMcKie** [comment]
Can you share the PDF?
It does like like the annotation rect is rotated by 90° against the page, because the curved annot sides are top and bottom.
This situation should actually have been taken care of automatically, ...
Where did you get the Rect coordinates from? When I highlight that rect on an empty page, it looks like this
![grafik](https://user-images.githubusercontent.com/8290722/104376443-67cdd800-54fb-11eb-84fc-b8e079c1c1a8.png)

... 90° rotated. What is the value of `page.rotation`?

**Comment by nikolamirkov** [comment]
I got the coordinates by running `doc[0].searchFor('data to feature continued')`. The value of `page.rotation` is 0.

**Comment by JorjMcKie** [comment]
Oha - the file you sent me has page rotation 90!

**Comment by JorjMcKie** [comment]
It definitely is a bug!
As a circumvention, please use `quads=True` in your search - and of course use that result in your adding highlight. This will mark the page correctly (always, I hope):

![grafik](https://user-images.githubusercontent.com/8290722/104424655-0dae3080-5556-11eb-8097-4903a1361a6e.png)

I continue figuring out what goes wrong in the quad-to-rect conversion - in this case.

> Note: Internally, **_always_** quads are delivered by the search. The conversion to rectangles takes place afterwards, if the user did not want quads.

**Comment by nikolamirkov** [comment]
Amazing! Thank you! Just a quick follow up question: 

How can I implement the circumvention you suggest, if I pass the bbox of a span to `addHighlightAnnot()` instead of passing a rectangle from `page.searchFor()`? In the PDF above, the example of a span would be "data to feature continued moderation in deflation " and it's bbox should be (446.63726806640625, 309.0020751953125, 457.4102783203125, 511.19970703125).

**Comment by JorjMcKie** [comment]
You can just do this:
```python
rl = page.searchFor(search_text, quads=True)
page.addHighlightAnnot(rl)
```
that's it. The method will detect whether rectangles or quads are contained in `rl`.
If more than one hits of the search text occurred, then rll will be a list of quads. In that case a common annotation will be created for all hits, but the text of each hit will be highlighted as if handled separately.
This means you can also do this
```python
for q in rl:
    page.addHighlightAnnot(q)
```
and the result will look the same. But there will be as many separate annotations created as there are items in `rl`.

**Comment by nikolamirkov** [comment]
Sorry for the confusion! I was referring to a situation where you want to pass bbox (containing, correct me if I'm wrong, **left**, **top**, **width**, and **height**) to `page.addHighlightAnnot()` instead of using `page.searchFor`. 

Nevertheless, thanks to your suggestion I obtained the correct highlight as you did, by mimicking the output of `page.searchFor(search_text, quads=True)` and therefore passing

`rectangle = [fitz.Quad((fitz.Point(left, height), fitz.Point(left, top), 
                        fitz.Point(width, height), fitz.Point(width, top)))]
`
to

`page.addHighlightAnnot(rectangle)`.

Thank you again!!!

**Comment by JorjMcKie** [comment]
Glad to hear this.
But note that rectangles and rect-likes are defined by two diagonally opposite points: top-left and bottom-right. Not as you suggested involving width & height.

Otherwise also note:
If the page has rotation 0 then just go ahead as you did.
If rotation != 0 then it is important to know, that coordinates you use as parameters are all interpreted **_relative to the unrotated page!_** IAW as if the page were not rotated.
Therefore, in your example, `fitz.Point(0, 0)` is in the **_upper-right_** corner, not the upper left!
You can calculate between those coordinate systems using `page.rotationMatrix`, resp. `page.derotationMatrix`. So relative to the rotated page, this mentioned point obviously has coordinates (792, 0), because its width is equal to the original's height.

```python
>>> page.rotationMatrix
Matrix(0.0, 1.0, -1.0, 0.0, 792.0, 0.0)
>>> fitz.Point(0, 0) * page.rotationMatrix
Point(792.0, 0.0)
```

**Comment by JorjMcKie** [comment]
I have the reason!
I should realized this faster: the problem is inherent to page rotations of 90 or 270 (-90) degrees and not solvable!
The rectangle result of `page.searchFor` is being computed correctly ... **_BUT_** rectangles in the 90° case inevitably lead to errors as you saw them.
The reason is that these text marker annotations are not rotation-symmetric: highlight has curves, no straight lines left and right, underline / squiggly put their lines at the bottom of rectangle,etc.

So wrapping up: when text marking where page rotation is not zero, always make sure to **_use quads, rectangles_**.
I need to clarify this prominently in the documentation.

Your issue is in so far very important - thanks a lot!

**Comment by JorjMcKie** [comment]
So in your example, if you had done this:
```python
rl = page.searchFor(...)  # get rectangle(s), no quads
r = rl[0]  # the delivered rect
# make quad before annotating:
q=fitz.Quad(r.bl,r.tl,r.br, r.tr)  # specify the correct left and right sides!
page.addHighlighAnnot(q)  # also is the right highlight!
```

**Comment by JorjMcKie** [comment]
The same considerations apply if your rectangle comes from from some other source than text searching. For example text extractions delivering position coordinates: whenever one wants to use those for text marking, one must make sure to first compute the right quad version from the delivered bbox coordinates.

**Comment by nikolamirkov** [comment]
great stuff! thank you so much again!

**Comment by JorjMcKie** [comment]
This was a very important issue - thank you again for bringing this up.
Took me an embarrassingly long time to see that my code is right after all 😒 ... and only parts of documentation are missing.

**Comment by JorjMcKie** [comment]
For your peace of mind: I removed the example file you mailed to me.
