### ISSUE TITLE
v1.18.6 PyPI linux sources include_dirs missing "/usr/include/freetype2"

### ISSUE THREAD

**Issue by JackieFei** [pymupdf/PyMuPDF#831]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Amazon Linux cannot install PyMuPDF 1.18.6 from `$ pip install PyMuPDF`

## To Reproduce (mandatory)
`$ pip install PyMuPDF`

error results:
```
  fitz/fitz_wrap.c:2771:10: fatal error：ft2build.h：No such file or directory
   #include <ft2build.h>
            ^~~~~~~~~~~~
```

## Your configuration (mandatory)
 - python 3.7
 - print (sys.platform)
 `linux`
 - freetype2 installed
```
$ pkg-config --cflags freetype2
-I/usr/include/freetype2 -I/usr/include/libpng15
```

## Additional context (optional)
1. Download the pip source from https://files.pythonhosted.org/packages/92/35/6fb6e72ba14e066c4cc5a70dd2afff2b859d3502ddba1d1045a9ef22c23b/PyMuPDF-1.18.6.tar.gz

2. view setup.py
```
# check the platform
if sys.platform.startswith("linux") or "gnu" in sys.platform:
    module = Extension(
        "fitz._fitz",  # name of the module
        ["fitz/fitz_wrap.c"],  # C source file
        include_dirs=[  # we need the path of the MuPDF headers
            "/usr/include/mupdf",
            "/usr/local/include/mupdf",
            "mupdf/thirdparty/freetype/include",
        ],
        libraries=load_libraries(),
    )
```
include_dirs contains:
#### `mupdf/thirdparty/freetype/include`

3. relative to https://github.com/pymupdf/PyMuPDF/blob/master/setup.py
```
# check the platform
if sys.platform.startswith("linux") or "gnu" in sys.platform:
    module = Extension(
        "fitz._fitz",  # name of the module
        ["fitz/fitz.i"],
        include_dirs=[  # we need the path of the MuPDF headers
            "/usr/include/mupdf",
            "/usr/local/include/mupdf",
            "/usr/include/freetype2",
        ],
        libraries=load_libraries(),
    )
```
include_dirs contains:

**Comment by JackieFei** [comment]
We can update the `include_dirs` to build from source, but it is best to install from `$ pip install PyMuPDF`

**Comment by JackieFei** [comment]
We make more tests, it seems not the PyMuPDF PyPI bug.

There is a little strange thing when execute `print (sys.platform.startswith("linux"))` in Amazon Linux.
1. it show `True` in command line,
2. but results `False` in runtime (and maybe in `$ pip install PyMuPDF`).

So we close this issue currently till more Amazon Linux knowledge.

**Comment by JackieFei** [comment]
Hi, @JorjMcKie 

Can you help us to identify the `setup.py` difference between PyPI and Github (as mentioned in issue Additional context) is correct and expected ? (Because we are not familiar with how `pip` using the `setup.py` to install.)

Thanks in advanced.

**Comment by JorjMcKie** [comment]
Sure.
From what I see in the thread, the issue seems to be about the freetype include library?
These headers are required for the PyMuPDF C-source part that accesses some functions and properties around fonts.

Unfortunately, the specification of that folder differes somewhat per platform. Independent from those technical details, you should always specify the folder contained in the MuPDF source - not any other freetype installation that may already exist.

The difference between the `setup.py` versions in the Github repo and on PyPI **_in that respect_** may be just an artifact:
The Github `fitz` folder is used by Linux package managers. They are usually interested in the original, **_non generated_** sources - i.e. they do not want to see `fitz.py` and `fitz_wrap.c` there. So the `setup.py` there contains instructions to **_generate_** those two sources by invoking SWIG ... just as I do on my own machine.

So far, I have no feedback / complains from these guys about any non-fitting include libraries or similar ... which may have a number of reasons of course.

The **_PyPI source content_** on the other hand is the same as I am using it for generating the wheels for OSX and Linux (manylinux platform tag) via the Travic CI service. It does work on Ubuntu and OSX, so I encourage you to use this as a start for your platform.

Hope this helps.

**Comment by JackieFei** [comment]
We have solved this issue (on Amazon Linux) by :

1. $ pip install --upgrade pip
```
Successfully uninstalled pip-9.0.3
Successfully installed pip-20.3.3
```

2. $ pip install PyMuPDF
```
Collecting PyMuPDF
  Downloading PyMuPDF-1.18.6-cp37-cp37m-manylinux2010_x86_64.whl
Successfully installed PyMuPDF-1.18.6
```

Thanks.

**Comment by seisdr** [comment]
what

**Comment by seisdr** [comment]
```
creating build/temp.linux-i686-2.7/fitz
    i686-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-rh9FfC/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/mupdf -I/usr/local/include/mupdf -Imupdf/thirdparty/freetype/include -I/usr/include/python2.7 -c fitz/fitz_wrap.c -o build/temp.linux-i686-2.7/fitz/fitz_wrap.o
    fitz/fitz_wrap.c:2771:10: fatal error: ft2build.h: No such file or directory
     #include <ft2build.h>
              ^~~~~~~~~~~~
    compilation terminated.
    error: command 'i686-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5kQpnm/PyMuPDF/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-W538J1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-5kQpnm/PyMuPDF/
```

**Comment by seisdr** [comment]
v^C
root@localhost:~# find / 2>&1 |grep ft2build.h
/usr/include/freetype2/ft2build.h

**Comment by seisdr** [comment]
Successfully installed pip-20.3.3
