### ISSUE TITLE
annot.addRectAnnot opacity on Mac Preview

### ISSUE THREAD

**Issue by cabal-chan** [pymupdf/PyMuPDF#886]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When clicking on annotation in Preview (MacOS) the opacity gets set to 1.0 and covers the text.

## To Reproduce (mandatory)
Open annotated file in Preview and click the rect annotation.

## Expected behavior (optional)
Select the rect or the text underneath

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/65152862/107127364-772a1200-686a-11eb-83c7-af21f7ffc154.png)
![image](https://user-images.githubusercontent.com/65152862/107127367-7beec600-686a-11eb-9051-26b2b25f34a1.png)

## Your configuration (mandatory)
```
3.7.3 (default, Dec 13 2019, 19:58:14) 
[Clang 11.0.0 (clang-1100.0.33.17)] 
 darwin 
 
PyMuPDF 1.18.8: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-02-03 19:56:11.
Built for Python 3.7 on darwin (64-bit).
```
For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

## Additional context (optional)

```import fitz
### READ IN PDF
# doc = fitz.open("deposition.pdf")
doc = fitz.open("roger.pdf")
# breakpoint()
page = doc[0]
### SEARCH
text = "The interview in the above matter was held in Room HVC-304, the Capitol, commencing at 9:41 a.m."
text_instances = page.searchFor(text)
text2 = "Present: Representatives Conaway, King, LoBiondo, Rooney, Stewart, Gowdy, Hurd, Schiff, Himes, Speier, Quigley, Swalwell, Castro, and Heck."
text_instances2 = page.searchFor(text2)

### HIGHLIGHT
for inst in text_instances:
    highlight = page.addRectAnnot(inst)
    # breakpoint()
    highlight.setColors(fill=(0.24, 0.68, 0.53),stroke=[])
    highlight.setOpacity(0.5)
    flags = highlight.flags
    flags |= fitz.PDF_ANNOT_IS_LOCKED
    flags |= fitz.PDF_ANNOT_IS_READ_ONLY
    highlight.set_flags(flags)
    highlight.update()

for inst in text_instances2:
    highlight = page.addRectAnnot(inst)
    # breakpoint()
    highlight.setColors(fill=(200.0/255.0, 255.0/255.0, 89.0/255.0),stroke=[])
    highlight.setOpacity(0.5)
    flags = highlight.flags
    flags |= fitz.PDF_ANNOT_IS_LOCKED
    flags |= fitz.PDF_ANNOT_IS_READ_ONLY
    highlight.set_flags(flags)
    highlight.update()`
```
I'm resorting to this method since I can't update the highlight color. If there's a better way to do this let me know. I get a weird error saying the following:

mupdf: Highlight annotations have no IC property
warning: annot type has no fill color

**Comment by cabal-chan** [comment]
I've figured out how to update highlight color: 
`highlight.setColors(stroke=(200.0/255.0, 255.0/255.0, 89.0/255.0))`

Looks like highlight only has "Stroke" but no fill.

This is still a weird bug that doesn't seem to happen when opening the pdf on web/adobe.

**Comment by JorjMcKie** [comment]
Guys! it is **_not_** a bug!

1. All 4 text marker annotation types _**have no fill color**_ - underline, highlight, strikeout, squiggle. They all only have a **_stroke_** color. Even though highlight looks like some area is filled with color. This is a PDF design fact and has nothing to do with PyMuPDF / MuPDF. The stroke color is specified with the PDF key `/C`, fill color (where possible) is defined via key `/IC` ("interior color").
2. Annotation colors can be changed via method `annot.set_colors(stroke=color1, fill=color2)`. The fill parameter is rejected (ignored with a warning) where not valid.
3. After color changes, the annot must be updated via `annot.update(...)`.
4. To remove one of the two color types, setting it to `None` won't work, because this value is reserved for "do not touch". Instead use `color=[]`, `fill=[]`, respectively.
5. Annotations colors never have an alpha channel - again by PDF design, not by lack of (Py-) MuPDF's cooperation. Use `annot.set_opacity()` and / or `annot.set_blendmode()` to influence how the other PDF content should appear under the annotation.

**Comment by cabal-chan** [comment]
@JorjMcKie makes sense. I just couldn't find it in the documentation so I resorted to trying a bunch of things out. 

The original bug is using addRectAnnot which causes issues on preview:
`    highlight = page.addRectAnnot(inst)`

**Comment by JorjMcKie** [comment]
Are you saying then, that rect annot opacity does not wok?

**Comment by cabal-chan** [comment]
@JorjMcKie It works initially but when I click on the annotation, it becomes opaque on macOS Preview and I can't revert it back. It seems to be restricted to macOS only though. I tested it on Adobe Acrobat reader and Chrome and it doesn't have that issue there.

**Comment by JorjMcKie** [comment]
Ah, ok. It's a bug with that Preview then.

**Comment by JorjMcKie** [comment]
Good, thanks.
Let's close this issue here then.
