### ISSUE TITLE
[Question] Undelete an annotation

### ISSUE THREAD

**Issue by PowerSnail** [pymupdf/PyMuPDF#899]
The doc of delete_annot says:

> Please remember that physical removal requires saving to a new file with garbage > 0.

Does that mean that there is an easy way to un-delete the annotation, while the file hasn't been saved?

Of course I can re-insert a new annotation, with the same attributes, but the problem is that the order of annotation will not be the same.

Thanks!

**Comment by JorjMcKie** [comment]
> Does that mean that there is an easy way to un-delete the annotation, while the file hasn't been saved?

1. If you `doc.close()` and then re-open (for example by `doc = fitz.open(doc.name)`), the document is in the **_state before all changes_** since the last save. You cannot undo some changes, but accept others.
2. If you do a `doc.saveIncr()´ or `doc.save(doc.name, incremental=True,...)`, the document will **_contain_** your changes. But physically the previous document state continues to exist. There is no way to go back to an earlier version via PyMuPDF, but I quite often use a capable editor to a remove recent incremental updates. Fairly easy thing to do. And of course, with incremental updates, the file size will always grow.
3. If you do not use incremental updates, deleted stuff does not go away physically if you use `garbage=0`. The file size will also grow, but earlier viersions cannot be recovered. To recover space and to remove potentially sensitive data also physically, use a garbage collection value > 0. Please look up the documentation to learn about the differences between values 1 to 4.
